// Generated by gencs from shape_msgs/Plane.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace shape_msgs {

    [System.Serializable]
    public class Plane : ROSMessage
    {
      public double[]  coef;


      public Plane()
      {
        coef = new double[4];

      }

      public Plane(double[]  _coef)
      {
        coef = _coef;
      }

      new public static string GetMessageType()
      {
        return "shape_msgs/Plane";
      }

      new public static string GetMD5Hash()
      {
        return "2c1b92ed8f31492f8e73f6a4a44ca796";
      }

    } // class Plane

  } // namespace shape_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
