// Generated by gencs from visualization_msgs/srv/GetInteractiveMarkers.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace visualization_msgs {
        namespace srv {

            public class GetInteractiveMarkers : ROSBridgeServiceProvider<GetInteractiveMarkers_Request>
            {

                public GetInteractiveMarkers(string serviceName) : base(serviceName)
                {
                    _type = "visualization_msgs/srv/GetInteractiveMarkers";
                }

                public GetInteractiveMarkers(string serviceName, string serviceType = "visualization_msgs/srv/GetInteractiveMarkers") : base(serviceName, serviceType) {}

            } // class GetInteractiveMarkers

            [System.Serializable]
            public class GetInteractiveMarkers_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public GetInteractiveMarkers_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public GetInteractiveMarkers_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "visualization_msgs/srv/GetInteractiveMarkers_Request";
                }

            } // class GetInteractiveMarkers_Request

            [System.Serializable]
            public class GetInteractiveMarkers_Response : ServiceResponse
            {
                public System.UInt64 sequence_number;
                public System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarker>  markers;


                public GetInteractiveMarkers_Response()
                {
                    sequence_number = 0;
                    markers = new System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarker>();
                }

                public GetInteractiveMarkers_Response(System.UInt64 _sequence_number, System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarker>  _markers)
                {
                    sequence_number = _sequence_number;
                    markers = _markers;
                }

                new public static string GetMessageType()
                {
                    return "visualization_msgs/srv/GetInteractiveMarkers_Response";
                }

            } // class GetInteractiveMarkers_Response

        } // namespace srv
    } // namespace visualization_msgs
} // namespace ROSBridgeLib
