// Generated by gencs from diagnostic_msgs/msg/DiagnosticArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.diagnostic_msgs.msg;

namespace ROSBridgeLib {

    namespace diagnostic_msgs {
        namespace msg {

            [System.Serializable]
            public class DiagnosticArray : ROSMessage
            {
                public std_msgs.msg.Header header;
                public System.Collections.Generic.List<diagnostic_msgs.msg.DiagnosticStatus>  status;


                public DiagnosticArray()
                {
                    header = new std_msgs.msg.Header();
                    status = new System.Collections.Generic.List<diagnostic_msgs.msg.DiagnosticStatus>();
                }

                public DiagnosticArray(std_msgs.msg.Header _header, System.Collections.Generic.List<diagnostic_msgs.msg.DiagnosticStatus>  _status)
                {
                    header = _header;
                    status = _status;
                }

                new public static string GetMessageType()
                {
                    return "diagnostic_msgs/msg/DiagnosticArray";
                }

            } // class DiagnosticArray

        } // namespace msg
    } // namespace diagnostic_msgs

} // namespace ROSBridgeLib
