// Generated by gencs from diagnostic_msgs/msg/DiagnosticStatus.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.diagnostic_msgs.msg;

namespace ROSBridgeLib {

    namespace diagnostic_msgs {
        namespace msg {

            [System.Serializable]
            public class DiagnosticStatus : ROSMessage
            {
                public sbyte level;
                public string name;
                public string message;
                public string hardware_id;
                public System.Collections.Generic.List<diagnostic_msgs.msg.KeyValue>  values;

                // Constants:
                public const sbyte OK = 0;
                public const sbyte WARN = 1;
                public const sbyte ERROR = 2;
                public const sbyte STALE = 3;

                public DiagnosticStatus()
                {
                    level = 0;
                    name = "";
                    message = "";
                    hardware_id = "";
                    values = new System.Collections.Generic.List<diagnostic_msgs.msg.KeyValue>();
                }

                public DiagnosticStatus(sbyte _level, string _name, string _message, string _hardware_id, System.Collections.Generic.List<diagnostic_msgs.msg.KeyValue>  _values)
                {
                    level = _level;
                    name = _name;
                    message = _message;
                    hardware_id = _hardware_id;
                    values = _values;
                }

                new public static string GetMessageType()
                {
                    return "diagnostic_msgs/msg/DiagnosticStatus";
                }

            } // class DiagnosticStatus

        } // namespace msg
    } // namespace diagnostic_msgs

} // namespace ROSBridgeLib
