// Generated by gencs from diagnostic_msgs/msg/KeyValue.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace diagnostic_msgs {
        namespace msg {

            [System.Serializable]
            public class KeyValue : ROSMessage
            {
                public string key;
                public string value;


                public KeyValue()
                {
                    key = "";
                    value = "";
                }

                public KeyValue(string _key, string _value)
                {
                    key = _key;
                    value = _value;
                }

                new public static string GetMessageType()
                {
                    return "diagnostic_msgs/msg/KeyValue";
                }

            } // class KeyValue

        } // namespace msg
    } // namespace diagnostic_msgs

} // namespace ROSBridgeLib
