// Generated by gencs from nav_msgs/msg/GridCells.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace nav_msgs {
        namespace msg {

            [System.Serializable]
            public class GridCells : ROSMessage
            {
                public std_msgs.msg.Header header;
                public float cell_width;
                public float cell_height;
                public System.Collections.Generic.List<UnityEngine.Vector3>  cells;


                public GridCells()
                {
                    header = new std_msgs.msg.Header();
                    cell_width = 0.0f;
                    cell_height = 0.0f;
                    cells = new System.Collections.Generic.List<UnityEngine.Vector3>();
                }

                public GridCells(std_msgs.msg.Header _header, float _cell_width, float _cell_height, System.Collections.Generic.List<UnityEngine.Vector3>  _cells)
                {
                    header = _header;
                    cell_width = _cell_width;
                    cell_height = _cell_height;
                    cells = _cells;
                }

                new public static string GetMessageType()
                {
                    return "nav_msgs/msg/GridCells";
                }

            } // class GridCells

        } // namespace msg
    } // namespace nav_msgs

} // namespace ROSBridgeLib
