// Generated by gencs from nav_msgs/msg/Path.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace nav_msgs {
        namespace msg {

            [System.Serializable]
            public class Path : ROSMessage
            {
                public std_msgs.msg.Header header;
                public System.Collections.Generic.List<geometry_msgs.msg.PoseStamped>  poses;


                public Path()
                {
                    header = new std_msgs.msg.Header();
                    poses = new System.Collections.Generic.List<geometry_msgs.msg.PoseStamped>();
                }

                public Path(std_msgs.msg.Header _header, System.Collections.Generic.List<geometry_msgs.msg.PoseStamped>  _poses)
                {
                    header = _header;
                    poses = _poses;
                }

                new public static string GetMessageType()
                {
                    return "nav_msgs/msg/Path";
                }

            } // class Path

        } // namespace msg
    } // namespace nav_msgs

} // namespace ROSBridgeLib
