// Generated by gencs from stereo_msgs/msg/DisparityImage.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.sensor_msgs.msg;

namespace ROSBridgeLib {

    namespace stereo_msgs {
        namespace msg {

            [System.Serializable]
            public class DisparityImage : ROSMessage
            {
                public std_msgs.msg.Header header;
                public sensor_msgs.msg.Image image;
                public float f;
                public float t;
                public sensor_msgs.msg.RegionOfInterest valid_window;
                public float min_disparity;
                public float max_disparity;
                public float delta_d;


                public DisparityImage()
                {
                    header = new std_msgs.msg.Header();
                    image = new sensor_msgs.msg.Image();
                    f = 0.0f;
                    t = 0.0f;
                    valid_window = new sensor_msgs.msg.RegionOfInterest();
                    min_disparity = 0.0f;
                    max_disparity = 0.0f;
                    delta_d = 0.0f;
                }

                public DisparityImage(std_msgs.msg.Header _header, sensor_msgs.msg.Image _image, float _f, float _t, sensor_msgs.msg.RegionOfInterest _valid_window, float _min_disparity, float _max_disparity, float _delta_d)
                {
                    header = _header;
                    image = _image;
                    f = _f;
                    t = _t;
                    valid_window = _valid_window;
                    min_disparity = _min_disparity;
                    max_disparity = _max_disparity;
                    delta_d = _delta_d;
                }

                new public static string GetMessageType()
                {
                    return "stereo_msgs/msg/DisparityImage";
                }

            } // class DisparityImage

        } // namespace msg
    } // namespace stereo_msgs

} // namespace ROSBridgeLib
