// Generated by gencs from actionlib_msgs/GoalStatus.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.actionlib_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace actionlib_msgs {

    [System.Serializable]
    public class GoalStatus : ROSMessage
    {
      public actionlib_msgs.GoalID goal_id;
      public byte status;
      public string text;

      public const byte PENDING = 0;
      public const byte ACTIVE = 1;
      public const byte PREEMPTED = 2;
      public const byte SUCCEEDED = 3;
      public const byte ABORTED = 4;
      public const byte REJECTED = 5;
      public const byte PREEMPTING = 6;
      public const byte RECALLING = 7;
      public const byte RECALLED = 8;
      public const byte LOST = 9;

      public GoalStatus()
      {
        goal_id = new actionlib_msgs.GoalID();
        status = 0;
        text = "";

      }

      public GoalStatus(actionlib_msgs.GoalID _goal_id, byte _status, string _text)
      {
        goal_id = _goal_id;
        status = _status;
        text = _text;
      }

      new public static string GetMessageType()
      {
        return "actionlib_msgs/GoalStatus";
      }

      new public static string GetMD5Hash()
      {
        return "d388f9b87b3c471f784434d671988d4a";
      }

    } // class GoalStatus

  } // namespace actionlib_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
