// Generated by gencs from actionlib_msgs/GoalStatusArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.actionlib_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace actionlib_msgs {

    [System.Serializable]
    public class GoalStatusArray : ROSMessage
    {
      public std_msgs.Header header;
      public System.Collections.Generic.List<actionlib_msgs.GoalStatus>  status_list;


      public GoalStatusArray()
      {
        header = new std_msgs.Header();
        status_list = new System.Collections.Generic.List<actionlib_msgs.GoalStatus>();

      }

      public GoalStatusArray(std_msgs.Header _header, System.Collections.Generic.List<actionlib_msgs.GoalStatus>  _status_list)
      {
        header = _header;
        status_list = _status_list;
      }

      new public static string GetMessageType()
      {
        return "actionlib_msgs/GoalStatusArray";
      }

      new public static string GetMD5Hash()
      {
        return "8b2b82f13216d0a8ea88bd3af735e619";
      }

    } // class GoalStatusArray

  } // namespace actionlib_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
