// Generated by gencs from actionlib_msgs/GoalID.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace actionlib_msgs {

    [System.Serializable]
    public class GoalID : ROSMessage
    {
      public ROSBridgeLib.msg_helpers.Time stamp;
      public string id;


      public GoalID()
      {
        stamp = new ROSBridgeLib.msg_helpers.Time();
        id = "";

      }

      public GoalID(ROSBridgeLib.msg_helpers.Time _stamp, string _id)
      {
        stamp = _stamp;
        id = _id;
      }

      new public static string GetMessageType()
      {
        return "actionlib_msgs/GoalID";
      }

      new public static string GetMD5Hash()
      {
        return "302881f31927c1df708a2dbab0e80ee8";
      }

    } // class GoalID

  } // namespace actionlib_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
