// Generated by gencs from geometry_msgs/msg/AccelWithCovarianceStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class AccelWithCovarianceStamped : ROSMessage
            {
                public std_msgs.msg.Header header;
                public geometry_msgs.msg.AccelWithCovariance accel;


                public AccelWithCovarianceStamped()
                {
                    header = new std_msgs.msg.Header();
                    accel = new geometry_msgs.msg.AccelWithCovariance();
                }

                public AccelWithCovarianceStamped(std_msgs.msg.Header _header, geometry_msgs.msg.AccelWithCovariance _accel)
                {
                    header = _header;
                    accel = _accel;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/AccelWithCovarianceStamped";
                }

            } // class AccelWithCovarianceStamped

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
