// Generated by gencs from geometry_msgs/msg/AccelWithCovariance.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class AccelWithCovariance : ROSMessage
            {
                public geometry_msgs.msg.Accel accel;
                public double[]  covariance;


                public AccelWithCovariance()
                {
                    accel = new geometry_msgs.msg.Accel();
                    covariance = new double[36];
                }

                public AccelWithCovariance(geometry_msgs.msg.Accel _accel, double[]  _covariance)
                {
                    accel = _accel;
                    covariance = _covariance;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/AccelWithCovariance";
                }

            } // class AccelWithCovariance

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
