// Generated by gencs from geometry_msgs/msg/Inertia.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class Inertia : ROSMessage
            {
                public double m;
                public UnityEngine.Vector3 com;
                public double ixx;
                public double ixy;
                public double ixz;
                public double iyy;
                public double iyz;
                public double izz;


                public Inertia()
                {
                    m = 0.0f;
                    com = new UnityEngine.Vector3();
                    ixx = 0.0f;
                    ixy = 0.0f;
                    ixz = 0.0f;
                    iyy = 0.0f;
                    iyz = 0.0f;
                    izz = 0.0f;
                }

                public Inertia(double _m, UnityEngine.Vector3 _com, double _ixx, double _ixy, double _ixz, double _iyy, double _iyz, double _izz)
                {
                    m = _m;
                    com = _com;
                    ixx = _ixx;
                    ixy = _ixy;
                    ixz = _ixz;
                    iyy = _iyy;
                    iyz = _iyz;
                    izz = _izz;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/Inertia";
                }

            } // class Inertia

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
