// Generated by gencs from geometry_msgs/msg/InertiaStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class InertiaStamped : ROSMessage
            {
                public std_msgs.msg.Header header;
                public geometry_msgs.msg.Inertia inertia;


                public InertiaStamped()
                {
                    header = new std_msgs.msg.Header();
                    inertia = new geometry_msgs.msg.Inertia();
                }

                public InertiaStamped(std_msgs.msg.Header _header, geometry_msgs.msg.Inertia _inertia)
                {
                    header = _header;
                    inertia = _inertia;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/InertiaStamped";
                }

            } // class InertiaStamped

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
