// Generated by gencs from geometry_msgs/msg/Point32.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class Point32 : ROSMessage
            {
                public float x;
                public float y;
                public float z;


                public Point32()
                {
                    x = 0.0f;
                    y = 0.0f;
                    z = 0.0f;
                }

                public Point32(float _x, float _y, float _z)
                {
                    x = _x;
                    y = _y;
                    z = _z;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/Point32";
                }

            } // class Point32

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
