// Generated by gencs from geometry_msgs/msg/PointStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class PointStamped : ROSMessage
            {
                public std_msgs.msg.Header header;
                public UnityEngine.Vector3 point;


                public PointStamped()
                {
                    header = new std_msgs.msg.Header();
                    point = new UnityEngine.Vector3();
                }

                public PointStamped(std_msgs.msg.Header _header, UnityEngine.Vector3 _point)
                {
                    header = _header;
                    point = _point;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/PointStamped";
                }

            } // class PointStamped

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
