// Generated by gencs from geometry_msgs/msg/PolygonStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class PolygonStamped : ROSMessage
            {
                public std_msgs.msg.Header header;
                public geometry_msgs.msg.Polygon polygon;


                public PolygonStamped()
                {
                    header = new std_msgs.msg.Header();
                    polygon = new geometry_msgs.msg.Polygon();
                }

                public PolygonStamped(std_msgs.msg.Header _header, geometry_msgs.msg.Polygon _polygon)
                {
                    header = _header;
                    polygon = _polygon;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/PolygonStamped";
                }

            } // class PolygonStamped

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
