// Generated by gencs from geometry_msgs/msg/PoseArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class PoseArray : ROSMessage
            {
                public std_msgs.msg.Header header;
                public System.Collections.Generic.List<geometry_msgs.msg.Pose>  poses;


                public PoseArray()
                {
                    header = new std_msgs.msg.Header();
                    poses = new System.Collections.Generic.List<geometry_msgs.msg.Pose>();
                }

                public PoseArray(std_msgs.msg.Header _header, System.Collections.Generic.List<geometry_msgs.msg.Pose>  _poses)
                {
                    header = _header;
                    poses = _poses;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/PoseArray";
                }

            } // class PoseArray

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
