// Generated by gencs from geometry_msgs/msg/Pose.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class Pose : ROSMessage
            {
                public UnityEngine.Vector3 position;
                public UnityEngine.Quaternion orientation;


                public Pose()
                {
                    position = new UnityEngine.Vector3();
                    orientation = new UnityEngine.Quaternion();
                }

                public Pose(UnityEngine.Vector3 _position, UnityEngine.Quaternion _orientation)
                {
                    position = _position;
                    orientation = _orientation;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/Pose";
                }

            } // class Pose

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
