// Generated by gencs from geometry_msgs/msg/PoseStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class PoseStamped : ROSMessage
            {
                public std_msgs.msg.Header header;
                public geometry_msgs.msg.Pose pose;


                public PoseStamped()
                {
                    header = new std_msgs.msg.Header();
                    pose = new geometry_msgs.msg.Pose();
                }

                public PoseStamped(std_msgs.msg.Header _header, geometry_msgs.msg.Pose _pose)
                {
                    header = _header;
                    pose = _pose;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/PoseStamped";
                }

            } // class PoseStamped

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
