// Generated by gencs from geometry_msgs/msg/PoseWithCovarianceStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class PoseWithCovarianceStamped : ROSMessage
            {
                public std_msgs.msg.Header header;
                public geometry_msgs.msg.PoseWithCovariance pose;


                public PoseWithCovarianceStamped()
                {
                    header = new std_msgs.msg.Header();
                    pose = new geometry_msgs.msg.PoseWithCovariance();
                }

                public PoseWithCovarianceStamped(std_msgs.msg.Header _header, geometry_msgs.msg.PoseWithCovariance _pose)
                {
                    header = _header;
                    pose = _pose;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/PoseWithCovarianceStamped";
                }

            } // class PoseWithCovarianceStamped

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
