// Generated by gencs from geometry_msgs/msg/Quaternion.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class Quaternion : ROSMessage
            {
                public double x;
                public double y;
                public double z;
                public double w;


                public Quaternion()
                {
                    x = 0.0f;
                    y = 0.0f;
                    z = 0.0f;
                    w = 0.0f;
                }

                public Quaternion(double _x, double _y, double _z, double _w)
                {
                    x = _x;
                    y = _y;
                    z = _z;
                    w = _w;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/Quaternion";
                }

            } // class Quaternion

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
