// Generated by gencs from geometry_msgs/msg/QuaternionStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class QuaternionStamped : ROSMessage
            {
                public std_msgs.msg.Header header;
                public UnityEngine.Quaternion quaternion;


                public QuaternionStamped()
                {
                    header = new std_msgs.msg.Header();
                    quaternion = new UnityEngine.Quaternion();
                }

                public QuaternionStamped(std_msgs.msg.Header _header, UnityEngine.Quaternion _quaternion)
                {
                    header = _header;
                    quaternion = _quaternion;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/QuaternionStamped";
                }

            } // class QuaternionStamped

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
