// Generated by gencs from geometry_msgs/msg/Transform.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class Transform : ROSMessage
            {
                public UnityEngine.Vector3 translation;
                public UnityEngine.Quaternion rotation;


                public Transform()
                {
                    translation = new UnityEngine.Vector3();
                    rotation = new UnityEngine.Quaternion();
                }

                public Transform(UnityEngine.Vector3 _translation, UnityEngine.Quaternion _rotation)
                {
                    translation = _translation;
                    rotation = _rotation;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/Transform";
                }

            } // class Transform

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
