// Generated by gencs from geometry_msgs/msg/TransformStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class TransformStamped : ROSMessage
            {
                public std_msgs.msg.Header header;
                public string child_frame_id;
                public geometry_msgs.msg.Transform transform;


                public TransformStamped()
                {
                    header = new std_msgs.msg.Header();
                    child_frame_id = "";
                    transform = new geometry_msgs.msg.Transform();
                }

                public TransformStamped(std_msgs.msg.Header _header, string _child_frame_id, geometry_msgs.msg.Transform _transform)
                {
                    header = _header;
                    child_frame_id = _child_frame_id;
                    transform = _transform;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/TransformStamped";
                }

            } // class TransformStamped

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
