// Generated by gencs from geometry_msgs/msg/TwistStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class TwistStamped : ROSMessage
            {
                public std_msgs.msg.Header header;
                public geometry_msgs.msg.Twist twist;


                public TwistStamped()
                {
                    header = new std_msgs.msg.Header();
                    twist = new geometry_msgs.msg.Twist();
                }

                public TwistStamped(std_msgs.msg.Header _header, geometry_msgs.msg.Twist _twist)
                {
                    header = _header;
                    twist = _twist;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/TwistStamped";
                }

            } // class TwistStamped

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
