// Generated by gencs from geometry_msgs/msg/TwistWithCovarianceStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class TwistWithCovarianceStamped : ROSMessage
            {
                public std_msgs.msg.Header header;
                public geometry_msgs.msg.TwistWithCovariance twist;


                public TwistWithCovarianceStamped()
                {
                    header = new std_msgs.msg.Header();
                    twist = new geometry_msgs.msg.TwistWithCovariance();
                }

                public TwistWithCovarianceStamped(std_msgs.msg.Header _header, geometry_msgs.msg.TwistWithCovariance _twist)
                {
                    header = _header;
                    twist = _twist;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/TwistWithCovarianceStamped";
                }

            } // class TwistWithCovarianceStamped

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
