// Generated by gencs from geometry_msgs/msg/TwistWithCovariance.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class TwistWithCovariance : ROSMessage
            {
                public geometry_msgs.msg.Twist twist;
                public double[]  covariance;


                public TwistWithCovariance()
                {
                    twist = new geometry_msgs.msg.Twist();
                    covariance = new double[36];
                }

                public TwistWithCovariance(geometry_msgs.msg.Twist _twist, double[]  _covariance)
                {
                    twist = _twist;
                    covariance = _covariance;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/TwistWithCovariance";
                }

            } // class TwistWithCovariance

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
