// Generated by gencs from geometry_msgs/msg/Vector3.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class Vector3 : ROSMessage
            {
                public double x;
                public double y;
                public double z;


                public Vector3()
                {
                    x = 0.0f;
                    y = 0.0f;
                    z = 0.0f;
                }

                public Vector3(double _x, double _y, double _z)
                {
                    x = _x;
                    y = _y;
                    z = _z;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/Vector3";
                }

            } // class Vector3

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
