// Generated by gencs from geometry_msgs/msg/WrenchStamped.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class WrenchStamped : ROSMessage
            {
                public std_msgs.msg.Header header;
                public geometry_msgs.msg.Wrench wrench;


                public WrenchStamped()
                {
                    header = new std_msgs.msg.Header();
                    wrench = new geometry_msgs.msg.Wrench();
                }

                public WrenchStamped(std_msgs.msg.Header _header, geometry_msgs.msg.Wrench _wrench)
                {
                    header = _header;
                    wrench = _wrench;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/WrenchStamped";
                }

            } // class WrenchStamped

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
