// Generated by gencs from geometry_msgs/msg/Wrench.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace geometry_msgs {
        namespace msg {

            [System.Serializable]
            public class Wrench : ROSMessage
            {
                public UnityEngine.Vector3 force;
                public UnityEngine.Vector3 torque;


                public Wrench()
                {
                    force = new UnityEngine.Vector3();
                    torque = new UnityEngine.Vector3();
                }

                public Wrench(UnityEngine.Vector3 _force, UnityEngine.Vector3 _torque)
                {
                    force = _force;
                    torque = _torque;
                }

                new public static string GetMessageType()
                {
                    return "geometry_msgs/msg/Wrench";
                }

            } // class Wrench

        } // namespace msg
    } // namespace geometry_msgs

} // namespace ROSBridgeLib
