// Generated by gencs from actionlib_msgs/msg/GoalID.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.builtin_interfaces.msg;

namespace ROSBridgeLib {

    namespace actionlib_msgs {
        namespace msg {

            [System.Serializable]
            public class GoalID : ROSMessage
            {
                public builtin_interfaces.msg.Time stamp;
                public string id;


                public GoalID()
                {
                    stamp = new builtin_interfaces.msg.Time();
                    id = "";
                }

                public GoalID(builtin_interfaces.msg.Time _stamp, string _id)
                {
                    stamp = _stamp;
                    id = _id;
                }

                new public static string GetMessageType()
                {
                    return "actionlib_msgs/msg/GoalID";
                }

            } // class GoalID

        } // namespace msg
    } // namespace actionlib_msgs

} // namespace ROSBridgeLib
