// Generated by gencs from actionlib_msgs/msg/GoalStatusArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.actionlib_msgs.msg;

namespace ROSBridgeLib {

    namespace actionlib_msgs {
        namespace msg {

            [System.Serializable]
            public class GoalStatusArray : ROSMessage
            {
                public std_msgs.msg.Header header;
                public System.Collections.Generic.List<actionlib_msgs.msg.GoalStatus>  status_list;


                public GoalStatusArray()
                {
                    header = new std_msgs.msg.Header();
                    status_list = new System.Collections.Generic.List<actionlib_msgs.msg.GoalStatus>();
                }

                public GoalStatusArray(std_msgs.msg.Header _header, System.Collections.Generic.List<actionlib_msgs.msg.GoalStatus>  _status_list)
                {
                    header = _header;
                    status_list = _status_list;
                }

                new public static string GetMessageType()
                {
                    return "actionlib_msgs/msg/GoalStatusArray";
                }

            } // class GoalStatusArray

        } // namespace msg
    } // namespace actionlib_msgs

} // namespace ROSBridgeLib
