// Generated by gencs from netft_utils/srv/GetDouble.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace netft_utils {
        namespace srv {

            public class GetDouble : ROSBridgeServiceProvider<GetDouble_Request>
            {

                public GetDouble(string serviceName) : base(serviceName)
                {
                    _type = "netft_utils/srv/GetDouble";
                }

                public GetDouble(string serviceName, string serviceType = "netft_utils/srv/GetDouble") : base(serviceName, serviceType) {}

            } // class GetDouble

            [System.Serializable]
            public class GetDouble_Request : ServiceArgs
            {
                public bool ignore;


                public GetDouble_Request()
                {
                    ignore = false;
                }

                public GetDouble_Request(bool _ignore)
                {
                    ignore = _ignore;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/GetDouble_Request";
                }

            } // class GetDouble_Request

            [System.Serializable]
            public class GetDouble_Response : ServiceResponse
            {
                public double weight;


                public GetDouble_Response()
                {
                    weight = 0.0f;
                }

                public GetDouble_Response(double _weight)
                {
                    weight = _weight;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/GetDouble_Response";
                }

            } // class GetDouble_Response

        } // namespace srv
    } // namespace netft_utils
} // namespace ROSBridgeLib
