// Generated by gencs from netft_utils/srv/SetBias.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace netft_utils {
        namespace srv {

            public class SetBias : ROSBridgeServiceProvider<SetBias_Request>
            {

                public SetBias(string serviceName) : base(serviceName)
                {
                    _type = "netft_utils/srv/SetBias";
                }

                public SetBias(string serviceName, string serviceType = "netft_utils/srv/SetBias") : base(serviceName, serviceType) {}

            } // class SetBias

            [System.Serializable]
            public class SetBias_Request : ServiceArgs
            {
                public bool to_bias;
                public double force_max;
                public double torque_max;


                public SetBias_Request()
                {
                    to_bias = false;
                    force_max = 0.0f;
                    torque_max = 0.0f;
                }

                public SetBias_Request(bool _to_bias, double _force_max, double _torque_max)
                {
                    to_bias = _to_bias;
                    force_max = _force_max;
                    torque_max = _torque_max;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/SetBias_Request";
                }

            } // class SetBias_Request

            [System.Serializable]
            public class SetBias_Response : ServiceResponse
            {
                public bool success;


                public SetBias_Response()
                {
                    success = false;
                }

                public SetBias_Response(bool _success)
                {
                    success = _success;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/SetBias_Response";
                }

            } // class SetBias_Response

        } // namespace srv
    } // namespace netft_utils
} // namespace ROSBridgeLib
