// Generated by gencs from netft_utils/srv/SetThreshold.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace netft_utils {
        namespace srv {

            public class SetThreshold : ROSBridgeServiceProvider<SetThreshold_Request>
            {

                public SetThreshold(string serviceName) : base(serviceName)
                {
                    _type = "netft_utils/srv/SetThreshold";
                }

                public SetThreshold(string serviceName, string serviceType = "netft_utils/srv/SetThreshold") : base(serviceName, serviceType) {}

            } // class SetThreshold

            [System.Serializable]
            public class SetThreshold_Request : ServiceArgs
            {
                public geometry_msgs.msg.WrenchStamped data;


                public SetThreshold_Request()
                {
                    data = new geometry_msgs.msg.WrenchStamped();
                }

                public SetThreshold_Request(geometry_msgs.msg.WrenchStamped _data)
                {
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/SetThreshold_Request";
                }

            } // class SetThreshold_Request

            [System.Serializable]
            public class SetThreshold_Response : ServiceResponse
            {
                public bool success;


                public SetThreshold_Response()
                {
                    success = false;
                }

                public SetThreshold_Response(bool _success)
                {
                    success = _success;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/SetThreshold_Response";
                }

            } // class SetThreshold_Response

        } // namespace srv
    } // namespace netft_utils
} // namespace ROSBridgeLib
