// Generated by gencs from netft_utils/srv/SetFilter.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace netft_utils {
        namespace srv {

            public class SetFilter : ROSBridgeServiceProvider<SetFilter_Request>
            {

                public SetFilter(string serviceName) : base(serviceName)
                {
                    _type = "netft_utils/srv/SetFilter";
                }

                public SetFilter(string serviceName, string serviceType = "netft_utils/srv/SetFilter") : base(serviceName, serviceType) {}

            } // class SetFilter

            [System.Serializable]
            public class SetFilter_Request : ServiceArgs
            {
                public bool to_filter;
                public double delta_t;
                public double cutoff_frequency;


                public SetFilter_Request()
                {
                    to_filter = false;
                    delta_t = 0.0f;
                    cutoff_frequency = 0.0f;
                }

                public SetFilter_Request(bool _to_filter, double _delta_t, double _cutoff_frequency)
                {
                    to_filter = _to_filter;
                    delta_t = _delta_t;
                    cutoff_frequency = _cutoff_frequency;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/SetFilter_Request";
                }

            } // class SetFilter_Request

            [System.Serializable]
            public class SetFilter_Response : ServiceResponse
            {
                public byte structure_needs_at_least_one_member;


                public SetFilter_Response()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public SetFilter_Response(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/SetFilter_Response";
                }

            } // class SetFilter_Response

        } // namespace srv
    } // namespace netft_utils
} // namespace ROSBridgeLib
