// Generated by gencs from netft_utils/srv/SetToolData.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace netft_utils {
        namespace srv {

            public class SetToolData : ROSBridgeServiceProvider<SetToolData_Request>
            {

                public SetToolData(string serviceName) : base(serviceName)
                {
                    _type = "netft_utils/srv/SetToolData";
                }

                public SetToolData(string serviceName, string serviceType = "netft_utils/srv/SetToolData") : base(serviceName, serviceType) {}

            } // class SetToolData

            [System.Serializable]
            public class SetToolData_Request : ServiceArgs
            {
                public double mass;
                public double com;


                public SetToolData_Request()
                {
                    mass = 0.0f;
                    com = 0.0f;
                }

                public SetToolData_Request(double _mass, double _com)
                {
                    mass = _mass;
                    com = _com;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/SetToolData_Request";
                }

            } // class SetToolData_Request

            [System.Serializable]
            public class SetToolData_Response : ServiceResponse
            {
                public bool success;


                public SetToolData_Response()
                {
                    success = false;
                }

                public SetToolData_Response(bool _success)
                {
                    success = _success;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/SetToolData_Response";
                }

            } // class SetToolData_Response

        } // namespace srv
    } // namespace netft_utils
} // namespace ROSBridgeLib
