// Generated by gencs from netft_utils/srv/StartSim.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace netft_utils {
        namespace srv {

            public class StartSim : ROSBridgeServiceProvider<StartSim_Request>
            {

                public StartSim(string serviceName) : base(serviceName)
                {
                    _type = "netft_utils/srv/StartSim";
                }

                public StartSim(string serviceName, string serviceType = "netft_utils/srv/StartSim") : base(serviceName, serviceType) {}

            } // class StartSim

            [System.Serializable]
            public class StartSim_Request : ServiceArgs
            {
                public System.Int32 sim_dim;
                public System.Int32 sim_type;
                public double sim_slope;
                public double max_force;


                public StartSim_Request()
                {
                    sim_dim = 0;
                    sim_type = 0;
                    sim_slope = 0.0f;
                    max_force = 0.0f;
                }

                public StartSim_Request(System.Int32 _sim_dim, System.Int32 _sim_type, double _sim_slope, double _max_force)
                {
                    sim_dim = _sim_dim;
                    sim_type = _sim_type;
                    sim_slope = _sim_slope;
                    max_force = _max_force;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/StartSim_Request";
                }

            } // class StartSim_Request

            [System.Serializable]
            public class StartSim_Response : ServiceResponse
            {
                public byte structure_needs_at_least_one_member;


                public StartSim_Response()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public StartSim_Response(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/StartSim_Response";
                }

            } // class StartSim_Response

        } // namespace srv
    } // namespace netft_utils
} // namespace ROSBridgeLib
