// Generated by gencs from netft_utils/srv/StopSim.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace netft_utils {
        namespace srv {

            public class StopSim : ROSBridgeServiceProvider<StopSim_Request>
            {

                public StopSim(string serviceName) : base(serviceName)
                {
                    _type = "netft_utils/srv/StopSim";
                }

                public StopSim(string serviceName, string serviceType = "netft_utils/srv/StopSim") : base(serviceName, serviceType) {}

            } // class StopSim

            [System.Serializable]
            public class StopSim_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public StopSim_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public StopSim_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/StopSim_Request";
                }

            } // class StopSim_Request

            [System.Serializable]
            public class StopSim_Response : ServiceResponse
            {
                public byte structure_needs_at_least_one_member;


                public StopSim_Response()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public StopSim_Response(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/srv/StopSim_Response";
                }

            } // class StopSim_Response

        } // namespace srv
    } // namespace netft_utils
} // namespace ROSBridgeLib
