// Generated by gencs from composition_interfaces/srv/ListNodes.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace composition_interfaces {
        namespace srv {

            public class ListNodes : ROSBridgeServiceProvider<ListNodes_Request>
            {

                public ListNodes(string serviceName) : base(serviceName)
                {
                    _type = "composition_interfaces/srv/ListNodes";
                }

                public ListNodes(string serviceName, string serviceType = "composition_interfaces/srv/ListNodes") : base(serviceName, serviceType) {}

            } // class ListNodes

            [System.Serializable]
            public class ListNodes_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public ListNodes_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public ListNodes_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "composition_interfaces/srv/ListNodes_Request";
                }

            } // class ListNodes_Request

            [System.Serializable]
            public class ListNodes_Response : ServiceResponse
            {
                public System.Collections.Generic.List<string>  full_node_names;
                public System.Collections.Generic.List<System.UInt64>  unique_ids;


                public ListNodes_Response()
                {
                    full_node_names = new System.Collections.Generic.List<string>();
                    unique_ids = new System.Collections.Generic.List<System.UInt64>();
                }

                public ListNodes_Response(System.Collections.Generic.List<string>  _full_node_names, System.Collections.Generic.List<System.UInt64>  _unique_ids)
                {
                    full_node_names = _full_node_names;
                    unique_ids = _unique_ids;
                }

                new public static string GetMessageType()
                {
                    return "composition_interfaces/srv/ListNodes_Response";
                }

            } // class ListNodes_Response

        } // namespace srv
    } // namespace composition_interfaces
} // namespace ROSBridgeLib
