// Generated by gencs from composition_interfaces/srv/LoadNode.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace composition_interfaces {
        namespace srv {

            public class LoadNode : ROSBridgeServiceProvider<LoadNode_Request>
            {

                public LoadNode(string serviceName) : base(serviceName)
                {
                    _type = "composition_interfaces/srv/LoadNode";
                }

                public LoadNode(string serviceName, string serviceType = "composition_interfaces/srv/LoadNode") : base(serviceName, serviceType) {}

            } // class LoadNode

            [System.Serializable]
            public class LoadNode_Request : ServiceArgs
            {
                public string package_name;
                public string plugin_name;
                public string node_name;
                public string node_namespace;
                public byte log_level;
                public System.Collections.Generic.List<string>  remap_rules;
                public System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  parameters;
                public System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  extra_arguments;


                public LoadNode_Request()
                {
                    package_name = "";
                    plugin_name = "";
                    node_name = "";
                    node_namespace = "";
                    log_level = 0;
                    remap_rules = new System.Collections.Generic.List<string>();
                    parameters = new System.Collections.Generic.List<rcl_interfaces.msg.Parameter>();
                    extra_arguments = new System.Collections.Generic.List<rcl_interfaces.msg.Parameter>();
                }

                public LoadNode_Request(string _package_name, string _plugin_name, string _node_name, string _node_namespace, byte _log_level, System.Collections.Generic.List<string>  _remap_rules, System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  _parameters, System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  _extra_arguments)
                {
                    package_name = _package_name;
                    plugin_name = _plugin_name;
                    node_name = _node_name;
                    node_namespace = _node_namespace;
                    log_level = _log_level;
                    remap_rules = _remap_rules;
                    parameters = _parameters;
                    extra_arguments = _extra_arguments;
                }

                new public static string GetMessageType()
                {
                    return "composition_interfaces/srv/LoadNode_Request";
                }

            } // class LoadNode_Request

            [System.Serializable]
            public class LoadNode_Response : ServiceResponse
            {
                public bool success;
                public string error_message;
                public string full_node_name;
                public System.UInt64 unique_id;


                public LoadNode_Response()
                {
                    success = false;
                    error_message = "";
                    full_node_name = "";
                    unique_id = 0;
                }

                public LoadNode_Response(bool _success, string _error_message, string _full_node_name, System.UInt64 _unique_id)
                {
                    success = _success;
                    error_message = _error_message;
                    full_node_name = _full_node_name;
                    unique_id = _unique_id;
                }

                new public static string GetMessageType()
                {
                    return "composition_interfaces/srv/LoadNode_Response";
                }

            } // class LoadNode_Response

        } // namespace srv
    } // namespace composition_interfaces
} // namespace ROSBridgeLib
