// Generated by gencs from composition_interfaces/srv/UnloadNode.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace composition_interfaces {
        namespace srv {

            public class UnloadNode : ROSBridgeServiceProvider<UnloadNode_Request>
            {

                public UnloadNode(string serviceName) : base(serviceName)
                {
                    _type = "composition_interfaces/srv/UnloadNode";
                }

                public UnloadNode(string serviceName, string serviceType = "composition_interfaces/srv/UnloadNode") : base(serviceName, serviceType) {}

            } // class UnloadNode

            [System.Serializable]
            public class UnloadNode_Request : ServiceArgs
            {
                public System.UInt64 unique_id;


                public UnloadNode_Request()
                {
                    unique_id = 0;
                }

                public UnloadNode_Request(System.UInt64 _unique_id)
                {
                    unique_id = _unique_id;
                }

                new public static string GetMessageType()
                {
                    return "composition_interfaces/srv/UnloadNode_Request";
                }

            } // class UnloadNode_Request

            [System.Serializable]
            public class UnloadNode_Response : ServiceResponse
            {
                public bool success;
                public string error_message;


                public UnloadNode_Response()
                {
                    success = false;
                    error_message = "";
                }

                public UnloadNode_Response(bool _success, string _error_message)
                {
                    success = _success;
                    error_message = _error_message;
                }

                new public static string GetMessageType()
                {
                    return "composition_interfaces/srv/UnloadNode_Response";
                }

            } // class UnloadNode_Response

        } // namespace srv
    } // namespace composition_interfaces
} // namespace ROSBridgeLib
