// Generated by gencs from rcl_interfaces/msg/FloatingPointRange.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace rcl_interfaces {
        namespace msg {

            [System.Serializable]
            public class FloatingPointRange : ROSMessage
            {
                public double from_value;
                public double to_value;
                public double step;


                public FloatingPointRange()
                {
                    from_value = 0.0f;
                    to_value = 0.0f;
                    step = 0.0f;
                }

                public FloatingPointRange(double _from_value, double _to_value, double _step)
                {
                    from_value = _from_value;
                    to_value = _to_value;
                    step = _step;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/msg/FloatingPointRange";
                }

            } // class FloatingPointRange

        } // namespace msg
    } // namespace rcl_interfaces

} // namespace ROSBridgeLib
