// Generated by gencs from rcl_interfaces/msg/IntegerRange.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace rcl_interfaces {
        namespace msg {

            [System.Serializable]
            public class IntegerRange : ROSMessage
            {
                public System.Int64 from_value;
                public System.Int64 to_value;
                public System.UInt64 step;


                public IntegerRange()
                {
                    from_value = 0;
                    to_value = 0;
                    step = 0;
                }

                public IntegerRange(System.Int64 _from_value, System.Int64 _to_value, System.UInt64 _step)
                {
                    from_value = _from_value;
                    to_value = _to_value;
                    step = _step;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/msg/IntegerRange";
                }

            } // class IntegerRange

        } // namespace msg
    } // namespace rcl_interfaces

} // namespace ROSBridgeLib
