// Generated by gencs from rcl_interfaces/msg/Log.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.builtin_interfaces.msg;

namespace ROSBridgeLib {

    namespace rcl_interfaces {
        namespace msg {

            [System.Serializable]
            public class Log : ROSMessage
            {
                public builtin_interfaces.msg.Time stamp;
                public byte level;
                public string name;
                public string msg;
                public string file;
                public string function;
                public System.UInt32 line;

                // Constants:
                public const sbyte DEBUG = 10;
                public const sbyte INFO = 20;
                public const sbyte WARN = 30;
                public const sbyte ERROR = 40;
                public const sbyte FATAL = 50;

                public Log()
                {
                    stamp = new builtin_interfaces.msg.Time();
                    level = 0;
                    name = "";
                    msg = "";
                    file = "";
                    function = "";
                    line = 0;
                }

                public Log(builtin_interfaces.msg.Time _stamp, byte _level, string _name, string _msg, string _file, string _function, System.UInt32 _line)
                {
                    stamp = _stamp;
                    level = _level;
                    name = _name;
                    msg = _msg;
                    file = _file;
                    function = _function;
                    line = _line;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/msg/Log";
                }

            } // class Log

        } // namespace msg
    } // namespace rcl_interfaces

} // namespace ROSBridgeLib
