// Generated by gencs from rcl_interfaces/msg/ParameterValue.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace rcl_interfaces {
        namespace msg {

            [System.Serializable]
            public class ParameterValue : ROSMessage
            {
                public byte type;
                public bool bool_value;
                public System.Int64 integer_value;
                public double double_value;
                public string string_value;
                public System.Collections.Generic.List<sbyte>  byte_array_value;
                public System.Collections.Generic.List<bool>  bool_array_value;
                public System.Collections.Generic.List<System.Int64>  integer_array_value;
                public System.Collections.Generic.List<double>  double_array_value;
                public System.Collections.Generic.List<string>  string_array_value;


                public ParameterValue()
                {
                    type = 0;
                    bool_value = false;
                    integer_value = 0;
                    double_value = 0.0f;
                    string_value = "";
                    byte_array_value = new System.Collections.Generic.List<sbyte>();
                    bool_array_value = new System.Collections.Generic.List<bool>();
                    integer_array_value = new System.Collections.Generic.List<System.Int64>();
                    double_array_value = new System.Collections.Generic.List<double>();
                    string_array_value = new System.Collections.Generic.List<string>();
                }

                public ParameterValue(byte _type, bool _bool_value, System.Int64 _integer_value, double _double_value, string _string_value, System.Collections.Generic.List<sbyte>  _byte_array_value, System.Collections.Generic.List<bool>  _bool_array_value, System.Collections.Generic.List<System.Int64>  _integer_array_value, System.Collections.Generic.List<double>  _double_array_value, System.Collections.Generic.List<string>  _string_array_value)
                {
                    type = _type;
                    bool_value = _bool_value;
                    integer_value = _integer_value;
                    double_value = _double_value;
                    string_value = _string_value;
                    byte_array_value = _byte_array_value;
                    bool_array_value = _bool_array_value;
                    integer_array_value = _integer_array_value;
                    double_array_value = _double_array_value;
                    string_array_value = _string_array_value;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/msg/ParameterValue";
                }

            } // class ParameterValue

        } // namespace msg
    } // namespace rcl_interfaces

} // namespace ROSBridgeLib
