// Generated by gencs from rcl_interfaces/msg/Parameter.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.rcl_interfaces.msg;

namespace ROSBridgeLib {

    namespace rcl_interfaces {
        namespace msg {

            [System.Serializable]
            public class Parameter : ROSMessage
            {
                public string name;
                public rcl_interfaces.msg.ParameterValue value;


                public Parameter()
                {
                    name = "";
                    value = new rcl_interfaces.msg.ParameterValue();
                }

                public Parameter(string _name, rcl_interfaces.msg.ParameterValue _value)
                {
                    name = _name;
                    value = _value;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/msg/Parameter";
                }

            } // class Parameter

        } // namespace msg
    } // namespace rcl_interfaces

} // namespace ROSBridgeLib
