// Generated by gencs from rcl_interfaces/msg/ParameterEvent.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.builtin_interfaces.msg;
using ROSBridgeLib.rcl_interfaces.msg;

namespace ROSBridgeLib {

    namespace rcl_interfaces {
        namespace msg {

            [System.Serializable]
            public class ParameterEvent : ROSMessage
            {
                public builtin_interfaces.msg.Time stamp;
                public string node;
                public System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  new_parameters;
                public System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  changed_parameters;
                public System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  deleted_parameters;


                public ParameterEvent()
                {
                    stamp = new builtin_interfaces.msg.Time();
                    node = "";
                    new_parameters = new System.Collections.Generic.List<rcl_interfaces.msg.Parameter>();
                    changed_parameters = new System.Collections.Generic.List<rcl_interfaces.msg.Parameter>();
                    deleted_parameters = new System.Collections.Generic.List<rcl_interfaces.msg.Parameter>();
                }

                public ParameterEvent(builtin_interfaces.msg.Time _stamp, string _node, System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  _new_parameters, System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  _changed_parameters, System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  _deleted_parameters)
                {
                    stamp = _stamp;
                    node = _node;
                    new_parameters = _new_parameters;
                    changed_parameters = _changed_parameters;
                    deleted_parameters = _deleted_parameters;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/msg/ParameterEvent";
                }

            } // class ParameterEvent

        } // namespace msg
    } // namespace rcl_interfaces

} // namespace ROSBridgeLib
