// Generated by gencs from rcl_interfaces/msg/ParameterDescriptor.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.rcl_interfaces.msg;

namespace ROSBridgeLib {

    namespace rcl_interfaces {
        namespace msg {

            [System.Serializable]
            public class ParameterDescriptor : ROSMessage
            {
                public string name;
                public byte type;
                public string description;
                public string additional_constraints;
                public bool read_only;
                public bool dynamic_typing;
                public System.Collections.Generic.List<rcl_interfaces.msg.FloatingPointRange>  floating_point_range;
                public System.Collections.Generic.List<rcl_interfaces.msg.IntegerRange>  integer_range;


                public ParameterDescriptor()
                {
                    name = "";
                    type = 0;
                    description = "";
                    additional_constraints = "";
                    read_only = false;
                    dynamic_typing = false;
                    floating_point_range = new System.Collections.Generic.List<rcl_interfaces.msg.FloatingPointRange>();
                    integer_range = new System.Collections.Generic.List<rcl_interfaces.msg.IntegerRange>();
                }

                public ParameterDescriptor(string _name, byte _type, string _description, string _additional_constraints, bool _read_only, bool _dynamic_typing, System.Collections.Generic.List<rcl_interfaces.msg.FloatingPointRange>  _floating_point_range, System.Collections.Generic.List<rcl_interfaces.msg.IntegerRange>  _integer_range)
                {
                    name = _name;
                    type = _type;
                    description = _description;
                    additional_constraints = _additional_constraints;
                    read_only = _read_only;
                    dynamic_typing = _dynamic_typing;
                    floating_point_range = _floating_point_range;
                    integer_range = _integer_range;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/msg/ParameterDescriptor";
                }

            } // class ParameterDescriptor

        } // namespace msg
    } // namespace rcl_interfaces

} // namespace ROSBridgeLib
