// Generated by gencs from rcl_interfaces/msg/ParameterType.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace rcl_interfaces {
        namespace msg {

            [System.Serializable]
            public class ParameterType : ROSMessage
            {
                public byte structure_needs_at_least_one_member;

                // Constants:
                public const byte PARAMETER_NOT_SET = 0;
                public const byte PARAMETER_BOOL = 1;
                public const byte PARAMETER_INTEGER = 2;
                public const byte PARAMETER_DOUBLE = 3;
                public const byte PARAMETER_STRING = 4;
                public const byte PARAMETER_BYTE_ARRAY = 5;
                public const byte PARAMETER_BOOL_ARRAY = 6;
                public const byte PARAMETER_INTEGER_ARRAY = 7;
                public const byte PARAMETER_DOUBLE_ARRAY = 8;
                public const byte PARAMETER_STRING_ARRAY = 9;

                public ParameterType()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public ParameterType(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/msg/ParameterType";
                }

            } // class ParameterType

        } // namespace msg
    } // namespace rcl_interfaces

} // namespace ROSBridgeLib
