// Generated by gencs from lifecycle_msgs/msg/State.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace lifecycle_msgs {
        namespace msg {

            [System.Serializable]
            public class State : ROSMessage
            {
                public byte id;
                public string label;

                // Constants:
                public const byte PRIMARY_STATE_UNKNOWN = 0;
                public const byte PRIMARY_STATE_UNCONFIGURED = 1;
                public const byte PRIMARY_STATE_INACTIVE = 2;
                public const byte PRIMARY_STATE_ACTIVE = 3;
                public const byte PRIMARY_STATE_FINALIZED = 4;
                public const byte TRANSITION_STATE_CONFIGURING = 10;
                public const byte TRANSITION_STATE_CLEANINGUP = 11;
                public const byte TRANSITION_STATE_SHUTTINGDOWN = 12;
                public const byte TRANSITION_STATE_ACTIVATING = 13;
                public const byte TRANSITION_STATE_DEACTIVATING = 14;
                public const byte TRANSITION_STATE_ERRORPROCESSING = 15;

                public State()
                {
                    id = 0;
                    label = "";
                }

                public State(byte _id, string _label)
                {
                    id = _id;
                    label = _label;
                }

                new public static string GetMessageType()
                {
                    return "lifecycle_msgs/msg/State";
                }

            } // class State

        } // namespace msg
    } // namespace lifecycle_msgs

} // namespace ROSBridgeLib
