// Generated by gencs from lifecycle_msgs/msg/TransitionDescription.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.lifecycle_msgs.msg;

namespace ROSBridgeLib {

    namespace lifecycle_msgs {
        namespace msg {

            [System.Serializable]
            public class TransitionDescription : ROSMessage
            {
                public lifecycle_msgs.msg.Transition transition;
                public lifecycle_msgs.msg.State start_state;
                public lifecycle_msgs.msg.State goal_state;


                public TransitionDescription()
                {
                    transition = new lifecycle_msgs.msg.Transition();
                    start_state = new lifecycle_msgs.msg.State();
                    goal_state = new lifecycle_msgs.msg.State();
                }

                public TransitionDescription(lifecycle_msgs.msg.Transition _transition, lifecycle_msgs.msg.State _start_state, lifecycle_msgs.msg.State _goal_state)
                {
                    transition = _transition;
                    start_state = _start_state;
                    goal_state = _goal_state;
                }

                new public static string GetMessageType()
                {
                    return "lifecycle_msgs/msg/TransitionDescription";
                }

            } // class TransitionDescription

        } // namespace msg
    } // namespace lifecycle_msgs

} // namespace ROSBridgeLib
