// Generated by gencs from lifecycle_msgs/msg/Transition.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace lifecycle_msgs {
        namespace msg {

            [System.Serializable]
            public class Transition : ROSMessage
            {
                public byte id;
                public string label;

                // Constants:
                public const byte TRANSITION_CREATE = 0;
                public const byte TRANSITION_CONFIGURE = 1;
                public const byte TRANSITION_CLEANUP = 2;
                public const byte TRANSITION_ACTIVATE = 3;
                public const byte TRANSITION_DEACTIVATE = 4;
                public const byte TRANSITION_UNCONFIGURED_SHUTDOWN = 5;
                public const byte TRANSITION_INACTIVE_SHUTDOWN = 6;
                public const byte TRANSITION_ACTIVE_SHUTDOWN = 7;
                public const byte TRANSITION_DESTROY = 8;
                public const byte TRANSITION_ON_CONFIGURE_SUCCESS = 10;
                public const byte TRANSITION_ON_CONFIGURE_FAILURE = 11;
                public const byte TRANSITION_ON_CONFIGURE_ERROR = 12;
                public const byte TRANSITION_ON_CLEANUP_SUCCESS = 20;
                public const byte TRANSITION_ON_CLEANUP_FAILURE = 21;
                public const byte TRANSITION_ON_CLEANUP_ERROR = 22;
                public const byte TRANSITION_ON_ACTIVATE_SUCCESS = 30;
                public const byte TRANSITION_ON_ACTIVATE_FAILURE = 31;
                public const byte TRANSITION_ON_ACTIVATE_ERROR = 32;
                public const byte TRANSITION_ON_DEACTIVATE_SUCCESS = 40;
                public const byte TRANSITION_ON_DEACTIVATE_FAILURE = 41;
                public const byte TRANSITION_ON_DEACTIVATE_ERROR = 42;
                public const byte TRANSITION_ON_SHUTDOWN_SUCCESS = 50;
                public const byte TRANSITION_ON_SHUTDOWN_FAILURE = 51;
                public const byte TRANSITION_ON_SHUTDOWN_ERROR = 52;
                public const byte TRANSITION_ON_ERROR_SUCCESS = 60;
                public const byte TRANSITION_ON_ERROR_FAILURE = 61;
                public const byte TRANSITION_ON_ERROR_ERROR = 62;
                public const byte TRANSITION_CALLBACK_SUCCESS = 97;
                public const byte TRANSITION_CALLBACK_FAILURE = 98;
                public const byte TRANSITION_CALLBACK_ERROR = 99;

                public Transition()
                {
                    id = 0;
                    label = "";
                }

                public Transition(byte _id, string _label)
                {
                    id = _id;
                    label = _label;
                }

                new public static string GetMessageType()
                {
                    return "lifecycle_msgs/msg/Transition";
                }

            } // class Transition

        } // namespace msg
    } // namespace lifecycle_msgs

} // namespace ROSBridgeLib
