// Generated by gencs from stereo_msgs/DisparityImage.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.sensor_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace stereo_msgs {

    [System.Serializable]
    public class DisparityImage : ROSMessage
    {
      public std_msgs.Header header;
      public sensor_msgs.Image image;
      public float f;
      public float T;
      public sensor_msgs.RegionOfInterest valid_window;
      public float min_disparity;
      public float max_disparity;
      public float delta_d;


      public DisparityImage()
      {
        header = new std_msgs.Header();
        image = new sensor_msgs.Image();
        f = 0.0f;
        T = 0.0f;
        valid_window = new sensor_msgs.RegionOfInterest();
        min_disparity = 0.0f;
        max_disparity = 0.0f;
        delta_d = 0.0f;

      }

      public DisparityImage(std_msgs.Header _header, sensor_msgs.Image _image, float _f, float _T, sensor_msgs.RegionOfInterest _valid_window, float _min_disparity, float _max_disparity, float _delta_d)
      {
        header = _header;
        image = _image;
        f = _f;
        T = _T;
        valid_window = _valid_window;
        min_disparity = _min_disparity;
        max_disparity = _max_disparity;
        delta_d = _delta_d;
      }

      new public static string GetMessageType()
      {
        return "stereo_msgs/DisparityImage";
      }

      new public static string GetMD5Hash()
      {
        return "04a177815f75271039fa21f16acad8c9";
      }

    } // class DisparityImage

  } // namespace stereo_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
