// Generated by gencs from sensor_msgs/ChannelFloat32.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class ChannelFloat32 : ROSMessage
    {
      public string name;
      public System.Collections.Generic.List<float>  values;


      public ChannelFloat32()
      {
        name = "";
        values = new System.Collections.Generic.List<float>();

      }

      public ChannelFloat32(string _name, System.Collections.Generic.List<float>  _values)
      {
        name = _name;
        values = _values;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/ChannelFloat32";
      }

      new public static string GetMD5Hash()
      {
        return "3d40139cdd33dfedcb71ffeeeb42ae7f";
      }

    } // class ChannelFloat32

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
