// Generated by gencs from sensor_msgs/CompressedImage.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class CompressedImage : ROSMessage
    {
      public std_msgs.Header header;
      public string format;
      public System.Collections.Generic.List<byte>  data;


      public CompressedImage()
      {
        header = new std_msgs.Header();
        format = "";
        data = new System.Collections.Generic.List<byte>();

      }

      public CompressedImage(std_msgs.Header _header, string _format, System.Collections.Generic.List<byte>  _data)
      {
        header = _header;
        format = _format;
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/CompressedImage";
      }

      new public static string GetMD5Hash()
      {
        return "8f7a12909da2c9d3332d540a0977563f";
      }

    } // class CompressedImage

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
