// Generated by gencs from sensor_msgs/Illuminance.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class Illuminance : ROSMessage
    {
      public std_msgs.Header header;
      public double illuminance;
      public double variance;


      public Illuminance()
      {
        header = new std_msgs.Header();
        illuminance = 0.0;
        variance = 0.0;

      }

      public Illuminance(std_msgs.Header _header, double _illuminance, double _variance)
      {
        header = _header;
        illuminance = _illuminance;
        variance = _variance;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/Illuminance";
      }

      new public static string GetMD5Hash()
      {
        return "8cf5febb0952fca9d650c3d11a81a188";
      }

    } // class Illuminance

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
