// Generated by gencs from sensor_msgs/Image.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class Image : ROSMessage
    {
      public std_msgs.Header header;
      public System.UInt32 height;
      public System.UInt32 width;
      public string encoding;
      public byte is_bigendian;
      public System.UInt32 step;
      public System.Collections.Generic.List<byte>  data;


      public Image()
      {
        header = new std_msgs.Header();
        height = 0;
        width = 0;
        encoding = "";
        is_bigendian = 0;
        step = 0;
        data = new System.Collections.Generic.List<byte>();

      }

      public Image(std_msgs.Header _header, System.UInt32 _height, System.UInt32 _width, string _encoding, byte _is_bigendian, System.UInt32 _step, System.Collections.Generic.List<byte>  _data)
      {
        header = _header;
        height = _height;
        width = _width;
        encoding = _encoding;
        is_bigendian = _is_bigendian;
        step = _step;
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/Image";
      }

      new public static string GetMD5Hash()
      {
        return "060021388200f6f0f447d0fcd9c64743";
      }

    } // class Image

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
