// Generated by gencs from sensor_msgs/JointState.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class JointState : ROSMessage
    {
      public std_msgs.Header header;
      public System.Collections.Generic.List<string>  name;
      public System.Collections.Generic.List<double>  position;
      public System.Collections.Generic.List<double>  velocity;
      public System.Collections.Generic.List<double>  effort;


      public JointState()
      {
        header = new std_msgs.Header();
        name = new System.Collections.Generic.List<string>();
        position = new System.Collections.Generic.List<double>();
        velocity = new System.Collections.Generic.List<double>();
        effort = new System.Collections.Generic.List<double>();

      }

      public JointState(std_msgs.Header _header, System.Collections.Generic.List<string>  _name, System.Collections.Generic.List<double>  _position, System.Collections.Generic.List<double>  _velocity, System.Collections.Generic.List<double>  _effort)
      {
        header = _header;
        name = _name;
        position = _position;
        velocity = _velocity;
        effort = _effort;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/JointState";
      }

      new public static string GetMD5Hash()
      {
        return "3066dcd76a6cfaef579bd0f34173e9fd";
      }

    } // class JointState

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
