// Generated by gencs from sensor_msgs/Joy.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class Joy : ROSMessage
    {
      public std_msgs.Header header;
      public System.Collections.Generic.List<float>  axes;
      public System.Collections.Generic.List<System.Int32>  buttons;


      public Joy()
      {
        header = new std_msgs.Header();
        axes = new System.Collections.Generic.List<float>();
        buttons = new System.Collections.Generic.List<System.Int32>();

      }

      public Joy(std_msgs.Header _header, System.Collections.Generic.List<float>  _axes, System.Collections.Generic.List<System.Int32>  _buttons)
      {
        header = _header;
        axes = _axes;
        buttons = _buttons;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/Joy";
      }

      new public static string GetMD5Hash()
      {
        return "5a9ea5f83505693b71e785041e67a8bb";
      }

    } // class Joy

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
