// Generated by gencs from sensor_msgs/LaserScan.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class LaserScan : ROSMessage
    {
      public std_msgs.Header header;
      public float angle_min;
      public float angle_max;
      public float angle_increment;
      public float time_increment;
      public float scan_time;
      public float range_min;
      public float range_max;
      public System.Collections.Generic.List<float>  ranges;
      public System.Collections.Generic.List<float>  intensities;


      public LaserScan()
      {
        header = new std_msgs.Header();
        angle_min = 0.0f;
        angle_max = 0.0f;
        angle_increment = 0.0f;
        time_increment = 0.0f;
        scan_time = 0.0f;
        range_min = 0.0f;
        range_max = 0.0f;
        ranges = new System.Collections.Generic.List<float>();
        intensities = new System.Collections.Generic.List<float>();

      }

      public LaserScan(std_msgs.Header _header, float _angle_min, float _angle_max, float _angle_increment, float _time_increment, float _scan_time, float _range_min, float _range_max, System.Collections.Generic.List<float>  _ranges, System.Collections.Generic.List<float>  _intensities)
      {
        header = _header;
        angle_min = _angle_min;
        angle_max = _angle_max;
        angle_increment = _angle_increment;
        time_increment = _time_increment;
        scan_time = _scan_time;
        range_min = _range_min;
        range_max = _range_max;
        ranges = _ranges;
        intensities = _intensities;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/LaserScan";
      }

      new public static string GetMD5Hash()
      {
        return "90c7ef2dc6895d81024acba2ac42f369";
      }

    } // class LaserScan

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
