// Generated by gencs from sensor_msgs/LaserEcho.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class LaserEcho : ROSMessage
    {
      public System.Collections.Generic.List<float>  echoes;


      public LaserEcho()
      {
        echoes = new System.Collections.Generic.List<float>();

      }

      public LaserEcho(System.Collections.Generic.List<float>  _echoes)
      {
        echoes = _echoes;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/LaserEcho";
      }

      new public static string GetMD5Hash()
      {
        return "8bc5ae449b200fba4d552b4225586696";
      }

    } // class LaserEcho

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
