// Generated by gencs from sensor_msgs/MagneticField.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class MagneticField : ROSMessage
    {
      public std_msgs.Header header;
      public UnityEngine.Vector3 magnetic_field;
      public double[]  magnetic_field_covariance;


      public MagneticField()
      {
        header = new std_msgs.Header();
        magnetic_field = new UnityEngine.Vector3();
        magnetic_field_covariance = new double[9];

      }

      public MagneticField(std_msgs.Header _header, UnityEngine.Vector3 _magnetic_field, double[]  _magnetic_field_covariance)
      {
        header = _header;
        magnetic_field = _magnetic_field;
        magnetic_field_covariance = _magnetic_field_covariance;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/MagneticField";
      }

      new public static string GetMD5Hash()
      {
        return "2f3b0b43eed0c9501de0fa3ff89a45aa";
      }

    } // class MagneticField

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
