// Generated by gencs from sensor_msgs/NavSatFix.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.sensor_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class NavSatFix : ROSMessage
    {
      public std_msgs.Header header;
      public sensor_msgs.NavSatStatus status;
      public double latitude;
      public double longitude;
      public double altitude;
      public double[]  position_covariance;
      public byte position_covariance_type;

      public const byte COVARIANCE_TYPE_UNKNOWN = 0;
      public const byte COVARIANCE_TYPE_APPROXIMATED = 1;
      public const byte COVARIANCE_TYPE_DIAGONAL_KNOWN = 2;
      public const byte COVARIANCE_TYPE_KNOWN = 3;

      public NavSatFix()
      {
        header = new std_msgs.Header();
        status = new sensor_msgs.NavSatStatus();
        latitude = 0.0;
        longitude = 0.0;
        altitude = 0.0;
        position_covariance = new double[9];
        position_covariance_type = 0;

      }

      public NavSatFix(std_msgs.Header _header, sensor_msgs.NavSatStatus _status, double _latitude, double _longitude, double _altitude, double[]  _position_covariance, byte _position_covariance_type)
      {
        header = _header;
        status = _status;
        latitude = _latitude;
        longitude = _longitude;
        altitude = _altitude;
        position_covariance = _position_covariance;
        position_covariance_type = _position_covariance_type;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/NavSatFix";
      }

      new public static string GetMD5Hash()
      {
        return "2d3a8cd499b9b4a0249fb98fd05cfa48";
      }

    } // class NavSatFix

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
