// Generated by gencs from sensor_msgs/Range.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class Range : ROSMessage
    {
      public std_msgs.Header header;
      public byte radiation_type;
      public float field_of_view;
      public float min_range;
      public float max_range;
      public float range;

      public const byte ULTRASOUND = 0;
      public const byte INFRARED = 1;

      public Range()
      {
        header = new std_msgs.Header();
        radiation_type = 0;
        field_of_view = 0.0f;
        min_range = 0.0f;
        max_range = 0.0f;
        range = 0.0f;

      }

      public Range(std_msgs.Header _header, byte _radiation_type, float _field_of_view, float _min_range, float _max_range, float _range)
      {
        header = _header;
        radiation_type = _radiation_type;
        field_of_view = _field_of_view;
        min_range = _min_range;
        max_range = _max_range;
        range = _range;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/Range";
      }

      new public static string GetMD5Hash()
      {
        return "c005c34273dc426c67a020a87bc24148";
      }

    } // class Range

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
