// Generated by gencs from sensor_msgs/RegionOfInterest.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class RegionOfInterest : ROSMessage
    {
      public System.UInt32 x_offset;
      public System.UInt32 y_offset;
      public System.UInt32 height;
      public System.UInt32 width;
      public bool do_rectify;


      public RegionOfInterest()
      {
        x_offset = 0;
        y_offset = 0;
        height = 0;
        width = 0;
        do_rectify = false;

      }

      public RegionOfInterest(System.UInt32 _x_offset, System.UInt32 _y_offset, System.UInt32 _height, System.UInt32 _width, bool _do_rectify)
      {
        x_offset = _x_offset;
        y_offset = _y_offset;
        height = _height;
        width = _width;
        do_rectify = _do_rectify;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/RegionOfInterest";
      }

      new public static string GetMD5Hash()
      {
        return "bdb633039d588fcccb441a4d43ccfe09";
      }

    } // class RegionOfInterest

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
