// Generated by gencs from file sensor_msgs/SetCameraInfo.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ROS1;
using ROSBridgeLib.sensor_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    public class SetCameraInfo : ROSBridgeServiceProvider<sensor_msgs.SetCameraInfoRequest>
    {
      public SetCameraInfo(string serviceName) : base(serviceName)
      {
        _type = "sensor_msgs/SetCameraInfo";
      }

      public SetCameraInfo(string serviceName, string serviceType = "sensor_msgs/SetCameraInfo") : base(serviceName, serviceType) {}
    }

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib

