// Generated by gencs from sensor_msgs/Temperature.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class Temperature : ROSMessage
    {
      public std_msgs.Header header;
      public double temperature;
      public double variance;


      public Temperature()
      {
        header = new std_msgs.Header();
        temperature = 0.0;
        variance = 0.0;

      }

      public Temperature(std_msgs.Header _header, double _temperature, double _variance)
      {
        header = _header;
        temperature = _temperature;
        variance = _variance;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/Temperature";
      }

      new public static string GetMD5Hash()
      {
        return "ff71b307acdbe7c871a5a6d7ed359100";
      }

    } // class Temperature

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
