// Generated by gencs from sensor_msgs/TimeReference.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace sensor_msgs {

    [System.Serializable]
    public class TimeReference : ROSMessage
    {
      public std_msgs.Header header;
      public ROSBridgeLib.msg_helpers.Time time_ref;
      public string source;


      public TimeReference()
      {
        header = new std_msgs.Header();
        time_ref = new ROSBridgeLib.msg_helpers.Time();
        source = "";

      }

      public TimeReference(std_msgs.Header _header, ROSBridgeLib.msg_helpers.Time _time_ref, string _source)
      {
        header = _header;
        time_ref = _time_ref;
        source = _source;
      }

      new public static string GetMessageType()
      {
        return "sensor_msgs/TimeReference";
      }

      new public static string GetMD5Hash()
      {
        return "fded64a0265108ba86c3d38fb11c0c16";
      }

    } // class TimeReference

  } // namespace sensor_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
