// Generated by gencs from visualization_msgs/ImageMarker.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace visualization_msgs {

    [System.Serializable]
    public class ImageMarker : ROSMessage
    {
      public std_msgs.Header header;
      public string ns;
      public System.Int32 id;
      public System.Int32 type;
      public System.Int32 action;
      public UnityEngine.Vector3 position;
      public float scale;
      public std_msgs.ColorRGBA outline_color;
      public byte filled;
      public std_msgs.ColorRGBA fill_color;
      public ROSBridgeLib.msg_helpers.Duration lifetime;
      public System.Collections.Generic.List<UnityEngine.Vector3>  points;
      public System.Collections.Generic.List<std_msgs.ColorRGBA>  outline_colors;

      public const byte CIRCLE = 0;
      public const byte LINE_STRIP = 1;
      public const byte LINE_LIST = 2;
      public const byte POLYGON = 3;
      public const byte POINTS = 4;
      public const byte ADD = 0;
      public const byte REMOVE = 1;

      public ImageMarker()
      {
        header = new std_msgs.Header();
        ns = "";
        id = 0;
        type = 0;
        action = 0;
        position = new UnityEngine.Vector3();
        scale = 0.0f;
        outline_color = new std_msgs.ColorRGBA();
        filled = 0;
        fill_color = new std_msgs.ColorRGBA();
        lifetime = new ROSBridgeLib.msg_helpers.Duration();
        points = new System.Collections.Generic.List<UnityEngine.Vector3>();
        outline_colors = new System.Collections.Generic.List<std_msgs.ColorRGBA>();

      }

      public ImageMarker(std_msgs.Header _header, string _ns, System.Int32 _id, System.Int32 _type, System.Int32 _action, UnityEngine.Vector3 _position, float _scale, std_msgs.ColorRGBA _outline_color, byte _filled, std_msgs.ColorRGBA _fill_color, ROSBridgeLib.msg_helpers.Duration _lifetime, System.Collections.Generic.List<UnityEngine.Vector3>  _points, System.Collections.Generic.List<std_msgs.ColorRGBA>  _outline_colors)
      {
        header = _header;
        ns = _ns;
        id = _id;
        type = _type;
        action = _action;
        position = _position;
        scale = _scale;
        outline_color = _outline_color;
        filled = _filled;
        fill_color = _fill_color;
        lifetime = _lifetime;
        points = _points;
        outline_colors = _outline_colors;
      }

      new public static string GetMessageType()
      {
        return "visualization_msgs/ImageMarker";
      }

      new public static string GetMD5Hash()
      {
        return "1de93c67ec8858b831025a08fbf1b35c";
      }

    } // class ImageMarker

  } // namespace visualization_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
