// Generated by gencs from visualization_msgs/InteractiveMarker.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;
using ROSBridgeLib.ROS1.visualization_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace visualization_msgs {

    [System.Serializable]
    public class InteractiveMarker : ROSMessage
    {
      public std_msgs.Header header;
      public geometry_msgs.Pose pose;
      public string name;
      public string description;
      public float scale;
      public System.Collections.Generic.List<visualization_msgs.MenuEntry>  menu_entries;
      public System.Collections.Generic.List<visualization_msgs.InteractiveMarkerControl>  controls;


      public InteractiveMarker()
      {
        header = new std_msgs.Header();
        pose = new geometry_msgs.Pose();
        name = "";
        description = "";
        scale = 0.0f;
        menu_entries = new System.Collections.Generic.List<visualization_msgs.MenuEntry>();
        controls = new System.Collections.Generic.List<visualization_msgs.InteractiveMarkerControl>();

      }

      public InteractiveMarker(std_msgs.Header _header, geometry_msgs.Pose _pose, string _name, string _description, float _scale, System.Collections.Generic.List<visualization_msgs.MenuEntry>  _menu_entries, System.Collections.Generic.List<visualization_msgs.InteractiveMarkerControl>  _controls)
      {
        header = _header;
        pose = _pose;
        name = _name;
        description = _description;
        scale = _scale;
        menu_entries = _menu_entries;
        controls = _controls;
      }

      new public static string GetMessageType()
      {
        return "visualization_msgs/InteractiveMarker";
      }

      new public static string GetMD5Hash()
      {
        return "dd86d22909d5a3364b384492e35c10af";
      }

    } // class InteractiveMarker

  } // namespace visualization_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
