// Generated by gencs from visualization_msgs/InteractiveMarkerUpdate.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.visualization_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace visualization_msgs {

    [System.Serializable]
    public class InteractiveMarkerUpdate : ROSMessage
    {
      public string server_id;
      public System.UInt64 seq_num;
      public byte type;
      public System.Collections.Generic.List<visualization_msgs.InteractiveMarker>  markers;
      public System.Collections.Generic.List<visualization_msgs.InteractiveMarkerPose>  poses;
      public System.Collections.Generic.List<string>  erases;

      public const byte KEEP_ALIVE = 0;
      public const byte UPDATE = 1;

      public InteractiveMarkerUpdate()
      {
        server_id = "";
        seq_num = 0;
        type = 0;
        markers = new System.Collections.Generic.List<visualization_msgs.InteractiveMarker>();
        poses = new System.Collections.Generic.List<visualization_msgs.InteractiveMarkerPose>();
        erases = new System.Collections.Generic.List<string>();

      }

      public InteractiveMarkerUpdate(string _server_id, System.UInt64 _seq_num, byte _type, System.Collections.Generic.List<visualization_msgs.InteractiveMarker>  _markers, System.Collections.Generic.List<visualization_msgs.InteractiveMarkerPose>  _poses, System.Collections.Generic.List<string>  _erases)
      {
        server_id = _server_id;
        seq_num = _seq_num;
        type = _type;
        markers = _markers;
        poses = _poses;
        erases = _erases;
      }

      new public static string GetMessageType()
      {
        return "visualization_msgs/InteractiveMarkerUpdate";
      }

      new public static string GetMD5Hash()
      {
        return "710d308d0a9276d65945e92dd30b3946";
      }

    } // class InteractiveMarkerUpdate

  } // namespace visualization_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
