// Generated by gencs from visualization_msgs/InteractiveMarkerPose.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace visualization_msgs {

    [System.Serializable]
    public class InteractiveMarkerPose : ROSMessage
    {
      public std_msgs.Header header;
      public geometry_msgs.Pose pose;
      public string name;


      public InteractiveMarkerPose()
      {
        header = new std_msgs.Header();
        pose = new geometry_msgs.Pose();
        name = "";

      }

      public InteractiveMarkerPose(std_msgs.Header _header, geometry_msgs.Pose _pose, string _name)
      {
        header = _header;
        pose = _pose;
        name = _name;
      }

      new public static string GetMessageType()
      {
        return "visualization_msgs/InteractiveMarkerPose";
      }

      new public static string GetMD5Hash()
      {
        return "a6e6833209a196a38d798dadb02c81f8";
      }

    } // class InteractiveMarkerPose

  } // namespace visualization_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
