// Generated by gencs from visualization_msgs/InteractiveMarkerInit.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.visualization_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace visualization_msgs {

    [System.Serializable]
    public class InteractiveMarkerInit : ROSMessage
    {
      public string server_id;
      public System.UInt64 seq_num;
      public System.Collections.Generic.List<visualization_msgs.InteractiveMarker>  markers;


      public InteractiveMarkerInit()
      {
        server_id = "";
        seq_num = 0;
        markers = new System.Collections.Generic.List<visualization_msgs.InteractiveMarker>();

      }

      public InteractiveMarkerInit(string _server_id, System.UInt64 _seq_num, System.Collections.Generic.List<visualization_msgs.InteractiveMarker>  _markers)
      {
        server_id = _server_id;
        seq_num = _seq_num;
        markers = _markers;
      }

      new public static string GetMessageType()
      {
        return "visualization_msgs/InteractiveMarkerInit";
      }

      new public static string GetMD5Hash()
      {
        return "d5f2c5045a72456d228676ab91048734";
      }

    } // class InteractiveMarkerInit

  } // namespace visualization_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
