// Generated by gencs from visualization_msgs/Marker.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace visualization_msgs {

    [System.Serializable]
    public class Marker : ROSMessage
    {
      public std_msgs.Header header;
      public string ns;
      public System.Int32 id;
      public System.Int32 type;
      public System.Int32 action;
      public geometry_msgs.Pose pose;
      public UnityEngine.Vector3 scale;
      public std_msgs.ColorRGBA color;
      public ROSBridgeLib.msg_helpers.Duration lifetime;
      public bool frame_locked;
      public System.Collections.Generic.List<UnityEngine.Vector3>  points;
      public System.Collections.Generic.List<std_msgs.ColorRGBA>  colors;
      public string text;
      public string mesh_resource;
      public bool mesh_use_embedded_materials;

      public const byte ARROW = 0;
      public const byte CUBE = 1;
      public const byte SPHERE = 2;
      public const byte CYLINDER = 3;
      public const byte LINE_STRIP = 4;
      public const byte LINE_LIST = 5;
      public const byte CUBE_LIST = 6;
      public const byte SPHERE_LIST = 7;
      public const byte POINTS = 8;
      public const byte TEXT_VIEW_FACING = 9;
      public const byte MESH_RESOURCE = 10;
      public const byte TRIANGLE_LIST = 11;
      public const byte ADD = 0;
      public const byte MODIFY = 0;
      public const byte DELETE = 2;
      public const byte DELETEALL = 3;

      public Marker()
      {
        header = new std_msgs.Header();
        ns = "";
        id = 0;
        type = 0;
        action = 0;
        pose = new geometry_msgs.Pose();
        scale = new UnityEngine.Vector3();
        color = new std_msgs.ColorRGBA();
        lifetime = new ROSBridgeLib.msg_helpers.Duration();
        frame_locked = false;
        points = new System.Collections.Generic.List<UnityEngine.Vector3>();
        colors = new System.Collections.Generic.List<std_msgs.ColorRGBA>();
        text = "";
        mesh_resource = "";
        mesh_use_embedded_materials = false;

      }

      public Marker(std_msgs.Header _header, string _ns, System.Int32 _id, System.Int32 _type, System.Int32 _action, geometry_msgs.Pose _pose, UnityEngine.Vector3 _scale, std_msgs.ColorRGBA _color, ROSBridgeLib.msg_helpers.Duration _lifetime, bool _frame_locked, System.Collections.Generic.List<UnityEngine.Vector3>  _points, System.Collections.Generic.List<std_msgs.ColorRGBA>  _colors, string _text, string _mesh_resource, bool _mesh_use_embedded_materials)
      {
        header = _header;
        ns = _ns;
        id = _id;
        type = _type;
        action = _action;
        pose = _pose;
        scale = _scale;
        color = _color;
        lifetime = _lifetime;
        frame_locked = _frame_locked;
        points = _points;
        colors = _colors;
        text = _text;
        mesh_resource = _mesh_resource;
        mesh_use_embedded_materials = _mesh_use_embedded_materials;
      }

      new public static string GetMessageType()
      {
        return "visualization_msgs/Marker";
      }

      new public static string GetMD5Hash()
      {
        return "4048c9de2a16f4ae8e0538085ebf1b97";
      }

    } // class Marker

  } // namespace visualization_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
