// Generated by gencs from action_msgs/msg/GoalInfo.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.unique_identifier_msgs.msg;
using ROSBridgeLib.builtin_interfaces.msg;

namespace ROSBridgeLib {

    namespace action_msgs {
        namespace msg {

            [System.Serializable]
            public class GoalInfo : ROSMessage
            {
                public unique_identifier_msgs.msg.UUID goal_id;
                public builtin_interfaces.msg.Time stamp;


                public GoalInfo()
                {
                    goal_id = new unique_identifier_msgs.msg.UUID();
                    stamp = new builtin_interfaces.msg.Time();
                }

                public GoalInfo(unique_identifier_msgs.msg.UUID _goal_id, builtin_interfaces.msg.Time _stamp)
                {
                    goal_id = _goal_id;
                    stamp = _stamp;
                }

                new public static string GetMessageType()
                {
                    return "action_msgs/msg/GoalInfo";
                }

            } // class GoalInfo

        } // namespace msg
    } // namespace action_msgs

} // namespace ROSBridgeLib
