// Generated by gencs from action_msgs/msg/GoalStatus.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.action_msgs.msg;

namespace ROSBridgeLib {

    namespace action_msgs {
        namespace msg {

            [System.Serializable]
            public class GoalStatus : ROSMessage
            {
                public action_msgs.msg.GoalInfo goal_info;
                public sbyte status;

                // Constants:
                public const sbyte STATUS_UNKNOWN = 0;
                public const sbyte STATUS_ACCEPTED = 1;
                public const sbyte STATUS_EXECUTING = 2;
                public const sbyte STATUS_CANCELING = 3;
                public const sbyte STATUS_SUCCEEDED = 4;
                public const sbyte STATUS_CANCELED = 5;
                public const sbyte STATUS_ABORTED = 6;

                public GoalStatus()
                {
                    goal_info = new action_msgs.msg.GoalInfo();
                    status = 0;
                }

                public GoalStatus(action_msgs.msg.GoalInfo _goal_info, sbyte _status)
                {
                    goal_info = _goal_info;
                    status = _status;
                }

                new public static string GetMessageType()
                {
                    return "action_msgs/msg/GoalStatus";
                }

            } // class GoalStatus

        } // namespace msg
    } // namespace action_msgs

} // namespace ROSBridgeLib
