// Generated by gencs from action_msgs/msg/GoalStatusArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.action_msgs.msg;

namespace ROSBridgeLib {

    namespace action_msgs {
        namespace msg {

            [System.Serializable]
            public class GoalStatusArray : ROSMessage
            {
                public System.Collections.Generic.List<action_msgs.msg.GoalStatus>  status_list;


                public GoalStatusArray()
                {
                    status_list = new System.Collections.Generic.List<action_msgs.msg.GoalStatus>();
                }

                public GoalStatusArray(System.Collections.Generic.List<action_msgs.msg.GoalStatus>  _status_list)
                {
                    status_list = _status_list;
                }

                new public static string GetMessageType()
                {
                    return "action_msgs/msg/GoalStatusArray";
                }

            } // class GoalStatusArray

        } // namespace msg
    } // namespace action_msgs

} // namespace ROSBridgeLib
