// Generated by gencs from diagnostic_msgs/srv/AddDiagnostics.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace diagnostic_msgs {
        namespace srv {

            public class AddDiagnostics : ROSBridgeServiceProvider<AddDiagnostics_Request>
            {

                public AddDiagnostics(string serviceName) : base(serviceName)
                {
                    _type = "diagnostic_msgs/srv/AddDiagnostics";
                }

                public AddDiagnostics(string serviceName, string serviceType = "diagnostic_msgs/srv/AddDiagnostics") : base(serviceName, serviceType) {}

            } // class AddDiagnostics

            [System.Serializable]
            public class AddDiagnostics_Request : ServiceArgs
            {
                public string load_namespace;


                public AddDiagnostics_Request()
                {
                    load_namespace = "";
                }

                public AddDiagnostics_Request(string _load_namespace)
                {
                    load_namespace = _load_namespace;
                }

                new public static string GetMessageType()
                {
                    return "diagnostic_msgs/srv/AddDiagnostics_Request";
                }

            } // class AddDiagnostics_Request

            [System.Serializable]
            public class AddDiagnostics_Response : ServiceResponse
            {
                public bool success;
                public string message;


                public AddDiagnostics_Response()
                {
                    success = false;
                    message = "";
                }

                public AddDiagnostics_Response(bool _success, string _message)
                {
                    success = _success;
                    message = _message;
                }

                new public static string GetMessageType()
                {
                    return "diagnostic_msgs/srv/AddDiagnostics_Response";
                }

            } // class AddDiagnostics_Response

        } // namespace srv
    } // namespace diagnostic_msgs
} // namespace ROSBridgeLib
