// Generated by gencs from rcl_interfaces/srv/DescribeParameters.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rcl_interfaces {
        namespace srv {

            public class DescribeParameters : ROSBridgeServiceProvider<DescribeParameters_Request>
            {

                public DescribeParameters(string serviceName) : base(serviceName)
                {
                    _type = "rcl_interfaces/srv/DescribeParameters";
                }

                public DescribeParameters(string serviceName, string serviceType = "rcl_interfaces/srv/DescribeParameters") : base(serviceName, serviceType) {}

            } // class DescribeParameters

            [System.Serializable]
            public class DescribeParameters_Request : ServiceArgs
            {
                public System.Collections.Generic.List<string>  names;


                public DescribeParameters_Request()
                {
                    names = new System.Collections.Generic.List<string>();
                }

                public DescribeParameters_Request(System.Collections.Generic.List<string>  _names)
                {
                    names = _names;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/srv/DescribeParameters_Request";
                }

            } // class DescribeParameters_Request

            [System.Serializable]
            public class DescribeParameters_Response : ServiceResponse
            {
                public System.Collections.Generic.List<rcl_interfaces.msg.ParameterDescriptor>  descriptors;


                public DescribeParameters_Response()
                {
                    descriptors = new System.Collections.Generic.List<rcl_interfaces.msg.ParameterDescriptor>();
                }

                public DescribeParameters_Response(System.Collections.Generic.List<rcl_interfaces.msg.ParameterDescriptor>  _descriptors)
                {
                    descriptors = _descriptors;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/srv/DescribeParameters_Response";
                }

            } // class DescribeParameters_Response

        } // namespace srv
    } // namespace rcl_interfaces
} // namespace ROSBridgeLib
