// Generated by gencs from rcl_interfaces/srv/GetParameterTypes.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rcl_interfaces {
        namespace srv {

            public class GetParameterTypes : ROSBridgeServiceProvider<GetParameterTypes_Request>
            {

                public GetParameterTypes(string serviceName) : base(serviceName)
                {
                    _type = "rcl_interfaces/srv/GetParameterTypes";
                }

                public GetParameterTypes(string serviceName, string serviceType = "rcl_interfaces/srv/GetParameterTypes") : base(serviceName, serviceType) {}

            } // class GetParameterTypes

            [System.Serializable]
            public class GetParameterTypes_Request : ServiceArgs
            {
                public System.Collections.Generic.List<string>  names;


                public GetParameterTypes_Request()
                {
                    names = new System.Collections.Generic.List<string>();
                }

                public GetParameterTypes_Request(System.Collections.Generic.List<string>  _names)
                {
                    names = _names;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/srv/GetParameterTypes_Request";
                }

            } // class GetParameterTypes_Request

            [System.Serializable]
            public class GetParameterTypes_Response : ServiceResponse
            {
                public System.Collections.Generic.List<byte>  types;


                public GetParameterTypes_Response()
                {
                    types = new System.Collections.Generic.List<byte>();
                }

                public GetParameterTypes_Response(System.Collections.Generic.List<byte>  _types)
                {
                    types = _types;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/srv/GetParameterTypes_Response";
                }

            } // class GetParameterTypes_Response

        } // namespace srv
    } // namespace rcl_interfaces
} // namespace ROSBridgeLib
