// Generated by gencs from rcl_interfaces/srv/GetParameters.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rcl_interfaces {
        namespace srv {

            public class GetParameters : ROSBridgeServiceProvider<GetParameters_Request>
            {

                public GetParameters(string serviceName) : base(serviceName)
                {
                    _type = "rcl_interfaces/srv/GetParameters";
                }

                public GetParameters(string serviceName, string serviceType = "rcl_interfaces/srv/GetParameters") : base(serviceName, serviceType) {}

            } // class GetParameters

            [System.Serializable]
            public class GetParameters_Request : ServiceArgs
            {
                public System.Collections.Generic.List<string>  names;


                public GetParameters_Request()
                {
                    names = new System.Collections.Generic.List<string>();
                }

                public GetParameters_Request(System.Collections.Generic.List<string>  _names)
                {
                    names = _names;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/srv/GetParameters_Request";
                }

            } // class GetParameters_Request

            [System.Serializable]
            public class GetParameters_Response : ServiceResponse
            {
                public System.Collections.Generic.List<rcl_interfaces.msg.ParameterValue>  values;


                public GetParameters_Response()
                {
                    values = new System.Collections.Generic.List<rcl_interfaces.msg.ParameterValue>();
                }

                public GetParameters_Response(System.Collections.Generic.List<rcl_interfaces.msg.ParameterValue>  _values)
                {
                    values = _values;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/srv/GetParameters_Response";
                }

            } // class GetParameters_Response

        } // namespace srv
    } // namespace rcl_interfaces
} // namespace ROSBridgeLib
