// Generated by gencs from rcl_interfaces/srv/ListParameters.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rcl_interfaces {
        namespace srv {

            public class ListParameters : ROSBridgeServiceProvider<ListParameters_Request>
            {

                public ListParameters(string serviceName) : base(serviceName)
                {
                    _type = "rcl_interfaces/srv/ListParameters";
                }

                public ListParameters(string serviceName, string serviceType = "rcl_interfaces/srv/ListParameters") : base(serviceName, serviceType) {}

            } // class ListParameters

            [System.Serializable]
            public class ListParameters_Request : ServiceArgs
            {
                public System.Collections.Generic.List<string>  prefixes;
                public System.UInt64 depth;

                // Constants:
                public const System.UInt64 DEPTH_RECURSIVE = 0;

                public ListParameters_Request()
                {
                    prefixes = new System.Collections.Generic.List<string>();
                    depth = 0;
                }

                public ListParameters_Request(System.Collections.Generic.List<string>  _prefixes, System.UInt64 _depth)
                {
                    prefixes = _prefixes;
                    depth = _depth;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/srv/ListParameters_Request";
                }

            } // class ListParameters_Request

            [System.Serializable]
            public class ListParameters_Response : ServiceResponse
            {
                public rcl_interfaces.msg.ListParametersResult result;


                public ListParameters_Response()
                {
                    result = new rcl_interfaces.msg.ListParametersResult();
                }

                public ListParameters_Response(rcl_interfaces.msg.ListParametersResult _result)
                {
                    result = _result;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/srv/ListParameters_Response";
                }

            } // class ListParameters_Response

        } // namespace srv
    } // namespace rcl_interfaces
} // namespace ROSBridgeLib
