// Generated by gencs from rcl_interfaces/srv/SetParametersAtomically.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rcl_interfaces {
        namespace srv {

            public class SetParametersAtomically : ROSBridgeServiceProvider<SetParametersAtomically_Request>
            {

                public SetParametersAtomically(string serviceName) : base(serviceName)
                {
                    _type = "rcl_interfaces/srv/SetParametersAtomically";
                }

                public SetParametersAtomically(string serviceName, string serviceType = "rcl_interfaces/srv/SetParametersAtomically") : base(serviceName, serviceType) {}

            } // class SetParametersAtomically

            [System.Serializable]
            public class SetParametersAtomically_Request : ServiceArgs
            {
                public System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  parameters;


                public SetParametersAtomically_Request()
                {
                    parameters = new System.Collections.Generic.List<rcl_interfaces.msg.Parameter>();
                }

                public SetParametersAtomically_Request(System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  _parameters)
                {
                    parameters = _parameters;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/srv/SetParametersAtomically_Request";
                }

            } // class SetParametersAtomically_Request

            [System.Serializable]
            public class SetParametersAtomically_Response : ServiceResponse
            {
                public rcl_interfaces.msg.SetParametersResult result;


                public SetParametersAtomically_Response()
                {
                    result = new rcl_interfaces.msg.SetParametersResult();
                }

                public SetParametersAtomically_Response(rcl_interfaces.msg.SetParametersResult _result)
                {
                    result = _result;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/srv/SetParametersAtomically_Response";
                }

            } // class SetParametersAtomically_Response

        } // namespace srv
    } // namespace rcl_interfaces
} // namespace ROSBridgeLib
