// Generated by gencs from rcl_interfaces/srv/SetParameters.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rcl_interfaces {
        namespace srv {

            public class SetParameters : ROSBridgeServiceProvider<SetParameters_Request>
            {

                public SetParameters(string serviceName) : base(serviceName)
                {
                    _type = "rcl_interfaces/srv/SetParameters";
                }

                public SetParameters(string serviceName, string serviceType = "rcl_interfaces/srv/SetParameters") : base(serviceName, serviceType) {}

            } // class SetParameters

            [System.Serializable]
            public class SetParameters_Request : ServiceArgs
            {
                public System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  parameters;


                public SetParameters_Request()
                {
                    parameters = new System.Collections.Generic.List<rcl_interfaces.msg.Parameter>();
                }

                public SetParameters_Request(System.Collections.Generic.List<rcl_interfaces.msg.Parameter>  _parameters)
                {
                    parameters = _parameters;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/srv/SetParameters_Request";
                }

            } // class SetParameters_Request

            [System.Serializable]
            public class SetParameters_Response : ServiceResponse
            {
                public System.Collections.Generic.List<rcl_interfaces.msg.SetParametersResult>  results;


                public SetParameters_Response()
                {
                    results = new System.Collections.Generic.List<rcl_interfaces.msg.SetParametersResult>();
                }

                public SetParameters_Response(System.Collections.Generic.List<rcl_interfaces.msg.SetParametersResult>  _results)
                {
                    results = _results;
                }

                new public static string GetMessageType()
                {
                    return "rcl_interfaces/srv/SetParameters_Response";
                }

            } // class SetParameters_Response

        } // namespace srv
    } // namespace rcl_interfaces
} // namespace ROSBridgeLib
