// Generated by gencs from tf2_msgs/msg/TF2Error.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace tf2_msgs {
        namespace msg {

            [System.Serializable]
            public class TF2Error : ROSMessage
            {
                public byte error;
                public string error_string;

                // Constants:
                public const byte NO_ERROR = 0;
                public const byte LOOKUP_ERROR = 1;
                public const byte CONNECTIVITY_ERROR = 2;
                public const byte EXTRAPOLATION_ERROR = 3;
                public const byte INVALID_ARGUMENT_ERROR = 4;
                public const byte TIMEOUT_ERROR = 5;
                public const byte TRANSFORM_ERROR = 6;

                public TF2Error()
                {
                    error = 0;
                    error_string = "";
                }

                public TF2Error(byte _error, string _error_string)
                {
                    error = _error;
                    error_string = _error_string;
                }

                new public static string GetMessageType()
                {
                    return "tf2_msgs/msg/TF2Error";
                }

            } // class TF2Error

        } // namespace msg
    } // namespace tf2_msgs

} // namespace ROSBridgeLib
