// Generated by gencs from tf2_msgs/msg/TFMessage.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace tf2_msgs {
        namespace msg {

            [System.Serializable]
            public class TFMessage : ROSMessage
            {
                public System.Collections.Generic.List<geometry_msgs.msg.TransformStamped>  transforms;


                public TFMessage()
                {
                    transforms = new System.Collections.Generic.List<geometry_msgs.msg.TransformStamped>();
                }

                public TFMessage(System.Collections.Generic.List<geometry_msgs.msg.TransformStamped>  _transforms)
                {
                    transforms = _transforms;
                }

                new public static string GetMessageType()
                {
                    return "tf2_msgs/msg/TFMessage";
                }

            } // class TFMessage

        } // namespace msg
    } // namespace tf2_msgs

} // namespace ROSBridgeLib
