// Generated by gencs from statistics_msgs/msg/MetricsMessage.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.builtin_interfaces.msg;
using ROSBridgeLib.statistics_msgs.msg;

namespace ROSBridgeLib {

    namespace statistics_msgs {
        namespace msg {

            [System.Serializable]
            public class MetricsMessage : ROSMessage
            {
                public string measurement_source_name;
                public string metrics_source;
                public string unit;
                public builtin_interfaces.msg.Time window_start;
                public builtin_interfaces.msg.Time window_stop;
                public System.Collections.Generic.List<statistics_msgs.msg.StatisticDataPoint>  statistics;


                public MetricsMessage()
                {
                    measurement_source_name = "";
                    metrics_source = "";
                    unit = "";
                    window_start = new builtin_interfaces.msg.Time();
                    window_stop = new builtin_interfaces.msg.Time();
                    statistics = new System.Collections.Generic.List<statistics_msgs.msg.StatisticDataPoint>();
                }

                public MetricsMessage(string _measurement_source_name, string _metrics_source, string _unit, builtin_interfaces.msg.Time _window_start, builtin_interfaces.msg.Time _window_stop, System.Collections.Generic.List<statistics_msgs.msg.StatisticDataPoint>  _statistics)
                {
                    measurement_source_name = _measurement_source_name;
                    metrics_source = _metrics_source;
                    unit = _unit;
                    window_start = _window_start;
                    window_stop = _window_stop;
                    statistics = _statistics;
                }

                new public static string GetMessageType()
                {
                    return "statistics_msgs/msg/MetricsMessage";
                }

            } // class MetricsMessage

        } // namespace msg
    } // namespace statistics_msgs

} // namespace ROSBridgeLib
