// Generated by gencs from statistics_msgs/msg/StatisticDataPoint.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace statistics_msgs {
        namespace msg {

            [System.Serializable]
            public class StatisticDataPoint : ROSMessage
            {
                public byte data_type;
                public double data;


                public StatisticDataPoint()
                {
                    data_type = 0;
                    data = 0.0f;
                }

                public StatisticDataPoint(byte _data_type, double _data)
                {
                    data_type = _data_type;
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "statistics_msgs/msg/StatisticDataPoint";
                }

            } // class StatisticDataPoint

        } // namespace msg
    } // namespace statistics_msgs

} // namespace ROSBridgeLib
