// Generated by gencs from statistics_msgs/msg/StatisticDataType.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace statistics_msgs {
        namespace msg {

            [System.Serializable]
            public class StatisticDataType : ROSMessage
            {
                public byte structure_needs_at_least_one_member;

                // Constants:
                public const byte STATISTICS_DATA_TYPE_UNINITIALIZED = 0;
                public const byte STATISTICS_DATA_TYPE_AVERAGE = 1;
                public const byte STATISTICS_DATA_TYPE_MINIMUM = 2;
                public const byte STATISTICS_DATA_TYPE_MAXIMUM = 3;
                public const byte STATISTICS_DATA_TYPE_STDDEV = 4;
                public const byte STATISTICS_DATA_TYPE_SAMPLE_COUNT = 5;

                public StatisticDataType()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public StatisticDataType(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "statistics_msgs/msg/StatisticDataType";
                }

            } // class StatisticDataType

        } // namespace msg
    } // namespace statistics_msgs

} // namespace ROSBridgeLib
