// Generated by gencs from nav_msgs/srv/GetPlan.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace nav_msgs {
        namespace srv {

            public class GetPlan : ROSBridgeServiceProvider<GetPlan_Request>
            {

                public GetPlan(string serviceName) : base(serviceName)
                {
                    _type = "nav_msgs/srv/GetPlan";
                }

                public GetPlan(string serviceName, string serviceType = "nav_msgs/srv/GetPlan") : base(serviceName, serviceType) {}

            } // class GetPlan

            [System.Serializable]
            public class GetPlan_Request : ServiceArgs
            {
                public geometry_msgs.msg.PoseStamped start;
                public geometry_msgs.msg.PoseStamped goal;
                public float tolerance;


                public GetPlan_Request()
                {
                    start = new geometry_msgs.msg.PoseStamped();
                    goal = new geometry_msgs.msg.PoseStamped();
                    tolerance = 0.0f;
                }

                public GetPlan_Request(geometry_msgs.msg.PoseStamped _start, geometry_msgs.msg.PoseStamped _goal, float _tolerance)
                {
                    start = _start;
                    goal = _goal;
                    tolerance = _tolerance;
                }

                new public static string GetMessageType()
                {
                    return "nav_msgs/srv/GetPlan_Request";
                }

            } // class GetPlan_Request

            [System.Serializable]
            public class GetPlan_Response : ServiceResponse
            {
                public nav_msgs.msg.Path plan;


                public GetPlan_Response()
                {
                    plan = new nav_msgs.msg.Path();
                }

                public GetPlan_Response(nav_msgs.msg.Path _plan)
                {
                    plan = _plan;
                }

                new public static string GetMessageType()
                {
                    return "nav_msgs/srv/GetPlan_Response";
                }

            } // class GetPlan_Response

        } // namespace srv
    } // namespace nav_msgs
} // namespace ROSBridgeLib
