// Generated by gencs from nav_msgs/srv/GetMap.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace nav_msgs {
        namespace srv {

            public class GetMap : ROSBridgeServiceProvider<GetMap_Request>
            {

                public GetMap(string serviceName) : base(serviceName)
                {
                    _type = "nav_msgs/srv/GetMap";
                }

                public GetMap(string serviceName, string serviceType = "nav_msgs/srv/GetMap") : base(serviceName, serviceType) {}

            } // class GetMap

            [System.Serializable]
            public class GetMap_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public GetMap_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public GetMap_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "nav_msgs/srv/GetMap_Request";
                }

            } // class GetMap_Request

            [System.Serializable]
            public class GetMap_Response : ServiceResponse
            {
                public nav_msgs.msg.OccupancyGrid map;


                public GetMap_Response()
                {
                    map = new nav_msgs.msg.OccupancyGrid();
                }

                public GetMap_Response(nav_msgs.msg.OccupancyGrid _map)
                {
                    map = _map;
                }

                new public static string GetMessageType()
                {
                    return "nav_msgs/srv/GetMap_Response";
                }

            } // class GetMap_Response

        } // namespace srv
    } // namespace nav_msgs
} // namespace ROSBridgeLib
