// Generated by gencs from nav_msgs/srv/LoadMap.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace nav_msgs {
        namespace srv {

            public class LoadMap : ROSBridgeServiceProvider<LoadMap_Request>
            {

                public LoadMap(string serviceName) : base(serviceName)
                {
                    _type = "nav_msgs/srv/LoadMap";
                }

                public LoadMap(string serviceName, string serviceType = "nav_msgs/srv/LoadMap") : base(serviceName, serviceType) {}

            } // class LoadMap

            [System.Serializable]
            public class LoadMap_Request : ServiceArgs
            {
                public string map_url;


                public LoadMap_Request()
                {
                    map_url = "";
                }

                public LoadMap_Request(string _map_url)
                {
                    map_url = _map_url;
                }

                new public static string GetMessageType()
                {
                    return "nav_msgs/srv/LoadMap_Request";
                }

            } // class LoadMap_Request

            [System.Serializable]
            public class LoadMap_Response : ServiceResponse
            {
                public nav_msgs.msg.OccupancyGrid map;
                public byte result;

                // Constants:
                public const byte RESULT_SUCCESS = 0;
                public const byte RESULT_MAP_DOES_NOT_EXIST = 1;
                public const byte RESULT_INVALID_MAP_DATA = 2;
                public const byte RESULT_INVALID_MAP_METADATA = 3;
                public const byte RESULT_UNDEFINED_FAILURE = 255;

                public LoadMap_Response()
                {
                    map = new nav_msgs.msg.OccupancyGrid();
                    result = 0;
                }

                public LoadMap_Response(nav_msgs.msg.OccupancyGrid _map, byte _result)
                {
                    map = _map;
                    result = _result;
                }

                new public static string GetMessageType()
                {
                    return "nav_msgs/srv/LoadMap_Response";
                }

            } // class LoadMap_Response

        } // namespace srv
    } // namespace nav_msgs
} // namespace ROSBridgeLib
