// Generated by gencs from nav_msgs/srv/SetMap.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace nav_msgs {
        namespace srv {

            public class SetMap : ROSBridgeServiceProvider<SetMap_Request>
            {

                public SetMap(string serviceName) : base(serviceName)
                {
                    _type = "nav_msgs/srv/SetMap";
                }

                public SetMap(string serviceName, string serviceType = "nav_msgs/srv/SetMap") : base(serviceName, serviceType) {}

            } // class SetMap

            [System.Serializable]
            public class SetMap_Request : ServiceArgs
            {
                public nav_msgs.msg.OccupancyGrid map;
                public geometry_msgs.msg.PoseWithCovarianceStamped initial_pose;


                public SetMap_Request()
                {
                    map = new nav_msgs.msg.OccupancyGrid();
                    initial_pose = new geometry_msgs.msg.PoseWithCovarianceStamped();
                }

                public SetMap_Request(nav_msgs.msg.OccupancyGrid _map, geometry_msgs.msg.PoseWithCovarianceStamped _initial_pose)
                {
                    map = _map;
                    initial_pose = _initial_pose;
                }

                new public static string GetMessageType()
                {
                    return "nav_msgs/srv/SetMap_Request";
                }

            } // class SetMap_Request

            [System.Serializable]
            public class SetMap_Response : ServiceResponse
            {
                public bool success;


                public SetMap_Response()
                {
                    success = false;
                }

                public SetMap_Response(bool _success)
                {
                    success = _success;
                }

                new public static string GetMessageType()
                {
                    return "nav_msgs/srv/SetMap_Response";
                }

            } // class SetMap_Response

        } // namespace srv
    } // namespace nav_msgs
} // namespace ROSBridgeLib
