// Generated by gencs from rosapi_msgs/msg/TypeDef.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace rosapi_msgs {
        namespace msg {

            [System.Serializable]
            public class TypeDef : ROSMessage
            {
                public string type;
                public System.Collections.Generic.List<string>  fieldnames;
                public System.Collections.Generic.List<string>  fieldtypes;
                public System.Collections.Generic.List<System.Int32>  fieldarraylen;
                public System.Collections.Generic.List<string>  examples;
                public System.Collections.Generic.List<string>  constnames;
                public System.Collections.Generic.List<string>  constvalues;


                public TypeDef()
                {
                    type = "";
                    fieldnames = new System.Collections.Generic.List<string>();
                    fieldtypes = new System.Collections.Generic.List<string>();
                    fieldarraylen = new System.Collections.Generic.List<System.Int32>();
                    examples = new System.Collections.Generic.List<string>();
                    constnames = new System.Collections.Generic.List<string>();
                    constvalues = new System.Collections.Generic.List<string>();
                }

                public TypeDef(string _type, System.Collections.Generic.List<string>  _fieldnames, System.Collections.Generic.List<string>  _fieldtypes, System.Collections.Generic.List<System.Int32>  _fieldarraylen, System.Collections.Generic.List<string>  _examples, System.Collections.Generic.List<string>  _constnames, System.Collections.Generic.List<string>  _constvalues)
                {
                    type = _type;
                    fieldnames = _fieldnames;
                    fieldtypes = _fieldtypes;
                    fieldarraylen = _fieldarraylen;
                    examples = _examples;
                    constnames = _constnames;
                    constvalues = _constvalues;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/msg/TypeDef";
                }

            } // class TypeDef

        } // namespace msg
    } // namespace rosapi_msgs

} // namespace ROSBridgeLib
