// Generated by gencs from lifecycle_msgs/srv/ChangeState.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace lifecycle_msgs {
        namespace srv {

            public class ChangeState : ROSBridgeServiceProvider<ChangeState_Request>
            {

                public ChangeState(string serviceName) : base(serviceName)
                {
                    _type = "lifecycle_msgs/srv/ChangeState";
                }

                public ChangeState(string serviceName, string serviceType = "lifecycle_msgs/srv/ChangeState") : base(serviceName, serviceType) {}

            } // class ChangeState

            [System.Serializable]
            public class ChangeState_Request : ServiceArgs
            {
                public lifecycle_msgs.msg.Transition transition;


                public ChangeState_Request()
                {
                    transition = new lifecycle_msgs.msg.Transition();
                }

                public ChangeState_Request(lifecycle_msgs.msg.Transition _transition)
                {
                    transition = _transition;
                }

                new public static string GetMessageType()
                {
                    return "lifecycle_msgs/srv/ChangeState_Request";
                }

            } // class ChangeState_Request

            [System.Serializable]
            public class ChangeState_Response : ServiceResponse
            {
                public bool success;


                public ChangeState_Response()
                {
                    success = false;
                }

                public ChangeState_Response(bool _success)
                {
                    success = _success;
                }

                new public static string GetMessageType()
                {
                    return "lifecycle_msgs/srv/ChangeState_Response";
                }

            } // class ChangeState_Response

        } // namespace srv
    } // namespace lifecycle_msgs
} // namespace ROSBridgeLib
