// Generated by gencs from lifecycle_msgs/srv/GetAvailableStates.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace lifecycle_msgs {
        namespace srv {

            public class GetAvailableStates : ROSBridgeServiceProvider<GetAvailableStates_Request>
            {

                public GetAvailableStates(string serviceName) : base(serviceName)
                {
                    _type = "lifecycle_msgs/srv/GetAvailableStates";
                }

                public GetAvailableStates(string serviceName, string serviceType = "lifecycle_msgs/srv/GetAvailableStates") : base(serviceName, serviceType) {}

            } // class GetAvailableStates

            [System.Serializable]
            public class GetAvailableStates_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public GetAvailableStates_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public GetAvailableStates_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "lifecycle_msgs/srv/GetAvailableStates_Request";
                }

            } // class GetAvailableStates_Request

            [System.Serializable]
            public class GetAvailableStates_Response : ServiceResponse
            {
                public System.Collections.Generic.List<lifecycle_msgs.msg.State>  available_states;


                public GetAvailableStates_Response()
                {
                    available_states = new System.Collections.Generic.List<lifecycle_msgs.msg.State>();
                }

                public GetAvailableStates_Response(System.Collections.Generic.List<lifecycle_msgs.msg.State>  _available_states)
                {
                    available_states = _available_states;
                }

                new public static string GetMessageType()
                {
                    return "lifecycle_msgs/srv/GetAvailableStates_Response";
                }

            } // class GetAvailableStates_Response

        } // namespace srv
    } // namespace lifecycle_msgs
} // namespace ROSBridgeLib
