// Generated by gencs from lifecycle_msgs/srv/GetAvailableTransitions.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace lifecycle_msgs {
        namespace srv {

            public class GetAvailableTransitions : ROSBridgeServiceProvider<GetAvailableTransitions_Request>
            {

                public GetAvailableTransitions(string serviceName) : base(serviceName)
                {
                    _type = "lifecycle_msgs/srv/GetAvailableTransitions";
                }

                public GetAvailableTransitions(string serviceName, string serviceType = "lifecycle_msgs/srv/GetAvailableTransitions") : base(serviceName, serviceType) {}

            } // class GetAvailableTransitions

            [System.Serializable]
            public class GetAvailableTransitions_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public GetAvailableTransitions_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public GetAvailableTransitions_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "lifecycle_msgs/srv/GetAvailableTransitions_Request";
                }

            } // class GetAvailableTransitions_Request

            [System.Serializable]
            public class GetAvailableTransitions_Response : ServiceResponse
            {
                public System.Collections.Generic.List<lifecycle_msgs.msg.TransitionDescription>  available_transitions;


                public GetAvailableTransitions_Response()
                {
                    available_transitions = new System.Collections.Generic.List<lifecycle_msgs.msg.TransitionDescription>();
                }

                public GetAvailableTransitions_Response(System.Collections.Generic.List<lifecycle_msgs.msg.TransitionDescription>  _available_transitions)
                {
                    available_transitions = _available_transitions;
                }

                new public static string GetMessageType()
                {
                    return "lifecycle_msgs/srv/GetAvailableTransitions_Response";
                }

            } // class GetAvailableTransitions_Response

        } // namespace srv
    } // namespace lifecycle_msgs
} // namespace ROSBridgeLib
