// Generated by gencs from lifecycle_msgs/srv/GetState.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace lifecycle_msgs {
        namespace srv {

            public class GetState : ROSBridgeServiceProvider<GetState_Request>
            {

                public GetState(string serviceName) : base(serviceName)
                {
                    _type = "lifecycle_msgs/srv/GetState";
                }

                public GetState(string serviceName, string serviceType = "lifecycle_msgs/srv/GetState") : base(serviceName, serviceType) {}

            } // class GetState

            [System.Serializable]
            public class GetState_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public GetState_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public GetState_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "lifecycle_msgs/srv/GetState_Request";
                }

            } // class GetState_Request

            [System.Serializable]
            public class GetState_Response : ServiceResponse
            {
                public lifecycle_msgs.msg.State current_state;


                public GetState_Response()
                {
                    current_state = new lifecycle_msgs.msg.State();
                }

                public GetState_Response(lifecycle_msgs.msg.State _current_state)
                {
                    current_state = _current_state;
                }

                new public static string GetMessageType()
                {
                    return "lifecycle_msgs/srv/GetState_Response";
                }

            } // class GetState_Response

        } // namespace srv
    } // namespace lifecycle_msgs
} // namespace ROSBridgeLib
