// Generated by gencs from std_msgs/Bool.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class Bool : ROSMessage
    {
      public bool data;


      public Bool()
      {
        data = false;

      }

      public Bool(bool _data)
      {
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/Bool";
      }

      new public static string GetMD5Hash()
      {
        return "8b94c1b53db61fb6aed406028ad6332a";
      }

    } // class Bool

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
