// Generated by gencs from std_msgs/ByteMultiArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class ByteMultiArray : ROSMessage
    {
      public std_msgs.MultiArrayLayout layout;
      public System.Collections.Generic.List<sbyte>  data;


      public ByteMultiArray()
      {
        layout = new std_msgs.MultiArrayLayout();
        data = new System.Collections.Generic.List<sbyte>();

      }

      public ByteMultiArray(std_msgs.MultiArrayLayout _layout, System.Collections.Generic.List<sbyte>  _data)
      {
        layout = _layout;
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/ByteMultiArray";
      }

      new public static string GetMD5Hash()
      {
        return "70ea476cbcfd65ac2f68f3cda1e891fe";
      }

    } // class ByteMultiArray

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
