// Generated by gencs from std_msgs/Char.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class Char : ROSMessage
    {
      public byte data;


      public Char()
      {
        data = 0;

      }

      public Char(byte _data)
      {
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/Char";
      }

      new public static string GetMD5Hash()
      {
        return "1bf77f25acecdedba0e224b162199717";
      }

    } // class Char

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
