// Generated by gencs from std_msgs/ColorRGBA.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class ColorRGBA : ROSMessage
    {
      public float r;
      public float g;
      public float b;
      public float a;


      public ColorRGBA()
      {
        r = 0.0f;
        g = 0.0f;
        b = 0.0f;
        a = 0.0f;

      }

      public ColorRGBA(float _r, float _g, float _b, float _a)
      {
        r = _r;
        g = _g;
        b = _b;
        a = _a;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/ColorRGBA";
      }

      new public static string GetMD5Hash()
      {
        return "a29a96539573343b1310c73607334b00";
      }

    } // class ColorRGBA

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
