// Generated by gencs from std_msgs/Duration.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class Duration : ROSMessage
    {
      public ROSBridgeLib.msg_helpers.Duration data;


      public Duration()
      {
        data = new ROSBridgeLib.msg_helpers.Duration();

      }

      public Duration(ROSBridgeLib.msg_helpers.Duration _data)
      {
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/Duration";
      }

      new public static string GetMD5Hash()
      {
        return "3e286caf4241d664e55f3ad380e2ae46";
      }

    } // class Duration

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
