// Generated by gencs from std_msgs/Empty.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class Empty : ROSMessage
    {


      public Empty()
      {

      }


      new public static string GetMessageType()
      {
        return "std_msgs/Empty";
      }

      new public static string GetMD5Hash()
      {
        return "d41d8cd98f00b204e9800998ecf8427e";
      }

    } // class Empty

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
