// Generated by gencs from std_msgs/Float32MultiArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class Float32MultiArray : ROSMessage
    {
      public std_msgs.MultiArrayLayout layout;
      public System.Collections.Generic.List<float>  data;


      public Float32MultiArray()
      {
        layout = new std_msgs.MultiArrayLayout();
        data = new System.Collections.Generic.List<float>();

      }

      public Float32MultiArray(std_msgs.MultiArrayLayout _layout, System.Collections.Generic.List<float>  _data)
      {
        layout = _layout;
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/Float32MultiArray";
      }

      new public static string GetMD5Hash()
      {
        return "6a40e0ffa6a17a503ac3f8616991b1f6";
      }

    } // class Float32MultiArray

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
