// Generated by gencs from std_msgs/Float64MultiArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class Float64MultiArray : ROSMessage
    {
      public std_msgs.MultiArrayLayout layout;
      public System.Collections.Generic.List<double>  data;


      public Float64MultiArray()
      {
        layout = new std_msgs.MultiArrayLayout();
        data = new System.Collections.Generic.List<double>();

      }

      public Float64MultiArray(std_msgs.MultiArrayLayout _layout, System.Collections.Generic.List<double>  _data)
      {
        layout = _layout;
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/Float64MultiArray";
      }

      new public static string GetMD5Hash()
      {
        return "4b7d974086d4060e7db4613a7e6c3ba4";
      }

    } // class Float64MultiArray

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
