// Generated by gencs from std_msgs/Float64.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class Float64 : ROSMessage
    {
      public double data;


      public Float64()
      {
        data = 0.0;

      }

      public Float64(double _data)
      {
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/Float64";
      }

      new public static string GetMD5Hash()
      {
        return "fdb28210bfa9d7c91146260178d9a584";
      }

    } // class Float64

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
