// Generated by gencs from std_msgs/Header.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class Header : ROSMessage
    {
      public System.UInt32 seq;
      public ROSBridgeLib.msg_helpers.Time stamp;
      public string frame_id;


      public Header()
      {
        seq = 0;
        stamp = new ROSBridgeLib.msg_helpers.Time();
        frame_id = "";

      }

      public Header(System.UInt32 _seq, ROSBridgeLib.msg_helpers.Time _stamp, string _frame_id)
      {
        seq = _seq;
        stamp = _stamp;
        frame_id = _frame_id;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/Header";
      }

      new public static string GetMD5Hash()
      {
        return "2176decaecbce78abc3b96ef049fabed";
      }

    } // class Header

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
