// Generated by gencs from std_msgs/MultiArrayDimension.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class MultiArrayDimension : ROSMessage
    {
      public string label;
      public System.UInt32 size;
      public System.UInt32 stride;


      public MultiArrayDimension()
      {
        label = "";
        size = 0;
        stride = 0;

      }

      public MultiArrayDimension(string _label, System.UInt32 _size, System.UInt32 _stride)
      {
        label = _label;
        size = _size;
        stride = _stride;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/MultiArrayDimension";
      }

      new public static string GetMD5Hash()
      {
        return "4cd0c83a8683deae40ecdac60e53bfa8";
      }

    } // class MultiArrayDimension

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
