// Generated by gencs from std_msgs/String.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class String : ROSMessage
    {
      public string data;


      public String()
      {
        data = "";

      }

      public String(string _data)
      {
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/String";
      }

      new public static string GetMD5Hash()
      {
        return "992ce8a1687cec8c8bd883ec73ca41d1";
      }

    } // class String

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
