// Generated by gencs from std_msgs/Time.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class Time : ROSMessage
    {
      public ROSBridgeLib.msg_helpers.Time data;


      public Time()
      {
        data = new ROSBridgeLib.msg_helpers.Time();

      }

      public Time(ROSBridgeLib.msg_helpers.Time _data)
      {
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/Time";
      }

      new public static string GetMD5Hash()
      {
        return "cd7166c74c552c311fbcc2fe5a7bc289";
      }

    } // class Time

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
