// Generated by gencs from std_msgs/UInt32.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class UInt32 : ROSMessage
    {
      public System.UInt32 data;


      public UInt32()
      {
        data = 0;

      }

      public UInt32(System.UInt32 _data)
      {
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/UInt32";
      }

      new public static string GetMD5Hash()
      {
        return "304a39449588c7f8ce2df6e8001c5fce";
      }

    } // class UInt32

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
