// Generated by gencs from std_msgs/UInt64.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class UInt64 : ROSMessage
    {
      public System.UInt64 data;


      public UInt64()
      {
        data = 0;

      }

      public UInt64(System.UInt64 _data)
      {
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/UInt64";
      }

      new public static string GetMD5Hash()
      {
        return "1b2a79973e8bf53d7b53acb71299cb57";
      }

    } // class UInt64

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
