// Generated by gencs from std_msgs/UInt8MultiArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_msgs {

    [System.Serializable]
    public class UInt8MultiArray : ROSMessage
    {
      public std_msgs.MultiArrayLayout layout;
      public System.Collections.Generic.List<byte>  data;


      public UInt8MultiArray()
      {
        layout = new std_msgs.MultiArrayLayout();
        data = new System.Collections.Generic.List<byte>();

      }

      public UInt8MultiArray(std_msgs.MultiArrayLayout _layout, System.Collections.Generic.List<byte>  _data)
      {
        layout = _layout;
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_msgs/UInt8MultiArray";
      }

      new public static string GetMD5Hash()
      {
        return "82373f1612381bb6ee473b5cd6f5d89c";
      }

    } // class UInt8MultiArray

  } // namespace std_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
