// Generated by gencs from std_msgs/msg/Bool.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class Bool : ROSMessage
            {
                public bool data;


                public Bool()
                {
                    data = false;
                }

                public Bool(bool _data)
                {
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/Bool";
                }

            } // class Bool

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
