// Generated by gencs from std_msgs/msg/Byte.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class Byte : ROSMessage
            {
                public sbyte data;


                public Byte()
                {
                    data = 0;
                }

                public Byte(sbyte _data)
                {
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/Byte";
                }

            } // class Byte

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
