// Generated by gencs from std_msgs/msg/Char.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class Char : ROSMessage
            {
                public byte data;


                public Char()
                {
                    data = 0;
                }

                public Char(byte _data)
                {
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/Char";
                }

            } // class Char

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
