// Generated by gencs from std_msgs/msg/Float64.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class Float64 : ROSMessage
            {
                public double data;


                public Float64()
                {
                    data = 0.0f;
                }

                public Float64(double _data)
                {
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/Float64";
                }

            } // class Float64

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
