// Generated by gencs from std_msgs/msg/Header.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.builtin_interfaces.msg;

namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class Header : ROSMessage
            {
                public builtin_interfaces.msg.Time stamp;
                public string frame_id;


                public Header()
                {
                    stamp = new builtin_interfaces.msg.Time();
                    frame_id = "";
                }

                public Header(builtin_interfaces.msg.Time _stamp, string _frame_id)
                {
                    stamp = _stamp;
                    frame_id = _frame_id;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/Header";
                }

            } // class Header

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
