// Generated by gencs from std_msgs/msg/Int64MultiArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;

namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class Int64MultiArray : ROSMessage
            {
                public std_msgs.msg.MultiArrayLayout layout;
                public System.Collections.Generic.List<System.Int64>  data;


                public Int64MultiArray()
                {
                    layout = new std_msgs.msg.MultiArrayLayout();
                    data = new System.Collections.Generic.List<System.Int64>();
                }

                public Int64MultiArray(std_msgs.msg.MultiArrayLayout _layout, System.Collections.Generic.List<System.Int64>  _data)
                {
                    layout = _layout;
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/Int64MultiArray";
                }

            } // class Int64MultiArray

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
