// Generated by gencs from std_msgs/msg/Int8.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class Int8 : ROSMessage
            {
                public sbyte data;


                public Int8()
                {
                    data = 0;
                }

                public Int8(sbyte _data)
                {
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/Int8";
                }

            } // class Int8

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
