// Generated by gencs from std_msgs/msg/MultiArrayLayout.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;

namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class MultiArrayLayout : ROSMessage
            {
                public System.Collections.Generic.List<std_msgs.msg.MultiArrayDimension>  dim;
                public System.UInt32 data_offset;


                public MultiArrayLayout()
                {
                    dim = new System.Collections.Generic.List<std_msgs.msg.MultiArrayDimension>();
                    data_offset = 0;
                }

                public MultiArrayLayout(System.Collections.Generic.List<std_msgs.msg.MultiArrayDimension>  _dim, System.UInt32 _data_offset)
                {
                    dim = _dim;
                    data_offset = _data_offset;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/MultiArrayLayout";
                }

            } // class MultiArrayLayout

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
