// Generated by gencs from std_msgs/msg/String.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class String : ROSMessage
            {
                public string data;


                public String()
                {
                    data = "";
                }

                public String(string _data)
                {
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/String";
                }

            } // class String

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
