// Generated by gencs from std_msgs/msg/UInt32.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class UInt32 : ROSMessage
            {
                public System.UInt32 data;


                public UInt32()
                {
                    data = 0;
                }

                public UInt32(System.UInt32 _data)
                {
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/UInt32";
                }

            } // class UInt32

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
