// Generated by gencs from std_msgs/msg/UInt8.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class UInt8 : ROSMessage
            {
                public byte data;


                public UInt8()
                {
                    data = 0;
                }

                public UInt8(byte _data)
                {
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/UInt8";
                }

            } // class UInt8

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
