// Generated by gencs from std_msgs/msg/UInt16.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class UInt16 : ROSMessage
            {
                public System.UInt16 data;


                public UInt16()
                {
                    data = 0;
                }

                public UInt16(System.UInt16 _data)
                {
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/UInt16";
                }

            } // class UInt16

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
