// Generated by gencs from std_msgs/msg/UInt16MultiArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;

namespace ROSBridgeLib {

    namespace std_msgs {
        namespace msg {

            [System.Serializable]
            public class UInt16MultiArray : ROSMessage
            {
                public std_msgs.msg.MultiArrayLayout layout;
                public System.Collections.Generic.List<System.UInt16>  data;


                public UInt16MultiArray()
                {
                    layout = new std_msgs.msg.MultiArrayLayout();
                    data = new System.Collections.Generic.List<System.UInt16>();
                }

                public UInt16MultiArray(std_msgs.msg.MultiArrayLayout _layout, System.Collections.Generic.List<System.UInt16>  _data)
                {
                    layout = _layout;
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "std_msgs/msg/UInt16MultiArray";
                }

            } // class UInt16MultiArray

        } // namespace msg
    } // namespace std_msgs

} // namespace ROSBridgeLib
