// Generated by gencs from rosgraph_msgs/msg/Clock.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.builtin_interfaces.msg;

namespace ROSBridgeLib {

    namespace rosgraph_msgs {
        namespace msg {

            [System.Serializable]
            public class Clock : ROSMessage
            {
                public builtin_interfaces.msg.Time clock;


                public Clock()
                {
                    clock = new builtin_interfaces.msg.Time();
                }

                public Clock(builtin_interfaces.msg.Time _clock)
                {
                    clock = _clock;
                }

                new public static string GetMessageType()
                {
                    return "rosgraph_msgs/msg/Clock";
                }

            } // class Clock

        } // namespace msg
    } // namespace rosgraph_msgs

} // namespace ROSBridgeLib
