// Generated by gencs from sensor_msgs/srv/SetCameraInfo.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace sensor_msgs {
        namespace srv {

            public class SetCameraInfo : ROSBridgeServiceProvider<SetCameraInfo_Request>
            {

                public SetCameraInfo(string serviceName) : base(serviceName)
                {
                    _type = "sensor_msgs/srv/SetCameraInfo";
                }

                public SetCameraInfo(string serviceName, string serviceType = "sensor_msgs/srv/SetCameraInfo") : base(serviceName, serviceType) {}

            } // class SetCameraInfo

            [System.Serializable]
            public class SetCameraInfo_Request : ServiceArgs
            {
                public sensor_msgs.msg.CameraInfo camera_info;


                public SetCameraInfo_Request()
                {
                    camera_info = new sensor_msgs.msg.CameraInfo();
                }

                public SetCameraInfo_Request(sensor_msgs.msg.CameraInfo _camera_info)
                {
                    camera_info = _camera_info;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/srv/SetCameraInfo_Request";
                }

            } // class SetCameraInfo_Request

            [System.Serializable]
            public class SetCameraInfo_Response : ServiceResponse
            {
                public bool success;
                public string status_message;


                public SetCameraInfo_Response()
                {
                    success = false;
                    status_message = "";
                }

                public SetCameraInfo_Response(bool _success, string _status_message)
                {
                    success = _success;
                    status_message = _status_message;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/srv/SetCameraInfo_Response";
                }

            } // class SetCameraInfo_Response

        } // namespace srv
    } // namespace sensor_msgs
} // namespace ROSBridgeLib
