// Generated by gencs from visualization_msgs/msg/ImageMarker.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;
using ROSBridgeLib.builtin_interfaces.msg;

namespace ROSBridgeLib {

    namespace visualization_msgs {
        namespace msg {

            [System.Serializable]
            public class ImageMarker : ROSMessage
            {
                public std_msgs.msg.Header header;
                public string ns;
                public System.Int32 id;
                public System.Int32 type;
                public System.Int32 action;
                public UnityEngine.Vector3 position;
                public float scale;
                public std_msgs.msg.ColorRGBA outline_color;
                public byte filled;
                public std_msgs.msg.ColorRGBA fill_color;
                public builtin_interfaces.msg.Duration lifetime;
                public System.Collections.Generic.List<UnityEngine.Vector3>  points;
                public System.Collections.Generic.List<std_msgs.msg.ColorRGBA>  outline_colors;

                // Constants:
                public const System.Int32 CIRCLE = 0;
                public const System.Int32 LINE_STRIP = 1;
                public const System.Int32 LINE_LIST = 2;
                public const System.Int32 POLYGON = 3;
                public const System.Int32 POINTS = 4;
                public const System.Int32 ADD = 0;
                public const System.Int32 REMOVE = 1;

                public ImageMarker()
                {
                    header = new std_msgs.msg.Header();
                    ns = "";
                    id = 0;
                    type = 0;
                    action = 0;
                    position = new UnityEngine.Vector3();
                    scale = 0.0f;
                    outline_color = new std_msgs.msg.ColorRGBA();
                    filled = 0;
                    fill_color = new std_msgs.msg.ColorRGBA();
                    lifetime = new builtin_interfaces.msg.Duration();
                    points = new System.Collections.Generic.List<UnityEngine.Vector3>();
                    outline_colors = new System.Collections.Generic.List<std_msgs.msg.ColorRGBA>();
                }

                public ImageMarker(std_msgs.msg.Header _header, string _ns, System.Int32 _id, System.Int32 _type, System.Int32 _action, UnityEngine.Vector3 _position, float _scale, std_msgs.msg.ColorRGBA _outline_color, byte _filled, std_msgs.msg.ColorRGBA _fill_color, builtin_interfaces.msg.Duration _lifetime, System.Collections.Generic.List<UnityEngine.Vector3>  _points, System.Collections.Generic.List<std_msgs.msg.ColorRGBA>  _outline_colors)
                {
                    header = _header;
                    ns = _ns;
                    id = _id;
                    type = _type;
                    action = _action;
                    position = _position;
                    scale = _scale;
                    outline_color = _outline_color;
                    filled = _filled;
                    fill_color = _fill_color;
                    lifetime = _lifetime;
                    points = _points;
                    outline_colors = _outline_colors;
                }

                new public static string GetMessageType()
                {
                    return "visualization_msgs/msg/ImageMarker";
                }

            } // class ImageMarker

        } // namespace msg
    } // namespace visualization_msgs

} // namespace ROSBridgeLib
