// Generated by gencs from visualization_msgs/msg/InteractiveMarkerControl.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.geometry_msgs.msg;
using ROSBridgeLib.visualization_msgs.msg;

namespace ROSBridgeLib {

    namespace visualization_msgs {
        namespace msg {

            [System.Serializable]
            public class InteractiveMarkerControl : ROSMessage
            {
                public string name;
                public UnityEngine.Quaternion orientation;
                public byte orientation_mode;
                public byte interaction_mode;
                public bool always_visible;
                public System.Collections.Generic.List<visualization_msgs.msg.Marker>  markers;
                public bool independent_marker_orientation;
                public string description;

                // Constants:
                public const byte INHERIT = 0;
                public const byte FIXED = 1;
                public const byte VIEW_FACING = 2;
                public const byte NONE = 0;
                public const byte MENU = 1;
                public const byte BUTTON = 2;
                public const byte MOVE_AXIS = 3;
                public const byte MOVE_PLANE = 4;
                public const byte ROTATE_AXIS = 5;
                public const byte MOVE_ROTATE = 6;
                public const byte MOVE_3D = 7;
                public const byte ROTATE_3D = 8;
                public const byte MOVE_ROTATE_3D = 9;

                public InteractiveMarkerControl()
                {
                    name = "";
                    orientation = new UnityEngine.Quaternion();
                    orientation_mode = 0;
                    interaction_mode = 0;
                    always_visible = false;
                    markers = new System.Collections.Generic.List<visualization_msgs.msg.Marker>();
                    independent_marker_orientation = false;
                    description = "";
                }

                public InteractiveMarkerControl(string _name, UnityEngine.Quaternion _orientation, byte _orientation_mode, byte _interaction_mode, bool _always_visible, System.Collections.Generic.List<visualization_msgs.msg.Marker>  _markers, bool _independent_marker_orientation, string _description)
                {
                    name = _name;
                    orientation = _orientation;
                    orientation_mode = _orientation_mode;
                    interaction_mode = _interaction_mode;
                    always_visible = _always_visible;
                    markers = _markers;
                    independent_marker_orientation = _independent_marker_orientation;
                    description = _description;
                }

                new public static string GetMessageType()
                {
                    return "visualization_msgs/msg/InteractiveMarkerControl";
                }

            } // class InteractiveMarkerControl

        } // namespace msg
    } // namespace visualization_msgs

} // namespace ROSBridgeLib
