// Generated by gencs from visualization_msgs/msg/InteractiveMarkerInit.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.visualization_msgs.msg;

namespace ROSBridgeLib {

    namespace visualization_msgs {
        namespace msg {

            [System.Serializable]
            public class InteractiveMarkerInit : ROSMessage
            {
                public string server_id;
                public System.UInt64 seq_num;
                public System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarker>  markers;


                public InteractiveMarkerInit()
                {
                    server_id = "";
                    seq_num = 0;
                    markers = new System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarker>();
                }

                public InteractiveMarkerInit(string _server_id, System.UInt64 _seq_num, System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarker>  _markers)
                {
                    server_id = _server_id;
                    seq_num = _seq_num;
                    markers = _markers;
                }

                new public static string GetMessageType()
                {
                    return "visualization_msgs/msg/InteractiveMarkerInit";
                }

            } // class InteractiveMarkerInit

        } // namespace msg
    } // namespace visualization_msgs

} // namespace ROSBridgeLib
