// Generated by gencs from visualization_msgs/msg/InteractiveMarker.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;
using ROSBridgeLib.visualization_msgs.msg;

namespace ROSBridgeLib {

    namespace visualization_msgs {
        namespace msg {

            [System.Serializable]
            public class InteractiveMarker : ROSMessage
            {
                public std_msgs.msg.Header header;
                public geometry_msgs.msg.Pose pose;
                public string name;
                public string description;
                public float scale;
                public System.Collections.Generic.List<visualization_msgs.msg.MenuEntry>  menu_entries;
                public System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarkerControl>  controls;


                public InteractiveMarker()
                {
                    header = new std_msgs.msg.Header();
                    pose = new geometry_msgs.msg.Pose();
                    name = "";
                    description = "";
                    scale = 0.0f;
                    menu_entries = new System.Collections.Generic.List<visualization_msgs.msg.MenuEntry>();
                    controls = new System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarkerControl>();
                }

                public InteractiveMarker(std_msgs.msg.Header _header, geometry_msgs.msg.Pose _pose, string _name, string _description, float _scale, System.Collections.Generic.List<visualization_msgs.msg.MenuEntry>  _menu_entries, System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarkerControl>  _controls)
                {
                    header = _header;
                    pose = _pose;
                    name = _name;
                    description = _description;
                    scale = _scale;
                    menu_entries = _menu_entries;
                    controls = _controls;
                }

                new public static string GetMessageType()
                {
                    return "visualization_msgs/msg/InteractiveMarker";
                }

            } // class InteractiveMarker

        } // namespace msg
    } // namespace visualization_msgs

} // namespace ROSBridgeLib
