// Generated by gencs from visualization_msgs/msg/InteractiveMarkerUpdate.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.visualization_msgs.msg;

namespace ROSBridgeLib {

    namespace visualization_msgs {
        namespace msg {

            [System.Serializable]
            public class InteractiveMarkerUpdate : ROSMessage
            {
                public string server_id;
                public System.UInt64 seq_num;
                public byte type;
                public System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarker>  markers;
                public System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarkerPose>  poses;
                public System.Collections.Generic.List<string>  erases;

                // Constants:
                public const byte KEEP_ALIVE = 0;
                public const byte UPDATE = 1;

                public InteractiveMarkerUpdate()
                {
                    server_id = "";
                    seq_num = 0;
                    type = 0;
                    markers = new System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarker>();
                    poses = new System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarkerPose>();
                    erases = new System.Collections.Generic.List<string>();
                }

                public InteractiveMarkerUpdate(string _server_id, System.UInt64 _seq_num, byte _type, System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarker>  _markers, System.Collections.Generic.List<visualization_msgs.msg.InteractiveMarkerPose>  _poses, System.Collections.Generic.List<string>  _erases)
                {
                    server_id = _server_id;
                    seq_num = _seq_num;
                    type = _type;
                    markers = _markers;
                    poses = _poses;
                    erases = _erases;
                }

                new public static string GetMessageType()
                {
                    return "visualization_msgs/msg/InteractiveMarkerUpdate";
                }

            } // class InteractiveMarkerUpdate

        } // namespace msg
    } // namespace visualization_msgs

} // namespace ROSBridgeLib
