// Generated by gencs from visualization_msgs/msg/Marker.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;
using ROSBridgeLib.builtin_interfaces.msg;

namespace ROSBridgeLib {

    namespace visualization_msgs {
        namespace msg {

            [System.Serializable]
            public class Marker : ROSMessage
            {
                public std_msgs.msg.Header header;
                public string ns;
                public System.Int32 id;
                public System.Int32 type;
                public System.Int32 action;
                public geometry_msgs.msg.Pose pose;
                public UnityEngine.Vector3 scale;
                public std_msgs.msg.ColorRGBA color;
                public builtin_interfaces.msg.Duration lifetime;
                public bool frame_locked;
                public System.Collections.Generic.List<UnityEngine.Vector3>  points;
                public System.Collections.Generic.List<std_msgs.msg.ColorRGBA>  colors;
                public string text;
                public string mesh_resource;
                public bool mesh_use_embedded_materials;

                // Constants:
                public const System.Int32 ARROW = 0;
                public const System.Int32 CUBE = 1;
                public const System.Int32 SPHERE = 2;
                public const System.Int32 CYLINDER = 3;
                public const System.Int32 LINE_STRIP = 4;
                public const System.Int32 LINE_LIST = 5;
                public const System.Int32 CUBE_LIST = 6;
                public const System.Int32 SPHERE_LIST = 7;
                public const System.Int32 POINTS = 8;
                public const System.Int32 TEXT_VIEW_FACING = 9;
                public const System.Int32 MESH_RESOURCE = 10;
                public const System.Int32 TRIANGLE_LIST = 11;
                public const System.Int32 ADD = 0;
                public const System.Int32 MODIFY = 0;
                public const System.Int32 DELETE = 2;
                public const System.Int32 DELETEALL = 3;

                public Marker()
                {
                    header = new std_msgs.msg.Header();
                    ns = "";
                    id = 0;
                    type = 0;
                    action = 0;
                    pose = new geometry_msgs.msg.Pose();
                    scale = new UnityEngine.Vector3();
                    color = new std_msgs.msg.ColorRGBA();
                    lifetime = new builtin_interfaces.msg.Duration();
                    frame_locked = false;
                    points = new System.Collections.Generic.List<UnityEngine.Vector3>();
                    colors = new System.Collections.Generic.List<std_msgs.msg.ColorRGBA>();
                    text = "";
                    mesh_resource = "";
                    mesh_use_embedded_materials = false;
                }

                public Marker(std_msgs.msg.Header _header, string _ns, System.Int32 _id, System.Int32 _type, System.Int32 _action, geometry_msgs.msg.Pose _pose, UnityEngine.Vector3 _scale, std_msgs.msg.ColorRGBA _color, builtin_interfaces.msg.Duration _lifetime, bool _frame_locked, System.Collections.Generic.List<UnityEngine.Vector3>  _points, System.Collections.Generic.List<std_msgs.msg.ColorRGBA>  _colors, string _text, string _mesh_resource, bool _mesh_use_embedded_materials)
                {
                    header = _header;
                    ns = _ns;
                    id = _id;
                    type = _type;
                    action = _action;
                    pose = _pose;
                    scale = _scale;
                    color = _color;
                    lifetime = _lifetime;
                    frame_locked = _frame_locked;
                    points = _points;
                    colors = _colors;
                    text = _text;
                    mesh_resource = _mesh_resource;
                    mesh_use_embedded_materials = _mesh_use_embedded_materials;
                }

                new public static string GetMessageType()
                {
                    return "visualization_msgs/msg/Marker";
                }

            } // class Marker

        } // namespace msg
    } // namespace visualization_msgs

} // namespace ROSBridgeLib
