// Generated by gencs from visualization_msgs/msg/MarkerArray.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.visualization_msgs.msg;

namespace ROSBridgeLib {

    namespace visualization_msgs {
        namespace msg {

            [System.Serializable]
            public class MarkerArray : ROSMessage
            {
                public System.Collections.Generic.List<visualization_msgs.msg.Marker>  markers;


                public MarkerArray()
                {
                    markers = new System.Collections.Generic.List<visualization_msgs.msg.Marker>();
                }

                public MarkerArray(System.Collections.Generic.List<visualization_msgs.msg.Marker>  _markers)
                {
                    markers = _markers;
                }

                new public static string GetMessageType()
                {
                    return "visualization_msgs/msg/MarkerArray";
                }

            } // class MarkerArray

        } // namespace msg
    } // namespace visualization_msgs

} // namespace ROSBridgeLib
