// Generated by gencs from visualization_msgs/msg/MenuEntry.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace visualization_msgs {
        namespace msg {

            [System.Serializable]
            public class MenuEntry : ROSMessage
            {
                public System.UInt32 id;
                public System.UInt32 parent_id;
                public string title;
                public string command;
                public byte command_type;

                // Constants:
                public const byte FEEDBACK = 0;
                public const byte ROSRUN = 1;
                public const byte ROSLAUNCH = 2;

                public MenuEntry()
                {
                    id = 0;
                    parent_id = 0;
                    title = "";
                    command = "";
                    command_type = 0;
                }

                public MenuEntry(System.UInt32 _id, System.UInt32 _parent_id, string _title, string _command, byte _command_type)
                {
                    id = _id;
                    parent_id = _parent_id;
                    title = _title;
                    command = _command;
                    command_type = _command_type;
                }

                new public static string GetMessageType()
                {
                    return "visualization_msgs/msg/MenuEntry";
                }

            } // class MenuEntry

        } // namespace msg
    } // namespace visualization_msgs

} // namespace ROSBridgeLib
