// Generated by gencs from shape_msgs/msg/Mesh.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.shape_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace shape_msgs {
        namespace msg {

            [System.Serializable]
            public class Mesh : ROSMessage
            {
                public System.Collections.Generic.List<shape_msgs.msg.MeshTriangle>  triangles;
                public System.Collections.Generic.List<UnityEngine.Vector3>  vertices;


                public Mesh()
                {
                    triangles = new System.Collections.Generic.List<shape_msgs.msg.MeshTriangle>();
                    vertices = new System.Collections.Generic.List<UnityEngine.Vector3>();
                }

                public Mesh(System.Collections.Generic.List<shape_msgs.msg.MeshTriangle>  _triangles, System.Collections.Generic.List<UnityEngine.Vector3>  _vertices)
                {
                    triangles = _triangles;
                    vertices = _vertices;
                }

                new public static string GetMessageType()
                {
                    return "shape_msgs/msg/Mesh";
                }

            } // class Mesh

        } // namespace msg
    } // namespace shape_msgs

} // namespace ROSBridgeLib
