// Generated by gencs from shape_msgs/msg/MeshTriangle.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace shape_msgs {
        namespace msg {

            [System.Serializable]
            public class MeshTriangle : ROSMessage
            {
                public System.UInt32[]  vertex_indices;


                public MeshTriangle()
                {
                    vertex_indices = new System.UInt32[3];
                }

                public MeshTriangle(System.UInt32[]  _vertex_indices)
                {
                    vertex_indices = _vertex_indices;
                }

                new public static string GetMessageType()
                {
                    return "shape_msgs/msg/MeshTriangle";
                }

            } // class MeshTriangle

        } // namespace msg
    } // namespace shape_msgs

} // namespace ROSBridgeLib
