// Generated by gencs from shape_msgs/msg/Plane.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace shape_msgs {
        namespace msg {

            [System.Serializable]
            public class Plane : ROSMessage
            {
                public double[]  coef;


                public Plane()
                {
                    coef = new double[4];
                }

                public Plane(double[]  _coef)
                {
                    coef = _coef;
                }

                new public static string GetMessageType()
                {
                    return "shape_msgs/msg/Plane";
                }

            } // class Plane

        } // namespace msg
    } // namespace shape_msgs

} // namespace ROSBridgeLib
