// Generated by gencs from shape_msgs/msg/SolidPrimitive.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace shape_msgs {
        namespace msg {

            [System.Serializable]
            public class SolidPrimitive : ROSMessage
            {
                public byte type;
                public System.Collections.Generic.List<double>  dimensions;

                // Constants:
                public const byte BOX = 1;
                public const byte SPHERE = 2;
                public const byte CYLINDER = 3;
                public const byte CONE = 4;
                public const byte BOX_X = 0;
                public const byte BOX_Y = 1;
                public const byte BOX_Z = 2;
                public const byte SPHERE_RADIUS = 0;
                public const byte CYLINDER_HEIGHT = 0;
                public const byte CYLINDER_RADIUS = 1;
                public const byte CONE_HEIGHT = 0;
                public const byte CONE_RADIUS = 1;

                public SolidPrimitive()
                {
                    type = 0;
                    dimensions = new System.Collections.Generic.List<double>();
                }

                public SolidPrimitive(byte _type, System.Collections.Generic.List<double>  _dimensions)
                {
                    type = _type;
                    dimensions = _dimensions;
                }

                new public static string GetMessageType()
                {
                    return "shape_msgs/msg/SolidPrimitive";
                }

            } // class SolidPrimitive

        } // namespace msg
    } // namespace shape_msgs

} // namespace ROSBridgeLib
