// Generated by gencs from std_srvs/Empty.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_srvs {

    [System.Serializable]
    public class EmptyRequest : ServiceArgs
    {


      public EmptyRequest()
      {

      }


      new public static string GetMessageType()
      {
        return "std_srvs/EmptyRequest";
      }

      new public static string GetMD5Hash()
      {
        return "d41d8cd98f00b204e9800998ecf8427e";
      }

    } // class EmptyRequest

  } // namespace std_srvs
 } // namespace ROS1
} // namespace ROSBridgeLib
