// Generated by gencs from file std_srvs/Empty.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ROS1;
using ROSBridgeLib.std_srvs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_srvs {

    public class Empty : ROSBridgeServiceProvider<std_srvs.EmptyRequest>
    {
      public Empty(string serviceName) : base(serviceName)
      {
        _type = "std_srvs/Empty";
      }

      public Empty(string serviceName, string serviceType = "std_srvs/Empty") : base(serviceName, serviceType) {}
    }

  } // namespace std_srvs
 } // namespace ROS1
} // namespace ROSBridgeLib

