// Generated by gencs from file std_srvs/SetBool.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ROS1;
using ROSBridgeLib.std_srvs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_srvs {

    public class SetBool : ROSBridgeServiceProvider<std_srvs.SetBoolRequest>
    {
      public SetBool(string serviceName) : base(serviceName)
      {
        _type = "std_srvs/SetBool";
      }

      public SetBool(string serviceName, string serviceType = "std_srvs/SetBool") : base(serviceName, serviceType) {}
    }

  } // namespace std_srvs
 } // namespace ROS1
} // namespace ROSBridgeLib

