// Generated by gencs from std_srvs/SetBool.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_srvs {

    [System.Serializable]
    public class SetBoolResponse : ServiceResponse
    {
      public bool success;
      public string message;


      public SetBoolResponse()
      {
        success = false;
        message = "";

      }

      public SetBoolResponse(bool _success, string _message)
      {
        success = _success;
        message = _message;
      }

      new public static string GetMessageType()
      {
        return "std_srvs/SetBoolResponse";
      }

      new public static string GetMD5Hash()
      {
        return "937c9679a518e3a18d831e57125ea522";
      }

    } // class SetBoolResponse

  } // namespace std_srvs
 } // namespace ROS1
} // namespace ROSBridgeLib
