// Generated by gencs from std_srvs/SetBool.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_srvs {

    [System.Serializable]
    public class SetBoolRequest : ServiceArgs
    {
      public bool data;


      public SetBoolRequest()
      {
        data = false;

      }

      public SetBoolRequest(bool _data)
      {
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "std_srvs/SetBoolRequest";
      }

      new public static string GetMD5Hash()
      {
        return "8b94c1b53db61fb6aed406028ad6332a";
      }

    } // class SetBoolRequest

  } // namespace std_srvs
 } // namespace ROS1
} // namespace ROSBridgeLib
