// Generated by gencs from file std_srvs/Trigger.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ROS1;
using ROSBridgeLib.std_srvs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace std_srvs {

    public class Trigger : ROSBridgeServiceProvider<std_srvs.TriggerRequest>
    {
      public Trigger(string serviceName) : base(serviceName)
      {
        _type = "std_srvs/Trigger";
      }

      public Trigger(string serviceName, string serviceType = "std_srvs/Trigger") : base(serviceName, serviceType) {}
    }

  } // namespace std_srvs
 } // namespace ROS1
} // namespace ROSBridgeLib

