// Generated by gencs from geometry_msgs/AccelWithCovariance.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace geometry_msgs {

    [System.Serializable]
    public class AccelWithCovariance : ROSMessage
    {
      public geometry_msgs.Accel accel;
      public double[]  covariance;


      public AccelWithCovariance()
      {
        accel = new geometry_msgs.Accel();
        covariance = new double[36];

      }

      public AccelWithCovariance(geometry_msgs.Accel _accel, double[]  _covariance)
      {
        accel = _accel;
        covariance = _covariance;
      }

      new public static string GetMessageType()
      {
        return "geometry_msgs/AccelWithCovariance";
      }

      new public static string GetMD5Hash()
      {
        return "ad5a718d699c6be72a02b8d6a139f334";
      }

    } // class AccelWithCovariance

  } // namespace geometry_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
