// Generated by gencs from geometry_msgs/Inertia.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace geometry_msgs {

    [System.Serializable]
    public class Inertia : ROSMessage
    {
      public double m;
      public UnityEngine.Vector3 com;
      public double ixx;
      public double ixy;
      public double ixz;
      public double iyy;
      public double iyz;
      public double izz;


      public Inertia()
      {
        m = 0.0;
        com = new UnityEngine.Vector3();
        ixx = 0.0;
        ixy = 0.0;
        ixz = 0.0;
        iyy = 0.0;
        iyz = 0.0;
        izz = 0.0;

      }

      public Inertia(double _m, UnityEngine.Vector3 _com, double _ixx, double _ixy, double _ixz, double _iyy, double _iyz, double _izz)
      {
        m = _m;
        com = _com;
        ixx = _ixx;
        ixy = _ixy;
        ixz = _ixz;
        iyy = _iyy;
        iyz = _iyz;
        izz = _izz;
      }

      new public static string GetMessageType()
      {
        return "geometry_msgs/Inertia";
      }

      new public static string GetMD5Hash()
      {
        return "1d26e4bb6c83ff141c5cf0d883c2b0fe";
      }

    } // class Inertia

  } // namespace geometry_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
