// Generated by gencs from geometry_msgs/Polygon.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace geometry_msgs {

    [System.Serializable]
    public class Polygon : ROSMessage
    {
      public System.Collections.Generic.List<geometry_msgs.Point32>  points;


      public Polygon()
      {
        points = new System.Collections.Generic.List<geometry_msgs.Point32>();

      }

      public Polygon(System.Collections.Generic.List<geometry_msgs.Point32>  _points)
      {
        points = _points;
      }

      new public static string GetMessageType()
      {
        return "geometry_msgs/Polygon";
      }

      new public static string GetMD5Hash()
      {
        return "cd60a26494a087f577976f0329fa120e";
      }

    } // class Polygon

  } // namespace geometry_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
