// Generated by gencs from geometry_msgs/PolygonStamped.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace geometry_msgs {

    [System.Serializable]
    public class PolygonStamped : ROSMessage
    {
      public std_msgs.Header header;
      public geometry_msgs.Polygon polygon;


      public PolygonStamped()
      {
        header = new std_msgs.Header();
        polygon = new geometry_msgs.Polygon();

      }

      public PolygonStamped(std_msgs.Header _header, geometry_msgs.Polygon _polygon)
      {
        header = _header;
        polygon = _polygon;
      }

      new public static string GetMessageType()
      {
        return "geometry_msgs/PolygonStamped";
      }

      new public static string GetMD5Hash()
      {
        return "c6be8f7dc3bee7fe9e8d296070f53340";
      }

    } // class PolygonStamped

  } // namespace geometry_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
