// Generated by gencs from geometry_msgs/PoseArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace geometry_msgs {

    [System.Serializable]
    public class PoseArray : ROSMessage
    {
      public std_msgs.Header header;
      public System.Collections.Generic.List<geometry_msgs.Pose>  poses;


      public PoseArray()
      {
        header = new std_msgs.Header();
        poses = new System.Collections.Generic.List<geometry_msgs.Pose>();

      }

      public PoseArray(std_msgs.Header _header, System.Collections.Generic.List<geometry_msgs.Pose>  _poses)
      {
        header = _header;
        poses = _poses;
      }

      new public static string GetMessageType()
      {
        return "geometry_msgs/PoseArray";
      }

      new public static string GetMD5Hash()
      {
        return "916c28c5764443f268b296bb671b9d97";
      }

    } // class PoseArray

  } // namespace geometry_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
