// Generated by gencs from geometry_msgs/Pose2D.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace geometry_msgs {

    [System.Serializable]
    public class Pose2D : ROSMessage
    {
      public double x;
      public double y;
      public double theta;


      public Pose2D()
      {
        x = 0.0;
        y = 0.0;
        theta = 0.0;

      }

      public Pose2D(double _x, double _y, double _theta)
      {
        x = _x;
        y = _y;
        theta = _theta;
      }

      new public static string GetMessageType()
      {
        return "geometry_msgs/Pose2D";
      }

      new public static string GetMD5Hash()
      {
        return "938fa65709584ad8e77d238529be13b8";
      }

    } // class Pose2D

  } // namespace geometry_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
