// Generated by gencs from geometry_msgs/TransformStamped.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace geometry_msgs {

    [System.Serializable]
    public class TransformStamped : ROSMessage
    {
      public std_msgs.Header header;
      public string child_frame_id;
      public geometry_msgs.Transform transform;


      public TransformStamped()
      {
        header = new std_msgs.Header();
        child_frame_id = "";
        transform = new geometry_msgs.Transform();

      }

      public TransformStamped(std_msgs.Header _header, string _child_frame_id, geometry_msgs.Transform _transform)
      {
        header = _header;
        child_frame_id = _child_frame_id;
        transform = _transform;
      }

      new public static string GetMessageType()
      {
        return "geometry_msgs/TransformStamped";
      }

      new public static string GetMD5Hash()
      {
        return "b5764a33bfeb3588febc2682852579b0";
      }

    } // class TransformStamped

  } // namespace geometry_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
