// Generated by gencs from geometry_msgs/TwistWithCovarianceStamped.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace geometry_msgs {

    [System.Serializable]
    public class TwistWithCovarianceStamped : ROSMessage
    {
      public std_msgs.Header header;
      public geometry_msgs.TwistWithCovariance twist;


      public TwistWithCovarianceStamped()
      {
        header = new std_msgs.Header();
        twist = new geometry_msgs.TwistWithCovariance();

      }

      public TwistWithCovarianceStamped(std_msgs.Header _header, geometry_msgs.TwistWithCovariance _twist)
      {
        header = _header;
        twist = _twist;
      }

      new public static string GetMessageType()
      {
        return "geometry_msgs/TwistWithCovarianceStamped";
      }

      new public static string GetMD5Hash()
      {
        return "8927a1a12fb2607ceea095b2dc440a96";
      }

    } // class TwistWithCovarianceStamped

  } // namespace geometry_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
