// Generated by gencs from geometry_msgs/TwistStamped.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace geometry_msgs {

    [System.Serializable]
    public class TwistStamped : ROSMessage
    {
      public std_msgs.Header header;
      public geometry_msgs.Twist twist;


      public TwistStamped()
      {
        header = new std_msgs.Header();
        twist = new geometry_msgs.Twist();

      }

      public TwistStamped(std_msgs.Header _header, geometry_msgs.Twist _twist)
      {
        header = _header;
        twist = _twist;
      }

      new public static string GetMessageType()
      {
        return "geometry_msgs/TwistStamped";
      }

      new public static string GetMD5Hash()
      {
        return "98d34b0043a2093cf9d9345ab6eef12e";
      }

    } // class TwistStamped

  } // namespace geometry_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
