// Generated by gencs from geometry_msgs/Wrench.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace geometry_msgs {

    [System.Serializable]
    public class Wrench : ROSMessage
    {
      public UnityEngine.Vector3 force;
      public UnityEngine.Vector3 torque;


      public Wrench()
      {
        force = new UnityEngine.Vector3();
        torque = new UnityEngine.Vector3();

      }

      public Wrench(UnityEngine.Vector3 _force, UnityEngine.Vector3 _torque)
      {
        force = _force;
        torque = _torque;
      }

      new public static string GetMessageType()
      {
        return "geometry_msgs/Wrench";
      }

      new public static string GetMD5Hash()
      {
        return "4f539cf138b23283b520fd271b567936";
      }

    } // class Wrench

  } // namespace geometry_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
