// Generated by gencs from action_msgs/srv/CancelGoal.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace action_msgs {
        namespace srv {

            public class CancelGoal : ROSBridgeServiceProvider<CancelGoal_Request>
            {

                public CancelGoal(string serviceName) : base(serviceName)
                {
                    _type = "action_msgs/srv/CancelGoal";
                }

                public CancelGoal(string serviceName, string serviceType = "action_msgs/srv/CancelGoal") : base(serviceName, serviceType) {}

            } // class CancelGoal

            [System.Serializable]
            public class CancelGoal_Request : ServiceArgs
            {
                public action_msgs.msg.GoalInfo goal_info;


                public CancelGoal_Request()
                {
                    goal_info = new action_msgs.msg.GoalInfo();
                }

                public CancelGoal_Request(action_msgs.msg.GoalInfo _goal_info)
                {
                    goal_info = _goal_info;
                }

                new public static string GetMessageType()
                {
                    return "action_msgs/srv/CancelGoal_Request";
                }

            } // class CancelGoal_Request

            [System.Serializable]
            public class CancelGoal_Response : ServiceResponse
            {
                public sbyte return_code;
                public System.Collections.Generic.List<action_msgs.msg.GoalInfo>  goals_canceling;

                // Constants:
                public const sbyte ERROR_NONE = 0;
                public const sbyte ERROR_REJECTED = 1;
                public const sbyte ERROR_UNKNOWN_GOAL_ID = 2;
                public const sbyte ERROR_GOAL_TERMINATED = 3;

                public CancelGoal_Response()
                {
                    return_code = 0;
                    goals_canceling = new System.Collections.Generic.List<action_msgs.msg.GoalInfo>();
                }

                public CancelGoal_Response(sbyte _return_code, System.Collections.Generic.List<action_msgs.msg.GoalInfo>  _goals_canceling)
                {
                    return_code = _return_code;
                    goals_canceling = _goals_canceling;
                }

                new public static string GetMessageType()
                {
                    return "action_msgs/srv/CancelGoal_Response";
                }

            } // class CancelGoal_Response

        } // namespace srv
    } // namespace action_msgs
} // namespace ROSBridgeLib
