// Generated by gencs from netft_utils/msg/Cancel.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace netft_utils {
        namespace msg {

            [System.Serializable]
            public class Cancel : ROSMessage
            {
                public bool to_cancel;


                public Cancel()
                {
                    to_cancel = false;
                }

                public Cancel(bool _to_cancel)
                {
                    to_cancel = _to_cancel;
                }

                new public static string GetMessageType()
                {
                    return "netft_utils/msg/Cancel";
                }

            } // class Cancel

        } // namespace msg
    } // namespace netft_utils

} // namespace ROSBridgeLib
