// Generated by gencs from file diagnostic_msgs/AddDiagnostics.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ROS1;
using ROSBridgeLib.diagnostic_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace diagnostic_msgs {

    public class AddDiagnostics : ROSBridgeServiceProvider<diagnostic_msgs.AddDiagnosticsRequest>
    {
      public AddDiagnostics(string serviceName) : base(serviceName)
      {
        _type = "diagnostic_msgs/AddDiagnostics";
      }

      public AddDiagnostics(string serviceName, string serviceType = "diagnostic_msgs/AddDiagnostics") : base(serviceName, serviceType) {}
    }

  } // namespace diagnostic_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib

