// Generated by gencs from diagnostic_msgs/AddDiagnostics.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace diagnostic_msgs {

    [System.Serializable]
    public class AddDiagnosticsResponse : ServiceResponse
    {
      public bool success;
      public string message;


      public AddDiagnosticsResponse()
      {
        success = false;
        message = "";

      }

      public AddDiagnosticsResponse(bool _success, string _message)
      {
        success = _success;
        message = _message;
      }

      new public static string GetMessageType()
      {
        return "diagnostic_msgs/AddDiagnosticsResponse";
      }

      new public static string GetMD5Hash()
      {
        return "937c9679a518e3a18d831e57125ea522";
      }

    } // class AddDiagnosticsResponse

  } // namespace diagnostic_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
