// Generated by gencs from diagnostic_msgs/AddDiagnostics.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace diagnostic_msgs {

    [System.Serializable]
    public class AddDiagnosticsRequest : ServiceArgs
    {
      public string load_namespace;


      public AddDiagnosticsRequest()
      {
        load_namespace = "";

      }

      public AddDiagnosticsRequest(string _load_namespace)
      {
        load_namespace = _load_namespace;
      }

      new public static string GetMessageType()
      {
        return "diagnostic_msgs/AddDiagnosticsRequest";
      }

      new public static string GetMD5Hash()
      {
        return "c26cf6e164288fbc6050d74f838bcdf0";
      }

    } // class AddDiagnosticsRequest

  } // namespace diagnostic_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
