// Generated by gencs from diagnostic_msgs/DiagnosticStatus.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.diagnostic_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace diagnostic_msgs {

    [System.Serializable]
    public class DiagnosticStatus : ROSMessage
    {
      public sbyte level;
      public string name;
      public string message;
      public string hardware_id;
      public System.Collections.Generic.List<diagnostic_msgs.KeyValue>  values;

      public const sbyte OK = 0;
      public const sbyte WARN = 1;
      public const sbyte ERROR = 2;
      public const sbyte STALE = 3;

      public DiagnosticStatus()
      {
        level = 0;
        name = "";
        message = "";
        hardware_id = "";
        values = new System.Collections.Generic.List<diagnostic_msgs.KeyValue>();

      }

      public DiagnosticStatus(sbyte _level, string _name, string _message, string _hardware_id, System.Collections.Generic.List<diagnostic_msgs.KeyValue>  _values)
      {
        level = _level;
        name = _name;
        message = _message;
        hardware_id = _hardware_id;
        values = _values;
      }

      new public static string GetMessageType()
      {
        return "diagnostic_msgs/DiagnosticStatus";
      }

      new public static string GetMD5Hash()
      {
        return "d0ce08bc6e5ba34c7754f563a9cabaf1";
      }

    } // class DiagnosticStatus

  } // namespace diagnostic_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
