// Generated by gencs from diagnostic_msgs/KeyValue.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace diagnostic_msgs {

    [System.Serializable]
    public class KeyValue : ROSMessage
    {
      public string key;
      public string value;


      public KeyValue()
      {
        key = "";
        value = "";

      }

      public KeyValue(string _key, string _value)
      {
        key = _key;
        value = _value;
      }

      new public static string GetMessageType()
      {
        return "diagnostic_msgs/KeyValue";
      }

      new public static string GetMD5Hash()
      {
        return "cf57fdc6617a881a88c16e768132149c";
      }

    } // class KeyValue

  } // namespace diagnostic_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
