// Generated by gencs from file diagnostic_msgs/SelfTest.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ROS1;
using ROSBridgeLib.diagnostic_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace diagnostic_msgs {

    public class SelfTest : ROSBridgeServiceProvider<diagnostic_msgs.SelfTestRequest>
    {
      public SelfTest(string serviceName) : base(serviceName)
      {
        _type = "diagnostic_msgs/SelfTest";
      }

      public SelfTest(string serviceName, string serviceType = "diagnostic_msgs/SelfTest") : base(serviceName, serviceType) {}
    }

  } // namespace diagnostic_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib

