// Generated by gencs from diagnostic_msgs/SelfTest.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.diagnostic_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace diagnostic_msgs {

    [System.Serializable]
    public class SelfTestResponse : ServiceResponse
    {
      public string id;
      public sbyte passed;
      public System.Collections.Generic.List<diagnostic_msgs.DiagnosticStatus>  status;


      public SelfTestResponse()
      {
        id = "";
        passed = 0;
        status = new System.Collections.Generic.List<diagnostic_msgs.DiagnosticStatus>();

      }

      public SelfTestResponse(string _id, sbyte _passed, System.Collections.Generic.List<diagnostic_msgs.DiagnosticStatus>  _status)
      {
        id = _id;
        passed = _passed;
        status = _status;
      }

      new public static string GetMessageType()
      {
        return "diagnostic_msgs/SelfTestResponse";
      }

      new public static string GetMD5Hash()
      {
        return "ac21b1bab7ab17546986536c22eb34e9";
      }

    } // class SelfTestResponse

  } // namespace diagnostic_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
