// Generated by gencs from diagnostic_msgs/SelfTest.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace diagnostic_msgs {

    [System.Serializable]
    public class SelfTestRequest : ServiceArgs
    {


      public SelfTestRequest()
      {

      }


      new public static string GetMessageType()
      {
        return "diagnostic_msgs/SelfTestRequest";
      }

      new public static string GetMD5Hash()
      {
        return "d41d8cd98f00b204e9800998ecf8427e";
      }

    } // class SelfTestRequest

  } // namespace diagnostic_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
