// Generated by gencs from nav_msgs/GetMapActionResult.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.actionlib_msgs;
using ROSBridgeLib.ROS1.nav_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class GetMapActionResult : ROSMessage
    {
      public std_msgs.Header header;
      public actionlib_msgs.GoalStatus status;
      public nav_msgs.GetMapResult result;


      public GetMapActionResult()
      {
        header = new std_msgs.Header();
        status = new actionlib_msgs.GoalStatus();
        result = new nav_msgs.GetMapResult();

      }

      public GetMapActionResult(std_msgs.Header _header, actionlib_msgs.GoalStatus _status, nav_msgs.GetMapResult _result)
      {
        header = _header;
        status = _status;
        result = _result;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/GetMapActionResult";
      }

      new public static string GetMD5Hash()
      {
        return "ac66e5b9a79bb4bbd33dab245236c892";
      }

    } // class GetMapActionResult

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
