// Generated by gencs from nav_msgs/GetMap.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.nav_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class GetMapResponse : ServiceResponse
    {
      public nav_msgs.OccupancyGrid map;


      public GetMapResponse()
      {
        map = new nav_msgs.OccupancyGrid();

      }

      public GetMapResponse(nav_msgs.OccupancyGrid _map)
      {
        map = _map;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/GetMapResponse";
      }

      new public static string GetMD5Hash()
      {
        return "6cdd0a18e0aff5b0a3ca2326a89b54ff";
      }

    } // class GetMapResponse

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
