// Generated by gencs from file nav_msgs/GetMap.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ROS1;
using ROSBridgeLib.nav_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    public class GetMap : ROSBridgeServiceProvider<nav_msgs.GetMapRequest>
    {
      public GetMap(string serviceName) : base(serviceName)
      {
        _type = "nav_msgs/GetMap";
      }

      public GetMap(string serviceName, string serviceType = "nav_msgs/GetMap") : base(serviceName, serviceType) {}
    }

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib

