// Generated by gencs from nav_msgs/GetMapFeedback.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class GetMapFeedback : ROSMessage
    {


      public GetMapFeedback()
      {

      }


      new public static string GetMessageType()
      {
        return "nav_msgs/GetMapFeedback";
      }

      new public static string GetMD5Hash()
      {
        return "d41d8cd98f00b204e9800998ecf8427e";
      }

    } // class GetMapFeedback

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
