// Generated by gencs from nav_msgs/GetMapActionFeedback.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.actionlib_msgs;
using ROSBridgeLib.ROS1.nav_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class GetMapActionFeedback : ROSMessage
    {
      public std_msgs.Header header;
      public actionlib_msgs.GoalStatus status;
      public nav_msgs.GetMapFeedback feedback;


      public GetMapActionFeedback()
      {
        header = new std_msgs.Header();
        status = new actionlib_msgs.GoalStatus();
        feedback = new nav_msgs.GetMapFeedback();

      }

      public GetMapActionFeedback(std_msgs.Header _header, actionlib_msgs.GoalStatus _status, nav_msgs.GetMapFeedback _feedback)
      {
        header = _header;
        status = _status;
        feedback = _feedback;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/GetMapActionFeedback";
      }

      new public static string GetMD5Hash()
      {
        return "aae20e09065c3809e8a8e87c4c8953fd";
      }

    } // class GetMapActionFeedback

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
