// Generated by gencs from nav_msgs/GetMapActionGoal.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.actionlib_msgs;
using ROSBridgeLib.ROS1.nav_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class GetMapActionGoal : ROSMessage
    {
      public std_msgs.Header header;
      public actionlib_msgs.GoalID goal_id;
      public nav_msgs.GetMapGoal goal;


      public GetMapActionGoal()
      {
        header = new std_msgs.Header();
        goal_id = new actionlib_msgs.GoalID();
        goal = new nav_msgs.GetMapGoal();

      }

      public GetMapActionGoal(std_msgs.Header _header, actionlib_msgs.GoalID _goal_id, nav_msgs.GetMapGoal _goal)
      {
        header = _header;
        goal_id = _goal_id;
        goal = _goal;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/GetMapActionGoal";
      }

      new public static string GetMD5Hash()
      {
        return "4b30be6cd12b9e72826df56b481f40e0";
      }

    } // class GetMapActionGoal

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
