// Generated by gencs from nav_msgs/GetPlan.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.nav_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class GetPlanResponse : ServiceResponse
    {
      public nav_msgs.Path plan;


      public GetPlanResponse()
      {
        plan = new nav_msgs.Path();

      }

      public GetPlanResponse(nav_msgs.Path _plan)
      {
        plan = _plan;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/GetPlanResponse";
      }

      new public static string GetMD5Hash()
      {
        return "0002bc113c0259d71f6cf8cbc9430e18";
      }

    } // class GetPlanResponse

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
