// Generated by gencs from file nav_msgs/GetPlan.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ROS1;
using ROSBridgeLib.nav_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    public class GetPlan : ROSBridgeServiceProvider<nav_msgs.GetPlanRequest>
    {
      public GetPlan(string serviceName) : base(serviceName)
      {
        _type = "nav_msgs/GetPlan";
      }

      public GetPlan(string serviceName, string serviceType = "nav_msgs/GetPlan") : base(serviceName, serviceType) {}
    }

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib

