// Generated by gencs from nav_msgs/GetPlan.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class GetPlanRequest : ServiceArgs
    {
      public geometry_msgs.PoseStamped start;
      public geometry_msgs.PoseStamped goal;
      public float tolerance;


      public GetPlanRequest()
      {
        start = new geometry_msgs.PoseStamped();
        goal = new geometry_msgs.PoseStamped();
        tolerance = 0.0f;

      }

      public GetPlanRequest(geometry_msgs.PoseStamped _start, geometry_msgs.PoseStamped _goal, float _tolerance)
      {
        start = _start;
        goal = _goal;
        tolerance = _tolerance;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/GetPlanRequest";
      }

      new public static string GetMD5Hash()
      {
        return "e25a43e0752bcca599a8c2eef8282df8";
      }

    } // class GetPlanRequest

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
