// Generated by gencs from nav_msgs/GridCells.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class GridCells : ROSMessage
    {
      public std_msgs.Header header;
      public float cell_width;
      public float cell_height;
      public System.Collections.Generic.List<UnityEngine.Vector3>  cells;


      public GridCells()
      {
        header = new std_msgs.Header();
        cell_width = 0.0f;
        cell_height = 0.0f;
        cells = new System.Collections.Generic.List<UnityEngine.Vector3>();

      }

      public GridCells(std_msgs.Header _header, float _cell_width, float _cell_height, System.Collections.Generic.List<UnityEngine.Vector3>  _cells)
      {
        header = _header;
        cell_width = _cell_width;
        cell_height = _cell_height;
        cells = _cells;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/GridCells";
      }

      new public static string GetMD5Hash()
      {
        return "b9e4f5df6d28e272ebde00a3994830f5";
      }

    } // class GridCells

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
