// Generated by gencs from nav_msgs/LoadMap.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class LoadMapRequest : ServiceArgs
    {
      public string map_url;


      public LoadMapRequest()
      {
        map_url = "";

      }

      public LoadMapRequest(string _map_url)
      {
        map_url = _map_url;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/LoadMapRequest";
      }

      new public static string GetMD5Hash()
      {
        return "3813ba1ae85fbcd4dc88c90f1426b90b";
      }

    } // class LoadMapRequest

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
