// Generated by gencs from file nav_msgs/LoadMap.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ROS1;
using ROSBridgeLib.nav_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    public class LoadMap : ROSBridgeServiceProvider<nav_msgs.LoadMapRequest>
    {
      public LoadMap(string serviceName) : base(serviceName)
      {
        _type = "nav_msgs/LoadMap";
      }

      public LoadMap(string serviceName, string serviceType = "nav_msgs/LoadMap") : base(serviceName, serviceType) {}
    }

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib

