// Generated by gencs from nav_msgs/LoadMap.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.nav_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class LoadMapResponse : ServiceResponse
    {
      public nav_msgs.OccupancyGrid map;
      public byte result;

      public const byte RESULT_SUCCESS = 0;
      public const byte RESULT_MAP_DOES_NOT_EXIST = 1;
      public const byte RESULT_INVALID_MAP_DATA = 2;
      public const byte RESULT_INVALID_MAP_METADATA = 3;
      public const byte RESULT_UNDEFINED_FAILURE = 255;

      public LoadMapResponse()
      {
        map = new nav_msgs.OccupancyGrid();
        result = 0;

      }

      public LoadMapResponse(nav_msgs.OccupancyGrid _map, byte _result)
      {
        map = _map;
        result = _result;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/LoadMapResponse";
      }

      new public static string GetMD5Hash()
      {
        return "079b9c828e9f7c1918bf86932fd7267e";
      }

    } // class LoadMapResponse

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
