// Generated by gencs from nav_msgs/MapMetaData.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class MapMetaData : ROSMessage
    {
      public ROSBridgeLib.msg_helpers.Time map_load_time;
      public float resolution;
      public System.UInt32 width;
      public System.UInt32 height;
      public geometry_msgs.Pose origin;


      public MapMetaData()
      {
        map_load_time = new ROSBridgeLib.msg_helpers.Time();
        resolution = 0.0f;
        width = 0;
        height = 0;
        origin = new geometry_msgs.Pose();

      }

      public MapMetaData(ROSBridgeLib.msg_helpers.Time _map_load_time, float _resolution, System.UInt32 _width, System.UInt32 _height, geometry_msgs.Pose _origin)
      {
        map_load_time = _map_load_time;
        resolution = _resolution;
        width = _width;
        height = _height;
        origin = _origin;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/MapMetaData";
      }

      new public static string GetMD5Hash()
      {
        return "10cfc8a2818024d3248802c00c95f11b";
      }

    } // class MapMetaData

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
