// Generated by gencs from nav_msgs/OccupancyGrid.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.nav_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class OccupancyGrid : ROSMessage
    {
      public std_msgs.Header header;
      public nav_msgs.MapMetaData info;
      public System.Collections.Generic.List<sbyte>  data;


      public OccupancyGrid()
      {
        header = new std_msgs.Header();
        info = new nav_msgs.MapMetaData();
        data = new System.Collections.Generic.List<sbyte>();

      }

      public OccupancyGrid(std_msgs.Header _header, nav_msgs.MapMetaData _info, System.Collections.Generic.List<sbyte>  _data)
      {
        header = _header;
        info = _info;
        data = _data;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/OccupancyGrid";
      }

      new public static string GetMD5Hash()
      {
        return "3381f2d731d4076ec5c71b0759edbe4e";
      }

    } // class OccupancyGrid

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
