// Generated by gencs from nav_msgs/Odometry.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class Odometry : ROSMessage
    {
      public std_msgs.Header header;
      public string child_frame_id;
      public geometry_msgs.PoseWithCovariance pose;
      public geometry_msgs.TwistWithCovariance twist;


      public Odometry()
      {
        header = new std_msgs.Header();
        child_frame_id = "";
        pose = new geometry_msgs.PoseWithCovariance();
        twist = new geometry_msgs.TwistWithCovariance();

      }

      public Odometry(std_msgs.Header _header, string _child_frame_id, geometry_msgs.PoseWithCovariance _pose, geometry_msgs.TwistWithCovariance _twist)
      {
        header = _header;
        child_frame_id = _child_frame_id;
        pose = _pose;
        twist = _twist;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/Odometry";
      }

      new public static string GetMD5Hash()
      {
        return "cd5e73d190d741a2f92e81eda573aca7";
      }

    } // class Odometry

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
