// Generated by gencs from nav_msgs/Path.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class Path : ROSMessage
    {
      public std_msgs.Header header;
      public System.Collections.Generic.List<geometry_msgs.PoseStamped>  poses;


      public Path()
      {
        header = new std_msgs.Header();
        poses = new System.Collections.Generic.List<geometry_msgs.PoseStamped>();

      }

      public Path(std_msgs.Header _header, System.Collections.Generic.List<geometry_msgs.PoseStamped>  _poses)
      {
        header = _header;
        poses = _poses;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/Path";
      }

      new public static string GetMD5Hash()
      {
        return "6227e2b7e9cce15051f669a5e197bbf7";
      }

    } // class Path

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
