// Generated by gencs from nav_msgs/SetMap.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.nav_msgs;
using ROSBridgeLib.ROS1.geometry_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    [System.Serializable]
    public class SetMapRequest : ServiceArgs
    {
      public nav_msgs.OccupancyGrid map;
      public geometry_msgs.PoseWithCovarianceStamped initial_pose;


      public SetMapRequest()
      {
        map = new nav_msgs.OccupancyGrid();
        initial_pose = new geometry_msgs.PoseWithCovarianceStamped();

      }

      public SetMapRequest(nav_msgs.OccupancyGrid _map, geometry_msgs.PoseWithCovarianceStamped _initial_pose)
      {
        map = _map;
        initial_pose = _initial_pose;
      }

      new public static string GetMessageType()
      {
        return "nav_msgs/SetMapRequest";
      }

      new public static string GetMD5Hash()
      {
        return "91149a20d7be299b87c340df8cc94fd4";
      }

    } // class SetMapRequest

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
