// Generated by gencs from file nav_msgs/SetMap.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ROS1;
using ROSBridgeLib.nav_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace nav_msgs {

    public class SetMap : ROSBridgeServiceProvider<nav_msgs.SetMapRequest>
    {
      public SetMap(string serviceName) : base(serviceName)
      {
        _type = "nav_msgs/SetMap";
      }

      public SetMap(string serviceName, string serviceType = "nav_msgs/SetMap") : base(serviceName, serviceType) {}
    }

  } // namespace nav_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib

