// Generated by gencs from sensor_msgs/msg/CameraInfo.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.sensor_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class CameraInfo : ROSMessage
            {
                public std_msgs.msg.Header header;
                public System.UInt32 height;
                public System.UInt32 width;
                public string distortion_model;
                public System.Collections.Generic.List<double>  d;
                public double[]  k;
                public double[]  r;
                public double[]  p;
                public System.UInt32 binning_x;
                public System.UInt32 binning_y;
                public sensor_msgs.msg.RegionOfInterest roi;


                public CameraInfo()
                {
                    header = new std_msgs.msg.Header();
                    height = 0;
                    width = 0;
                    distortion_model = "";
                    d = new System.Collections.Generic.List<double>();
                    k = new double[9];
                    r = new double[9];
                    p = new double[12];
                    binning_x = 0;
                    binning_y = 0;
                    roi = new sensor_msgs.msg.RegionOfInterest();
                }

                public CameraInfo(std_msgs.msg.Header _header, System.UInt32 _height, System.UInt32 _width, string _distortion_model, System.Collections.Generic.List<double>  _d, double[]  _k, double[]  _r, double[]  _p, System.UInt32 _binning_x, System.UInt32 _binning_y, sensor_msgs.msg.RegionOfInterest _roi)
                {
                    header = _header;
                    height = _height;
                    width = _width;
                    distortion_model = _distortion_model;
                    d = _d;
                    k = _k;
                    r = _r;
                    p = _p;
                    binning_x = _binning_x;
                    binning_y = _binning_y;
                    roi = _roi;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/CameraInfo";
                }

            } // class CameraInfo

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
