// Generated by gencs from sensor_msgs/msg/ChannelFloat32.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class ChannelFloat32 : ROSMessage
            {
                public string name;
                public System.Collections.Generic.List<float>  values;


                public ChannelFloat32()
                {
                    name = "";
                    values = new System.Collections.Generic.List<float>();
                }

                public ChannelFloat32(string _name, System.Collections.Generic.List<float>  _values)
                {
                    name = _name;
                    values = _values;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/ChannelFloat32";
                }

            } // class ChannelFloat32

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
