// Generated by gencs from sensor_msgs/msg/CompressedImage.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class CompressedImage : ROSMessage
            {
                public std_msgs.msg.Header header;
                public string format;
                public System.Collections.Generic.List<byte>  data;


                public CompressedImage()
                {
                    header = new std_msgs.msg.Header();
                    format = "";
                    data = new System.Collections.Generic.List<byte>();
                }

                public CompressedImage(std_msgs.msg.Header _header, string _format, System.Collections.Generic.List<byte>  _data)
                {
                    header = _header;
                    format = _format;
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/CompressedImage";
                }

            } // class CompressedImage

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
