// Generated by gencs from sensor_msgs/msg/FluidPressure.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class FluidPressure : ROSMessage
            {
                public std_msgs.msg.Header header;
                public double fluid_pressure;
                public double variance;


                public FluidPressure()
                {
                    header = new std_msgs.msg.Header();
                    fluid_pressure = 0.0f;
                    variance = 0.0f;
                }

                public FluidPressure(std_msgs.msg.Header _header, double _fluid_pressure, double _variance)
                {
                    header = _header;
                    fluid_pressure = _fluid_pressure;
                    variance = _variance;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/FluidPressure";
                }

            } // class FluidPressure

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
