// Generated by gencs from sensor_msgs/msg/Illuminance.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class Illuminance : ROSMessage
            {
                public std_msgs.msg.Header header;
                public double illuminance;
                public double variance;


                public Illuminance()
                {
                    header = new std_msgs.msg.Header();
                    illuminance = 0.0f;
                    variance = 0.0f;
                }

                public Illuminance(std_msgs.msg.Header _header, double _illuminance, double _variance)
                {
                    header = _header;
                    illuminance = _illuminance;
                    variance = _variance;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/Illuminance";
                }

            } // class Illuminance

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
