// Generated by gencs from sensor_msgs/msg/Image.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class Image : ROSMessage
            {
                public std_msgs.msg.Header header;
                public System.UInt32 height;
                public System.UInt32 width;
                public string encoding;
                public byte is_bigendian;
                public System.UInt32 step;
                public System.Collections.Generic.List<byte>  data;


                public Image()
                {
                    header = new std_msgs.msg.Header();
                    height = 0;
                    width = 0;
                    encoding = "";
                    is_bigendian = 0;
                    step = 0;
                    data = new System.Collections.Generic.List<byte>();
                }

                public Image(std_msgs.msg.Header _header, System.UInt32 _height, System.UInt32 _width, string _encoding, byte _is_bigendian, System.UInt32 _step, System.Collections.Generic.List<byte>  _data)
                {
                    header = _header;
                    height = _height;
                    width = _width;
                    encoding = _encoding;
                    is_bigendian = _is_bigendian;
                    step = _step;
                    data = _data;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/Image";
                }

            } // class Image

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
