// Generated by gencs from sensor_msgs/msg/Imu.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class Imu : ROSMessage
            {
                public std_msgs.msg.Header header;
                public UnityEngine.Quaternion orientation;
                public double[]  orientation_covariance;
                public UnityEngine.Vector3 angular_velocity;
                public double[]  angular_velocity_covariance;
                public UnityEngine.Vector3 linear_acceleration;
                public double[]  linear_acceleration_covariance;


                public Imu()
                {
                    header = new std_msgs.msg.Header();
                    orientation = new UnityEngine.Quaternion();
                    orientation_covariance = new double[9];
                    angular_velocity = new UnityEngine.Vector3();
                    angular_velocity_covariance = new double[9];
                    linear_acceleration = new UnityEngine.Vector3();
                    linear_acceleration_covariance = new double[9];
                }

                public Imu(std_msgs.msg.Header _header, UnityEngine.Quaternion _orientation, double[]  _orientation_covariance, UnityEngine.Vector3 _angular_velocity, double[]  _angular_velocity_covariance, UnityEngine.Vector3 _linear_acceleration, double[]  _linear_acceleration_covariance)
                {
                    header = _header;
                    orientation = _orientation;
                    orientation_covariance = _orientation_covariance;
                    angular_velocity = _angular_velocity;
                    angular_velocity_covariance = _angular_velocity_covariance;
                    linear_acceleration = _linear_acceleration;
                    linear_acceleration_covariance = _linear_acceleration_covariance;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/Imu";
                }

            } // class Imu

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
