// Generated by gencs from sensor_msgs/msg/JointState.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class JointState : ROSMessage
            {
                public std_msgs.msg.Header header;
                public System.Collections.Generic.List<string>  name;
                public System.Collections.Generic.List<double>  position;
                public System.Collections.Generic.List<double>  velocity;
                public System.Collections.Generic.List<double>  effort;


                public JointState()
                {
                    header = new std_msgs.msg.Header();
                    name = new System.Collections.Generic.List<string>();
                    position = new System.Collections.Generic.List<double>();
                    velocity = new System.Collections.Generic.List<double>();
                    effort = new System.Collections.Generic.List<double>();
                }

                public JointState(std_msgs.msg.Header _header, System.Collections.Generic.List<string>  _name, System.Collections.Generic.List<double>  _position, System.Collections.Generic.List<double>  _velocity, System.Collections.Generic.List<double>  _effort)
                {
                    header = _header;
                    name = _name;
                    position = _position;
                    velocity = _velocity;
                    effort = _effort;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/JointState";
                }

            } // class JointState

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
