// Generated by gencs from sensor_msgs/msg/MagneticField.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class MagneticField : ROSMessage
            {
                public std_msgs.msg.Header header;
                public UnityEngine.Vector3 magnetic_field;
                public double[]  magnetic_field_covariance;


                public MagneticField()
                {
                    header = new std_msgs.msg.Header();
                    magnetic_field = new UnityEngine.Vector3();
                    magnetic_field_covariance = new double[9];
                }

                public MagneticField(std_msgs.msg.Header _header, UnityEngine.Vector3 _magnetic_field, double[]  _magnetic_field_covariance)
                {
                    header = _header;
                    magnetic_field = _magnetic_field;
                    magnetic_field_covariance = _magnetic_field_covariance;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/MagneticField";
                }

            } // class MagneticField

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
