// Generated by gencs from sensor_msgs/msg/MultiDOFJointState.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class MultiDOFJointState : ROSMessage
            {
                public std_msgs.msg.Header header;
                public System.Collections.Generic.List<string>  joint_names;
                public System.Collections.Generic.List<geometry_msgs.msg.Transform>  transforms;
                public System.Collections.Generic.List<geometry_msgs.msg.Twist>  twist;
                public System.Collections.Generic.List<geometry_msgs.msg.Wrench>  wrench;


                public MultiDOFJointState()
                {
                    header = new std_msgs.msg.Header();
                    joint_names = new System.Collections.Generic.List<string>();
                    transforms = new System.Collections.Generic.List<geometry_msgs.msg.Transform>();
                    twist = new System.Collections.Generic.List<geometry_msgs.msg.Twist>();
                    wrench = new System.Collections.Generic.List<geometry_msgs.msg.Wrench>();
                }

                public MultiDOFJointState(std_msgs.msg.Header _header, System.Collections.Generic.List<string>  _joint_names, System.Collections.Generic.List<geometry_msgs.msg.Transform>  _transforms, System.Collections.Generic.List<geometry_msgs.msg.Twist>  _twist, System.Collections.Generic.List<geometry_msgs.msg.Wrench>  _wrench)
                {
                    header = _header;
                    joint_names = _joint_names;
                    transforms = _transforms;
                    twist = _twist;
                    wrench = _wrench;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/MultiDOFJointState";
                }

            } // class MultiDOFJointState

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
