// Generated by gencs from sensor_msgs/msg/NavSatFix.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.sensor_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class NavSatFix : ROSMessage
            {
                public std_msgs.msg.Header header;
                public sensor_msgs.msg.NavSatStatus status;
                public double latitude;
                public double longitude;
                public double altitude;
                public double[]  position_covariance;
                public byte position_covariance_type;

                // Constants:
                public const byte COVARIANCE_TYPE_UNKNOWN = 0;
                public const byte COVARIANCE_TYPE_APPROXIMATED = 1;
                public const byte COVARIANCE_TYPE_DIAGONAL_KNOWN = 2;
                public const byte COVARIANCE_TYPE_KNOWN = 3;

                public NavSatFix()
                {
                    header = new std_msgs.msg.Header();
                    status = new sensor_msgs.msg.NavSatStatus();
                    latitude = 0.0f;
                    longitude = 0.0f;
                    altitude = 0.0f;
                    position_covariance = new double[9];
                    position_covariance_type = 0;
                }

                public NavSatFix(std_msgs.msg.Header _header, sensor_msgs.msg.NavSatStatus _status, double _latitude, double _longitude, double _altitude, double[]  _position_covariance, byte _position_covariance_type)
                {
                    header = _header;
                    status = _status;
                    latitude = _latitude;
                    longitude = _longitude;
                    altitude = _altitude;
                    position_covariance = _position_covariance;
                    position_covariance_type = _position_covariance_type;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/NavSatFix";
                }

            } // class NavSatFix

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
