// Generated by gencs from sensor_msgs/msg/PointCloud.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.geometry_msgs.msg;
using ROSBridgeLib.sensor_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class PointCloud : ROSMessage
            {
                public std_msgs.msg.Header header;
                public System.Collections.Generic.List<geometry_msgs.msg.Point32>  points;
                public System.Collections.Generic.List<sensor_msgs.msg.ChannelFloat32>  channels;


                public PointCloud()
                {
                    header = new std_msgs.msg.Header();
                    points = new System.Collections.Generic.List<geometry_msgs.msg.Point32>();
                    channels = new System.Collections.Generic.List<sensor_msgs.msg.ChannelFloat32>();
                }

                public PointCloud(std_msgs.msg.Header _header, System.Collections.Generic.List<geometry_msgs.msg.Point32>  _points, System.Collections.Generic.List<sensor_msgs.msg.ChannelFloat32>  _channels)
                {
                    header = _header;
                    points = _points;
                    channels = _channels;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/PointCloud";
                }

            } // class PointCloud

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
