// Generated by gencs from sensor_msgs/msg/RelativeHumidity.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class RelativeHumidity : ROSMessage
            {
                public std_msgs.msg.Header header;
                public double relative_humidity;
                public double variance;


                public RelativeHumidity()
                {
                    header = new std_msgs.msg.Header();
                    relative_humidity = 0.0f;
                    variance = 0.0f;
                }

                public RelativeHumidity(std_msgs.msg.Header _header, double _relative_humidity, double _variance)
                {
                    header = _header;
                    relative_humidity = _relative_humidity;
                    variance = _variance;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/RelativeHumidity";
                }

            } // class RelativeHumidity

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
