// Generated by gencs from sensor_msgs/msg/Temperature.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class Temperature : ROSMessage
            {
                public std_msgs.msg.Header header;
                public double temperature;
                public double variance;


                public Temperature()
                {
                    header = new std_msgs.msg.Header();
                    temperature = 0.0f;
                    variance = 0.0f;
                }

                public Temperature(std_msgs.msg.Header _header, double _temperature, double _variance)
                {
                    header = _header;
                    temperature = _temperature;
                    variance = _variance;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/Temperature";
                }

            } // class Temperature

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
