// Generated by gencs from sensor_msgs/msg/TimeReference.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs.msg;
using ROSBridgeLib.builtin_interfaces.msg;

namespace ROSBridgeLib {

    namespace sensor_msgs {
        namespace msg {

            [System.Serializable]
            public class TimeReference : ROSMessage
            {
                public std_msgs.msg.Header header;
                public builtin_interfaces.msg.Time time_ref;
                public string source;


                public TimeReference()
                {
                    header = new std_msgs.msg.Header();
                    time_ref = new builtin_interfaces.msg.Time();
                    source = "";
                }

                public TimeReference(std_msgs.msg.Header _header, builtin_interfaces.msg.Time _time_ref, string _source)
                {
                    header = _header;
                    time_ref = _time_ref;
                    source = _source;
                }

                new public static string GetMessageType()
                {
                    return "sensor_msgs/msg/TimeReference";
                }

            } // class TimeReference

        } // namespace msg
    } // namespace sensor_msgs

} // namespace ROSBridgeLib
