// Generated by gencs from tf2_msgs/srv/FrameGraph.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace tf2_msgs {
        namespace srv {

            public class FrameGraph : ROSBridgeServiceProvider<FrameGraph_Request>
            {

                public FrameGraph(string serviceName) : base(serviceName)
                {
                    _type = "tf2_msgs/srv/FrameGraph";
                }

                public FrameGraph(string serviceName, string serviceType = "tf2_msgs/srv/FrameGraph") : base(serviceName, serviceType) {}

            } // class FrameGraph

            [System.Serializable]
            public class FrameGraph_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public FrameGraph_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public FrameGraph_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "tf2_msgs/srv/FrameGraph_Request";
                }

            } // class FrameGraph_Request

            [System.Serializable]
            public class FrameGraph_Response : ServiceResponse
            {
                public string frame_yaml;


                public FrameGraph_Response()
                {
                    frame_yaml = "";
                }

                public FrameGraph_Response(string _frame_yaml)
                {
                    frame_yaml = _frame_yaml;
                }

                new public static string GetMessageType()
                {
                    return "tf2_msgs/srv/FrameGraph_Response";
                }

            } // class FrameGraph_Response

        } // namespace srv
    } // namespace tf2_msgs
} // namespace ROSBridgeLib
