// Generated by gencs from rosapi_msgs/srv/DeleteParam.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class DeleteParam : ROSBridgeServiceProvider<DeleteParam_Request>
            {

                public DeleteParam(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/DeleteParam";
                }

                public DeleteParam(string serviceName, string serviceType = "rosapi_msgs/srv/DeleteParam") : base(serviceName, serviceType) {}

            } // class DeleteParam

            [System.Serializable]
            public class DeleteParam_Request : ServiceArgs
            {
                public string name;


                public DeleteParam_Request()
                {
                    name = "";
                }

                public DeleteParam_Request(string _name)
                {
                    name = _name;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/DeleteParam_Request";
                }

            } // class DeleteParam_Request

            [System.Serializable]
            public class DeleteParam_Response : ServiceResponse
            {
                public byte structure_needs_at_least_one_member;


                public DeleteParam_Response()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public DeleteParam_Response(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/DeleteParam_Response";
                }

            } // class DeleteParam_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
