// Generated by gencs from rosapi_msgs/srv/GetParam.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class GetParam : ROSBridgeServiceProvider<GetParam_Request>
            {

                public GetParam(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/GetParam";
                }

                public GetParam(string serviceName, string serviceType = "rosapi_msgs/srv/GetParam") : base(serviceName, serviceType) {}

            } // class GetParam

            [System.Serializable]
            public class GetParam_Request : ServiceArgs
            {
                public string name;
                public string default_value;


                public GetParam_Request()
                {
                    name = "";
                    default_value = "";
                }

                public GetParam_Request(string _name, string _default_value)
                {
                    name = _name;
                    default_value = _default_value;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/GetParam_Request";
                }

            } // class GetParam_Request

            [System.Serializable]
            public class GetParam_Response : ServiceResponse
            {
                public string value;


                public GetParam_Response()
                {
                    value = "";
                }

                public GetParam_Response(string _value)
                {
                    value = _value;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/GetParam_Response";
                }

            } // class GetParam_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
