// Generated by gencs from rosapi_msgs/srv/GetParamNames.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class GetParamNames : ROSBridgeServiceProvider<GetParamNames_Request>
            {

                public GetParamNames(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/GetParamNames";
                }

                public GetParamNames(string serviceName, string serviceType = "rosapi_msgs/srv/GetParamNames") : base(serviceName, serviceType) {}

            } // class GetParamNames

            [System.Serializable]
            public class GetParamNames_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public GetParamNames_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public GetParamNames_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/GetParamNames_Request";
                }

            } // class GetParamNames_Request

            [System.Serializable]
            public class GetParamNames_Response : ServiceResponse
            {
                public System.Collections.Generic.List<string>  names;


                public GetParamNames_Response()
                {
                    names = new System.Collections.Generic.List<string>();
                }

                public GetParamNames_Response(System.Collections.Generic.List<string>  _names)
                {
                    names = _names;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/GetParamNames_Response";
                }

            } // class GetParamNames_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
