// Generated by gencs from rosapi_msgs/srv/GetActionServers.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class GetActionServers : ROSBridgeServiceProvider<GetActionServers_Request>
            {

                public GetActionServers(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/GetActionServers";
                }

                public GetActionServers(string serviceName, string serviceType = "rosapi_msgs/srv/GetActionServers") : base(serviceName, serviceType) {}

            } // class GetActionServers

            [System.Serializable]
            public class GetActionServers_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public GetActionServers_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public GetActionServers_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/GetActionServers_Request";
                }

            } // class GetActionServers_Request

            [System.Serializable]
            public class GetActionServers_Response : ServiceResponse
            {
                public System.Collections.Generic.List<string>  action_servers;


                public GetActionServers_Response()
                {
                    action_servers = new System.Collections.Generic.List<string>();
                }

                public GetActionServers_Response(System.Collections.Generic.List<string>  _action_servers)
                {
                    action_servers = _action_servers;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/GetActionServers_Response";
                }

            } // class GetActionServers_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
