// Generated by gencs from rosapi_msgs/srv/GetROSVersion.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class GetROSVersion : ROSBridgeServiceProvider<GetROSVersion_Request>
            {

                public GetROSVersion(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/GetROSVersion";
                }

                public GetROSVersion(string serviceName, string serviceType = "rosapi_msgs/srv/GetROSVersion") : base(serviceName, serviceType) {}

            } // class GetROSVersion

            [System.Serializable]
            public class GetROSVersion_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public GetROSVersion_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public GetROSVersion_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/GetROSVersion_Request";
                }

            } // class GetROSVersion_Request

            [System.Serializable]
            public class GetROSVersion_Response : ServiceResponse
            {
                public byte version;
                public string distro;


                public GetROSVersion_Response()
                {
                    version = 0;
                    distro = "";
                }

                public GetROSVersion_Response(byte _version, string _distro)
                {
                    version = _version;
                    distro = _distro;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/GetROSVersion_Response";
                }

            } // class GetROSVersion_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
