// Generated by gencs from rosapi_msgs/srv/HasParam.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class HasParam : ROSBridgeServiceProvider<HasParam_Request>
            {

                public HasParam(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/HasParam";
                }

                public HasParam(string serviceName, string serviceType = "rosapi_msgs/srv/HasParam") : base(serviceName, serviceType) {}

            } // class HasParam

            [System.Serializable]
            public class HasParam_Request : ServiceArgs
            {
                public string name;


                public HasParam_Request()
                {
                    name = "";
                }

                public HasParam_Request(string _name)
                {
                    name = _name;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/HasParam_Request";
                }

            } // class HasParam_Request

            [System.Serializable]
            public class HasParam_Response : ServiceResponse
            {
                public bool exists;


                public HasParam_Response()
                {
                    exists = false;
                }

                public HasParam_Response(bool _exists)
                {
                    exists = _exists;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/HasParam_Response";
                }

            } // class HasParam_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
