// Generated by gencs from rosapi_msgs/srv/MessageDetails.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class MessageDetails : ROSBridgeServiceProvider<MessageDetails_Request>
            {

                public MessageDetails(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/MessageDetails";
                }

                public MessageDetails(string serviceName, string serviceType = "rosapi_msgs/srv/MessageDetails") : base(serviceName, serviceType) {}

            } // class MessageDetails

            [System.Serializable]
            public class MessageDetails_Request : ServiceArgs
            {
                public string type;


                public MessageDetails_Request()
                {
                    type = "";
                }

                public MessageDetails_Request(string _type)
                {
                    type = _type;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/MessageDetails_Request";
                }

            } // class MessageDetails_Request

            [System.Serializable]
            public class MessageDetails_Response : ServiceResponse
            {
                public System.Collections.Generic.List<rosapi_msgs.msg.TypeDef>  typedefs;


                public MessageDetails_Response()
                {
                    typedefs = new System.Collections.Generic.List<rosapi_msgs.msg.TypeDef>();
                }

                public MessageDetails_Response(System.Collections.Generic.List<rosapi_msgs.msg.TypeDef>  _typedefs)
                {
                    typedefs = _typedefs;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/MessageDetails_Response";
                }

            } // class MessageDetails_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
