// Generated by gencs from rosapi_msgs/srv/Nodes.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class Nodes : ROSBridgeServiceProvider<Nodes_Request>
            {

                public Nodes(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/Nodes";
                }

                public Nodes(string serviceName, string serviceType = "rosapi_msgs/srv/Nodes") : base(serviceName, serviceType) {}

            } // class Nodes

            [System.Serializable]
            public class Nodes_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public Nodes_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public Nodes_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/Nodes_Request";
                }

            } // class Nodes_Request

            [System.Serializable]
            public class Nodes_Response : ServiceResponse
            {
                public System.Collections.Generic.List<string>  nodes;


                public Nodes_Response()
                {
                    nodes = new System.Collections.Generic.List<string>();
                }

                public Nodes_Response(System.Collections.Generic.List<string>  _nodes)
                {
                    nodes = _nodes;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/Nodes_Response";
                }

            } // class Nodes_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
