// Generated by gencs from rosapi_msgs/srv/NodeDetails.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class NodeDetails : ROSBridgeServiceProvider<NodeDetails_Request>
            {

                public NodeDetails(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/NodeDetails";
                }

                public NodeDetails(string serviceName, string serviceType = "rosapi_msgs/srv/NodeDetails") : base(serviceName, serviceType) {}

            } // class NodeDetails

            [System.Serializable]
            public class NodeDetails_Request : ServiceArgs
            {
                public string node;


                public NodeDetails_Request()
                {
                    node = "";
                }

                public NodeDetails_Request(string _node)
                {
                    node = _node;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/NodeDetails_Request";
                }

            } // class NodeDetails_Request

            [System.Serializable]
            public class NodeDetails_Response : ServiceResponse
            {
                public System.Collections.Generic.List<string>  subscribing;
                public System.Collections.Generic.List<string>  publishing;
                public System.Collections.Generic.List<string>  services;


                public NodeDetails_Response()
                {
                    subscribing = new System.Collections.Generic.List<string>();
                    publishing = new System.Collections.Generic.List<string>();
                    services = new System.Collections.Generic.List<string>();
                }

                public NodeDetails_Response(System.Collections.Generic.List<string>  _subscribing, System.Collections.Generic.List<string>  _publishing, System.Collections.Generic.List<string>  _services)
                {
                    subscribing = _subscribing;
                    publishing = _publishing;
                    services = _services;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/NodeDetails_Response";
                }

            } // class NodeDetails_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
