// Generated by gencs from rosapi_msgs/srv/Publishers.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class Publishers : ROSBridgeServiceProvider<Publishers_Request>
            {

                public Publishers(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/Publishers";
                }

                public Publishers(string serviceName, string serviceType = "rosapi_msgs/srv/Publishers") : base(serviceName, serviceType) {}

            } // class Publishers

            [System.Serializable]
            public class Publishers_Request : ServiceArgs
            {
                public string topic;


                public Publishers_Request()
                {
                    topic = "";
                }

                public Publishers_Request(string _topic)
                {
                    topic = _topic;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/Publishers_Request";
                }

            } // class Publishers_Request

            [System.Serializable]
            public class Publishers_Response : ServiceResponse
            {
                public System.Collections.Generic.List<string>  publishers;


                public Publishers_Response()
                {
                    publishers = new System.Collections.Generic.List<string>();
                }

                public Publishers_Response(System.Collections.Generic.List<string>  _publishers)
                {
                    publishers = _publishers;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/Publishers_Response";
                }

            } // class Publishers_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
