// Generated by gencs from rosapi_msgs/srv/ServiceType.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class ServiceType : ROSBridgeServiceProvider<ServiceType_Request>
            {

                public ServiceType(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/ServiceType";
                }

                public ServiceType(string serviceName, string serviceType = "rosapi_msgs/srv/ServiceType") : base(serviceName, serviceType) {}

            } // class ServiceType

            [System.Serializable]
            public class ServiceType_Request : ServiceArgs
            {
                public string service;


                public ServiceType_Request()
                {
                    service = "";
                }

                public ServiceType_Request(string _service)
                {
                    service = _service;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/ServiceType_Request";
                }

            } // class ServiceType_Request

            [System.Serializable]
            public class ServiceType_Response : ServiceResponse
            {
                public string type;


                public ServiceType_Response()
                {
                    type = "";
                }

                public ServiceType_Response(string _type)
                {
                    type = _type;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/ServiceType_Response";
                }

            } // class ServiceType_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
