// Generated by gencs from rosapi_msgs/srv/ServiceNode.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class ServiceNode : ROSBridgeServiceProvider<ServiceNode_Request>
            {

                public ServiceNode(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/ServiceNode";
                }

                public ServiceNode(string serviceName, string serviceType = "rosapi_msgs/srv/ServiceNode") : base(serviceName, serviceType) {}

            } // class ServiceNode

            [System.Serializable]
            public class ServiceNode_Request : ServiceArgs
            {
                public string service;


                public ServiceNode_Request()
                {
                    service = "";
                }

                public ServiceNode_Request(string _service)
                {
                    service = _service;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/ServiceNode_Request";
                }

            } // class ServiceNode_Request

            [System.Serializable]
            public class ServiceNode_Response : ServiceResponse
            {
                public string node;


                public ServiceNode_Response()
                {
                    node = "";
                }

                public ServiceNode_Response(string _node)
                {
                    node = _node;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/ServiceNode_Response";
                }

            } // class ServiceNode_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
