// Generated by gencs from rosapi_msgs/srv/ServiceRequestDetails.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class ServiceRequestDetails : ROSBridgeServiceProvider<ServiceRequestDetails_Request>
            {

                public ServiceRequestDetails(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/ServiceRequestDetails";
                }

                public ServiceRequestDetails(string serviceName, string serviceType = "rosapi_msgs/srv/ServiceRequestDetails") : base(serviceName, serviceType) {}

            } // class ServiceRequestDetails

            [System.Serializable]
            public class ServiceRequestDetails_Request : ServiceArgs
            {
                public string type;


                public ServiceRequestDetails_Request()
                {
                    type = "";
                }

                public ServiceRequestDetails_Request(string _type)
                {
                    type = _type;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/ServiceRequestDetails_Request";
                }

            } // class ServiceRequestDetails_Request

            [System.Serializable]
            public class ServiceRequestDetails_Response : ServiceResponse
            {
                public System.Collections.Generic.List<rosapi_msgs.msg.TypeDef>  typedefs;


                public ServiceRequestDetails_Response()
                {
                    typedefs = new System.Collections.Generic.List<rosapi_msgs.msg.TypeDef>();
                }

                public ServiceRequestDetails_Response(System.Collections.Generic.List<rosapi_msgs.msg.TypeDef>  _typedefs)
                {
                    typedefs = _typedefs;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/ServiceRequestDetails_Response";
                }

            } // class ServiceRequestDetails_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
