// Generated by gencs from rosapi_msgs/srv/ServiceResponseDetails.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class ServiceResponseDetails : ROSBridgeServiceProvider<ServiceResponseDetails_Request>
            {

                public ServiceResponseDetails(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/ServiceResponseDetails";
                }

                public ServiceResponseDetails(string serviceName, string serviceType = "rosapi_msgs/srv/ServiceResponseDetails") : base(serviceName, serviceType) {}

            } // class ServiceResponseDetails

            [System.Serializable]
            public class ServiceResponseDetails_Request : ServiceArgs
            {
                public string type;


                public ServiceResponseDetails_Request()
                {
                    type = "";
                }

                public ServiceResponseDetails_Request(string _type)
                {
                    type = _type;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/ServiceResponseDetails_Request";
                }

            } // class ServiceResponseDetails_Request

            [System.Serializable]
            public class ServiceResponseDetails_Response : ServiceResponse
            {
                public System.Collections.Generic.List<rosapi_msgs.msg.TypeDef>  typedefs;


                public ServiceResponseDetails_Response()
                {
                    typedefs = new System.Collections.Generic.List<rosapi_msgs.msg.TypeDef>();
                }

                public ServiceResponseDetails_Response(System.Collections.Generic.List<rosapi_msgs.msg.TypeDef>  _typedefs)
                {
                    typedefs = _typedefs;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/ServiceResponseDetails_Response";
                }

            } // class ServiceResponseDetails_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
