// Generated by gencs from rosapi_msgs/srv/ServicesForType.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class ServicesForType : ROSBridgeServiceProvider<ServicesForType_Request>
            {

                public ServicesForType(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/ServicesForType";
                }

                public ServicesForType(string serviceName, string serviceType = "rosapi_msgs/srv/ServicesForType") : base(serviceName, serviceType) {}

            } // class ServicesForType

            [System.Serializable]
            public class ServicesForType_Request : ServiceArgs
            {
                public string type;


                public ServicesForType_Request()
                {
                    type = "";
                }

                public ServicesForType_Request(string _type)
                {
                    type = _type;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/ServicesForType_Request";
                }

            } // class ServicesForType_Request

            [System.Serializable]
            public class ServicesForType_Response : ServiceResponse
            {
                public System.Collections.Generic.List<string>  services;


                public ServicesForType_Response()
                {
                    services = new System.Collections.Generic.List<string>();
                }

                public ServicesForType_Response(System.Collections.Generic.List<string>  _services)
                {
                    services = _services;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/ServicesForType_Response";
                }

            } // class ServicesForType_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
