// Generated by gencs from rosapi_msgs/srv/Services.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class Services : ROSBridgeServiceProvider<Services_Request>
            {

                public Services(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/Services";
                }

                public Services(string serviceName, string serviceType = "rosapi_msgs/srv/Services") : base(serviceName, serviceType) {}

            } // class Services

            [System.Serializable]
            public class Services_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public Services_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public Services_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/Services_Request";
                }

            } // class Services_Request

            [System.Serializable]
            public class Services_Response : ServiceResponse
            {
                public System.Collections.Generic.List<string>  services;


                public Services_Response()
                {
                    services = new System.Collections.Generic.List<string>();
                }

                public Services_Response(System.Collections.Generic.List<string>  _services)
                {
                    services = _services;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/Services_Response";
                }

            } // class Services_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
