// Generated by gencs from rosapi_msgs/srv/SetParam.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class SetParam : ROSBridgeServiceProvider<SetParam_Request>
            {

                public SetParam(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/SetParam";
                }

                public SetParam(string serviceName, string serviceType = "rosapi_msgs/srv/SetParam") : base(serviceName, serviceType) {}

            } // class SetParam

            [System.Serializable]
            public class SetParam_Request : ServiceArgs
            {
                public string name;
                public string value;


                public SetParam_Request()
                {
                    name = "";
                    value = "";
                }

                public SetParam_Request(string _name, string _value)
                {
                    name = _name;
                    value = _value;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/SetParam_Request";
                }

            } // class SetParam_Request

            [System.Serializable]
            public class SetParam_Response : ServiceResponse
            {
                public byte structure_needs_at_least_one_member;


                public SetParam_Response()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public SetParam_Response(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/SetParam_Response";
                }

            } // class SetParam_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
