// Generated by gencs from rosapi_msgs/srv/Subscribers.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class Subscribers : ROSBridgeServiceProvider<Subscribers_Request>
            {

                public Subscribers(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/Subscribers";
                }

                public Subscribers(string serviceName, string serviceType = "rosapi_msgs/srv/Subscribers") : base(serviceName, serviceType) {}

            } // class Subscribers

            [System.Serializable]
            public class Subscribers_Request : ServiceArgs
            {
                public string topic;


                public Subscribers_Request()
                {
                    topic = "";
                }

                public Subscribers_Request(string _topic)
                {
                    topic = _topic;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/Subscribers_Request";
                }

            } // class Subscribers_Request

            [System.Serializable]
            public class Subscribers_Response : ServiceResponse
            {
                public System.Collections.Generic.List<string>  subscribers;


                public Subscribers_Response()
                {
                    subscribers = new System.Collections.Generic.List<string>();
                }

                public Subscribers_Response(System.Collections.Generic.List<string>  _subscribers)
                {
                    subscribers = _subscribers;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/Subscribers_Response";
                }

            } // class Subscribers_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
