// Generated by gencs from rosapi_msgs/srv/TopicsForType.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class TopicsForType : ROSBridgeServiceProvider<TopicsForType_Request>
            {

                public TopicsForType(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/TopicsForType";
                }

                public TopicsForType(string serviceName, string serviceType = "rosapi_msgs/srv/TopicsForType") : base(serviceName, serviceType) {}

            } // class TopicsForType

            [System.Serializable]
            public class TopicsForType_Request : ServiceArgs
            {
                public string type;


                public TopicsForType_Request()
                {
                    type = "";
                }

                public TopicsForType_Request(string _type)
                {
                    type = _type;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/TopicsForType_Request";
                }

            } // class TopicsForType_Request

            [System.Serializable]
            public class TopicsForType_Response : ServiceResponse
            {
                public System.Collections.Generic.List<string>  topics;


                public TopicsForType_Response()
                {
                    topics = new System.Collections.Generic.List<string>();
                }

                public TopicsForType_Response(System.Collections.Generic.List<string>  _topics)
                {
                    topics = _topics;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/TopicsForType_Response";
                }

            } // class TopicsForType_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
