// Generated by gencs from rosapi_msgs/srv/TopicsAndRawTypes.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {


    namespace rosapi_msgs {
        namespace srv {

            public class TopicsAndRawTypes : ROSBridgeServiceProvider<TopicsAndRawTypes_Request>
            {

                public TopicsAndRawTypes(string serviceName) : base(serviceName)
                {
                    _type = "rosapi_msgs/srv/TopicsAndRawTypes";
                }

                public TopicsAndRawTypes(string serviceName, string serviceType = "rosapi_msgs/srv/TopicsAndRawTypes") : base(serviceName, serviceType) {}

            } // class TopicsAndRawTypes

            [System.Serializable]
            public class TopicsAndRawTypes_Request : ServiceArgs
            {
                public byte structure_needs_at_least_one_member;


                public TopicsAndRawTypes_Request()
                {
                    structure_needs_at_least_one_member = 0;
                }

                public TopicsAndRawTypes_Request(byte _structure_needs_at_least_one_member)
                {
                    structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/TopicsAndRawTypes_Request";
                }

            } // class TopicsAndRawTypes_Request

            [System.Serializable]
            public class TopicsAndRawTypes_Response : ServiceResponse
            {
                public System.Collections.Generic.List<string>  topics;
                public System.Collections.Generic.List<string>  types;
                public System.Collections.Generic.List<string>  typedefs_full_text;


                public TopicsAndRawTypes_Response()
                {
                    topics = new System.Collections.Generic.List<string>();
                    types = new System.Collections.Generic.List<string>();
                    typedefs_full_text = new System.Collections.Generic.List<string>();
                }

                public TopicsAndRawTypes_Response(System.Collections.Generic.List<string>  _topics, System.Collections.Generic.List<string>  _types, System.Collections.Generic.List<string>  _typedefs_full_text)
                {
                    topics = _topics;
                    types = _types;
                    typedefs_full_text = _typedefs_full_text;
                }

                new public static string GetMessageType()
                {
                    return "rosapi_msgs/srv/TopicsAndRawTypes_Response";
                }

            } // class TopicsAndRawTypes_Response

        } // namespace srv
    } // namespace rosapi_msgs
} // namespace ROSBridgeLib
