// Generated by gencs from builtin_interfaces/msg/Time.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace builtin_interfaces {
        namespace msg {

            [System.Serializable]
            public class Time : ROSMessage
            {
                public System.Int32 sec;
                public System.UInt32 nanosec;


                public Time()
                {
                    sec = 0;
                    nanosec = 0;
                }

                public Time(System.Int32 _sec, System.UInt32 _nanosec)
                {
                    sec = _sec;
                    nanosec = _nanosec;
                }

                new public static string GetMessageType()
                {
                    return "builtin_interfaces/msg/Time";
                }

            } // class Time

        } // namespace msg
    } // namespace builtin_interfaces

} // namespace ROSBridgeLib
