// Generated by gencs from unique_identifier_msgs/msg/UUID.idl
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {

    namespace unique_identifier_msgs {
        namespace msg {

            [System.Serializable]
            public class UUID : ROSMessage
            {
                public byte[]  uuid;


                public UUID()
                {
                    uuid = new byte[16];
                }

                public UUID(byte[]  _uuid)
                {
                    uuid = _uuid;
                }

                new public static string GetMessageType()
                {
                    return "unique_identifier_msgs/msg/UUID";
                }

            } // class UUID

        } // namespace msg
    } // namespace unique_identifier_msgs

} // namespace ROSBridgeLib
