// Generated by gencs from rosgraph_msgs/Clock.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace rosgraph_msgs {

    [System.Serializable]
    public class Clock : ROSMessage
    {
      public ROSBridgeLib.msg_helpers.Time clock;


      public Clock()
      {
        clock = new ROSBridgeLib.msg_helpers.Time();

      }

      public Clock(ROSBridgeLib.msg_helpers.Time _clock)
      {
        clock = _clock;
      }

      new public static string GetMessageType()
      {
        return "rosgraph_msgs/Clock";
      }

      new public static string GetMD5Hash()
      {
        return "a9c97c1d230cfc112e270351a944ee47";
      }

    } // class Clock

  } // namespace rosgraph_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
