// Generated by gencs from rosgraph_msgs/Log.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;

using ROSBridgeLib.ROS1.std_msgs;

namespace ROSBridgeLib {
 namespace ROS1 {
  namespace rosgraph_msgs {

    [System.Serializable]
    public class Log : ROSMessage
    {
      public std_msgs.Header header;
      public sbyte level;
      public string name;
      public string msg;
      public string file;
      public string function;
      public System.UInt32 line;
      public System.Collections.Generic.List<string>  topics;

      public const sbyte DEBUG = 1;
      public const sbyte INFO = 2;
      public const sbyte WARN = 4;
      public const sbyte ERROR = 8;
      public const sbyte FATAL = 16;

      public Log()
      {
        header = new std_msgs.Header();
        level = 0;
        name = "";
        msg = "";
        file = "";
        function = "";
        line = 0;
        topics = new System.Collections.Generic.List<string>();

      }

      public Log(std_msgs.Header _header, sbyte _level, string _name, string _msg, string _file, string _function, System.UInt32 _line, System.Collections.Generic.List<string>  _topics)
      {
        header = _header;
        level = _level;
        name = _name;
        msg = _msg;
        file = _file;
        function = _function;
        line = _line;
        topics = _topics;
      }

      new public static string GetMessageType()
      {
        return "rosgraph_msgs/Log";
      }

      new public static string GetMD5Hash()
      {
        return "acffd30cd6b6de30f120938c17c593fb";
      }

    } // class Log

  } // namespace rosgraph_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
