// Generated by gencs from rosgraph_msgs/TopicStatistics.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using ROSBridgeLib.ROS1;
using UnityEngine;


namespace ROSBridgeLib {
 namespace ROS1 {
  namespace rosgraph_msgs {

    [System.Serializable]
    public class TopicStatistics : ROSMessage
    {
      public string topic;
      public string node_pub;
      public string node_sub;
      public ROSBridgeLib.msg_helpers.Time window_start;
      public ROSBridgeLib.msg_helpers.Time window_stop;
      public System.Int32 delivered_msgs;
      public System.Int32 dropped_msgs;
      public System.Int32 traffic;
      public ROSBridgeLib.msg_helpers.Duration period_mean;
      public ROSBridgeLib.msg_helpers.Duration period_stddev;
      public ROSBridgeLib.msg_helpers.Duration period_max;
      public ROSBridgeLib.msg_helpers.Duration stamp_age_mean;
      public ROSBridgeLib.msg_helpers.Duration stamp_age_stddev;
      public ROSBridgeLib.msg_helpers.Duration stamp_age_max;


      public TopicStatistics()
      {
        topic = "";
        node_pub = "";
        node_sub = "";
        window_start = new ROSBridgeLib.msg_helpers.Time();
        window_stop = new ROSBridgeLib.msg_helpers.Time();
        delivered_msgs = 0;
        dropped_msgs = 0;
        traffic = 0;
        period_mean = new ROSBridgeLib.msg_helpers.Duration();
        period_stddev = new ROSBridgeLib.msg_helpers.Duration();
        period_max = new ROSBridgeLib.msg_helpers.Duration();
        stamp_age_mean = new ROSBridgeLib.msg_helpers.Duration();
        stamp_age_stddev = new ROSBridgeLib.msg_helpers.Duration();
        stamp_age_max = new ROSBridgeLib.msg_helpers.Duration();

      }

      public TopicStatistics(string _topic, string _node_pub, string _node_sub, ROSBridgeLib.msg_helpers.Time _window_start, ROSBridgeLib.msg_helpers.Time _window_stop, System.Int32 _delivered_msgs, System.Int32 _dropped_msgs, System.Int32 _traffic, ROSBridgeLib.msg_helpers.Duration _period_mean, ROSBridgeLib.msg_helpers.Duration _period_stddev, ROSBridgeLib.msg_helpers.Duration _period_max, ROSBridgeLib.msg_helpers.Duration _stamp_age_mean, ROSBridgeLib.msg_helpers.Duration _stamp_age_stddev, ROSBridgeLib.msg_helpers.Duration _stamp_age_max)
      {
        topic = _topic;
        node_pub = _node_pub;
        node_sub = _node_sub;
        window_start = _window_start;
        window_stop = _window_stop;
        delivered_msgs = _delivered_msgs;
        dropped_msgs = _dropped_msgs;
        traffic = _traffic;
        period_mean = _period_mean;
        period_stddev = _period_stddev;
        period_max = _period_max;
        stamp_age_mean = _stamp_age_mean;
        stamp_age_stddev = _stamp_age_stddev;
        stamp_age_max = _stamp_age_max;
      }

      new public static string GetMessageType()
      {
        return "rosgraph_msgs/TopicStatistics";
      }

      new public static string GetMD5Hash()
      {
        return "10152ed868c5097a5e2e4a89d7daa710";
      }

    } // class TopicStatistics

  } // namespace rosgraph_msgs
 } // namespace ROS1
} // namespace ROSBridgeLib
